// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: copyfrom.go

package sqlc

import (
	"context"
)

// iteratorForCreateWorkloadEnvVars implements pgx.CopyFromSource.
type iteratorForCreateWorkloadEnvVars struct {
	rows                 []CreateWorkloadEnvVarsParams
	skippedFirstNextCall bool
}

func (r *iteratorForCreateWorkloadEnvVars) Next() bool {
	if len(r.rows) == 0 {
		return false
	}
	if !r.skippedFirstNextCall {
		r.skippedFirstNextCall = true
		return true
	}
	r.rows = r.rows[1:]
	return len(r.rows) > 0
}

func (r iteratorForCreateWorkloadEnvVars) Values() ([]interface{}, error) {
	return []interface{}{
		r.rows[0].WorkloadID,
		r.rows[0].Key,
		r.rows[0].ValueEncrypted,
		r.rows[0].IsSecret,
	}, nil
}

func (r iteratorForCreateWorkloadEnvVars) Err() error {
	return nil
}

func (q *Queries) CreateWorkloadEnvVars(ctx context.Context, arg []CreateWorkloadEnvVarsParams) (int64, error) {
	return q.db.CopyFrom(ctx, []string{"workload_env_vars"}, []string{"workload_id", "key", "value_encrypted", "is_secret"}, &iteratorForCreateWorkloadEnvVars{rows: arg})
}
