// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"time"

	"github.com/google/uuid"
)

type App struct {
	ID             uuid.UUID
	ProjectID      uuid.UUID
	Name           string
	Slug           string
	Subdomain      string
	ImageRef       string
	TargetReplicas int32
	PrimaryRegion  string
	RuntimePort    int32
	IsPublic       bool
	Status         string
	CreatedAt      time.Time
	UpdatedAt      time.Time
}

type AppEnvVar struct {
	ID             uuid.UUID
	AppID          uuid.UUID
	Key            string
	ValueEncrypted string
	CipherVersion  *string
	CipherAlgo     *string
	CipherKeyID    *string
	IsSecret       bool
	CreatedAt      time.Time
	UpdatedAt      time.Time
}

type AppRegistryCredential struct {
	AppID                uuid.UUID
	RegistryCredentialID uuid.UUID
	CreatedAt            time.Time
	LastUsed             *time.Time
}

type Deployment struct {
	ID           uuid.UUID
	AppID        uuid.UUID
	Status       string
	ImageRef     string
	RuntimePort  int32
	PublicUrl    *string
	ErrorMessage *string
	CreatedAt    time.Time
	UpdatedAt    time.Time
}

type Microvm struct {
	ID           uuid.UUID
	WorkspaceID  uuid.UUID
	ResourceType string
	ResourceID   *uuid.UUID
	Metadata     []byte
	NodeID       *uuid.UUID
	Region       string
	Vcpu         int32
	RamMb        int64
	CpuMode      string
	RootDiskMb   int64
	VolumeMb     int64
	Status       string
	ErrorMessage *string
	CreatedAt    time.Time
	UpdatedAt    time.Time
}

type NameWord struct {
	ID        uuid.UUID
	Word      string
	Kind      string
	Enabled   bool
	CreatedAt time.Time
	UpdatedAt time.Time
}

type Node struct {
	ID                 uuid.UUID
	Provider           string
	ProviderServerID   string
	Region             string
	BootstrapTokenHash *string
	CreatedAt          time.Time
	UpdatedAt          time.Time
}

type Project struct {
	ID          uuid.UUID
	WorkspaceID uuid.UUID
	Name        string
	Slug        string
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

type RegistryCredential struct {
	ID             uuid.UUID
	ProjectID      uuid.UUID
	Name           string
	RegistryUrl    string
	Username       string
	TokenEncrypted string
	CreatedAt      time.Time
	UpdatedAt      time.Time
	LastUsed       *time.Time
}

type User struct {
	ID                  uuid.UUID
	IdentityKey         string
	Email               *string
	Name                *string
	AvatarUrl           *string
	OnboardingCompleted bool
	CreatedAt           time.Time
	UpdatedAt           time.Time
}

type Workspace struct {
	ID          uuid.UUID
	OwnerUserID uuid.UUID
	Name        string
	CreatedAt   time.Time
	UpdatedAt   time.Time
}
