// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: nodes.sql

package sqlc

import (
	"context"
)

const updateProvisioningNodeFromBootstrap = `-- name: UpdateProvisioningNodeFromBootstrap :one
UPDATE nodes
SET bootstrap_token_hash = NULL,
    updated_at = NOW()
WHERE bootstrap_token_hash = $1
RETURNING id, provider, provider_server_id, region, bootstrap_token_hash, created_at, updated_at
`

func (q *Queries) UpdateProvisioningNodeFromBootstrap(ctx context.Context, bootstrapTokenHash *string) (Node, error) {
	row := q.db.QueryRow(ctx, updateProvisioningNodeFromBootstrap, bootstrapTokenHash)
	var i Node
	err := row.Scan(
		&i.ID,
		&i.Provider,
		&i.ProviderServerID,
		&i.Region,
		&i.BootstrapTokenHash,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
