// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const getUserByID = `-- name: GetUserByID :one
SELECT id, identity_key, email, name, avatar_url, created_at, updated_at
FROM users
WHERE id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.IdentityKey,
		&i.Email,
		&i.Name,
		&i.AvatarUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByIdentityKey = `-- name: GetUserByIdentityKey :one
SELECT id, identity_key, email, name, avatar_url, created_at, updated_at
FROM users
WHERE identity_key = $1
`

func (q *Queries) GetUserByIdentityKey(ctx context.Context, identityKey string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByIdentityKey, identityKey)
	var i User
	err := row.Scan(
		&i.ID,
		&i.IdentityKey,
		&i.Email,
		&i.Name,
		&i.AvatarUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertUserByIdentityKey = `-- name: UpsertUserByIdentityKey :one
INSERT INTO users (identity_key, email, name, avatar_url, created_at, updated_at)
VALUES ($1, $2, $3, $4, now(), now()) ON CONFLICT (identity_key) DO
UPDATE
    SET email = EXCLUDED.email,
    name = EXCLUDED.name,
    avatar_url = EXCLUDED.avatar_url,
    updated_at = now()
    RETURNING id, identity_key, email, name, avatar_url, created_at, updated_at
`

type UpsertUserByIdentityKeyParams struct {
	IdentityKey string
	Email       *string
	Name        *string
	AvatarUrl   *string
}

func (q *Queries) UpsertUserByIdentityKey(ctx context.Context, arg UpsertUserByIdentityKeyParams) (User, error) {
	row := q.db.QueryRow(ctx, upsertUserByIdentityKey,
		arg.IdentityKey,
		arg.Email,
		arg.Name,
		arg.AvatarUrl,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.IdentityKey,
		&i.Email,
		&i.Name,
		&i.AvatarUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
