// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: workspaces.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const createWorkspace = `-- name: CreateWorkspace :one
INSERT INTO workspaces (owner_user_id, name, created_at, updated_at)
VALUES ($1, $2, now(), now()) RETURNING id, owner_user_id, name, created_at, updated_at
`

type CreateWorkspaceParams struct {
	OwnerUserID uuid.UUID
	Name        string
}

func (q *Queries) CreateWorkspace(ctx context.Context, arg CreateWorkspaceParams) (Workspace, error) {
	row := q.db.QueryRow(ctx, createWorkspace, arg.OwnerUserID, arg.Name)
	var i Workspace
	err := row.Scan(
		&i.ID,
		&i.OwnerUserID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteWorkspaceByIDAndOwnerUserID = `-- name: DeleteWorkspaceByIDAndOwnerUserID :execrows
DELETE FROM workspaces
WHERE id = $1 AND owner_user_id = $2
`

type DeleteWorkspaceByIDAndOwnerUserIDParams struct {
	ID          uuid.UUID
	OwnerUserID uuid.UUID
}

func (q *Queries) DeleteWorkspaceByIDAndOwnerUserID(ctx context.Context, arg DeleteWorkspaceByIDAndOwnerUserIDParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteWorkspaceByIDAndOwnerUserID, arg.ID, arg.OwnerUserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getWorkspaceByIDAndOwnerUserID = `-- name: GetWorkspaceByIDAndOwnerUserID :one
SELECT id, owner_user_id, name, created_at, updated_at
FROM workspaces
WHERE id = $1 AND owner_user_id = $2
`

type GetWorkspaceByIDAndOwnerUserIDParams struct {
	ID          uuid.UUID
	OwnerUserID uuid.UUID
}

func (q *Queries) GetWorkspaceByIDAndOwnerUserID(ctx context.Context, arg GetWorkspaceByIDAndOwnerUserIDParams) (Workspace, error) {
	row := q.db.QueryRow(ctx, getWorkspaceByIDAndOwnerUserID, arg.ID, arg.OwnerUserID)
	var i Workspace
	err := row.Scan(
		&i.ID,
		&i.OwnerUserID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listWorkspacesByOwnerUserID = `-- name: ListWorkspacesByOwnerUserID :many
SELECT id, owner_user_id, name, created_at, updated_at
FROM workspaces
WHERE owner_user_id = $1
ORDER BY created_at ASC, id ASC
`

func (q *Queries) ListWorkspacesByOwnerUserID(ctx context.Context, ownerUserID uuid.UUID) ([]Workspace, error) {
	rows, err := q.db.Query(ctx, listWorkspacesByOwnerUserID, ownerUserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Workspace
	for rows.Next() {
		var i Workspace
		if err := rows.Scan(
			&i.ID,
			&i.OwnerUserID,
			&i.Name,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateWorkspaceByIDAndOwnerUserID = `-- name: UpdateWorkspaceByIDAndOwnerUserID :one
UPDATE workspaces
SET name = $3, updated_at = now()
WHERE id = $1 AND owner_user_id = $2
RETURNING id, owner_user_id, name, created_at, updated_at
`

type UpdateWorkspaceByIDAndOwnerUserIDParams struct {
	ID          uuid.UUID
	OwnerUserID uuid.UUID
	Name        string
}

func (q *Queries) UpdateWorkspaceByIDAndOwnerUserID(ctx context.Context, arg UpdateWorkspaceByIDAndOwnerUserIDParams) (Workspace, error) {
	row := q.db.QueryRow(ctx, updateWorkspaceByIDAndOwnerUserID, arg.ID, arg.OwnerUserID, arg.Name)
	var i Workspace
	err := row.Scan(
		&i.ID,
		&i.OwnerUserID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
