// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: workloads.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const createWorkload = `-- name: CreateWorkload :one
INSERT INTO workloads (project_id, name, slug, subdomain, image_ref, primary_region, runtime_port, status, is_public, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, 'queued', $8, now(), now())
RETURNING id, project_id, name, slug, subdomain, image_ref, target_replicas, primary_region, runtime_port, is_public, status, created_at, updated_at
`

type CreateWorkloadParams struct {
	ProjectID     uuid.UUID
	Name          string
	Slug          string
	Subdomain     string
	ImageRef      string
	PrimaryRegion string
	RuntimePort   int32
	IsPublic      bool
}

func (q *Queries) CreateWorkload(ctx context.Context, arg CreateWorkloadParams) (Workload, error) {
	row := q.db.QueryRow(ctx, createWorkload,
		arg.ProjectID,
		arg.Name,
		arg.Slug,
		arg.Subdomain,
		arg.ImageRef,
		arg.PrimaryRegion,
		arg.RuntimePort,
		arg.IsPublic,
	)
	var i Workload
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Name,
		&i.Slug,
		&i.Subdomain,
		&i.ImageRef,
		&i.TargetReplicas,
		&i.PrimaryRegion,
		&i.RuntimePort,
		&i.IsPublic,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

type CreateWorkloadEnvVarsParams struct {
	WorkloadID     uuid.UUID
	Key            string
	ValueEncrypted string
	IsSecret       bool
}

const getRegistryCredentialByIDAndProjectID = `-- name: GetRegistryCredentialByIDAndProjectID :one
SELECT id, project_id, name, registry_url, username, token_encrypted, created_at, updated_at, last_used
FROM registry_credentials
WHERE id = $1
  AND project_id = $2
`

type GetRegistryCredentialByIDAndProjectIDParams struct {
	ID        uuid.UUID
	ProjectID uuid.UUID
}

func (q *Queries) GetRegistryCredentialByIDAndProjectID(ctx context.Context, arg GetRegistryCredentialByIDAndProjectIDParams) (RegistryCredential, error) {
	row := q.db.QueryRow(ctx, getRegistryCredentialByIDAndProjectID, arg.ID, arg.ProjectID)
	var i RegistryCredential
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Name,
		&i.RegistryUrl,
		&i.Username,
		&i.TokenEncrypted,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastUsed,
	)
	return i, err
}

const getWorkloadByIDAndProjectID = `-- name: GetWorkloadByIDAndProjectID :one
SELECT id, project_id, name, slug, subdomain, image_ref, target_replicas, primary_region, runtime_port, is_public, status, created_at, updated_at
FROM workloads
WHERE id = $1
  AND project_id = $2
`

type GetWorkloadByIDAndProjectIDParams struct {
	ID        uuid.UUID
	ProjectID uuid.UUID
}

func (q *Queries) GetWorkloadByIDAndProjectID(ctx context.Context, arg GetWorkloadByIDAndProjectIDParams) (Workload, error) {
	row := q.db.QueryRow(ctx, getWorkloadByIDAndProjectID, arg.ID, arg.ProjectID)
	var i Workload
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Name,
		&i.Slug,
		&i.Subdomain,
		&i.ImageRef,
		&i.TargetReplicas,
		&i.PrimaryRegion,
		&i.RuntimePort,
		&i.IsPublic,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listWorkloadsByProjectID = `-- name: ListWorkloadsByProjectID :many
SELECT id, project_id, name, slug, subdomain, image_ref, target_replicas, primary_region, runtime_port, is_public, status, created_at, updated_at
FROM workloads
WHERE project_id = $1
ORDER BY created_at ASC, id ASC
`

func (q *Queries) ListWorkloadsByProjectID(ctx context.Context, projectID uuid.UUID) ([]Workload, error) {
	rows, err := q.db.Query(ctx, listWorkloadsByProjectID, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Workload
	for rows.Next() {
		var i Workload
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Name,
			&i.Slug,
			&i.Subdomain,
			&i.ImageRef,
			&i.TargetReplicas,
			&i.PrimaryRegion,
			&i.RuntimePort,
			&i.IsPublic,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markWorkloadDeploying = `-- name: MarkWorkloadDeploying :one
UPDATE workloads
SET status = 'deploying',
    updated_at = now()
WHERE id = $1
RETURNING id, project_id, name, slug, subdomain, image_ref, target_replicas, primary_region, runtime_port, is_public, status, created_at, updated_at
`

func (q *Queries) MarkWorkloadDeploying(ctx context.Context, id uuid.UUID) (Workload, error) {
	row := q.db.QueryRow(ctx, markWorkloadDeploying, id)
	var i Workload
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Name,
		&i.Slug,
		&i.Subdomain,
		&i.ImageRef,
		&i.TargetReplicas,
		&i.PrimaryRegion,
		&i.RuntimePort,
		&i.IsPublic,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const markWorkloadFailed = `-- name: MarkWorkloadFailed :one
UPDATE workloads
SET status = 'failed',
    updated_at = now()
WHERE id = $1
RETURNING id, project_id, name, slug, subdomain, image_ref, target_replicas, primary_region, runtime_port, is_public, status, created_at, updated_at
`

func (q *Queries) MarkWorkloadFailed(ctx context.Context, id uuid.UUID) (Workload, error) {
	row := q.db.QueryRow(ctx, markWorkloadFailed, id)
	var i Workload
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Name,
		&i.Slug,
		&i.Subdomain,
		&i.ImageRef,
		&i.TargetReplicas,
		&i.PrimaryRegion,
		&i.RuntimePort,
		&i.IsPublic,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const markWorkloadRunning = `-- name: MarkWorkloadRunning :one
UPDATE workloads
SET status = 'running',
    updated_at = now()
WHERE id = $1
RETURNING id, project_id, name, slug, subdomain, image_ref, target_replicas, primary_region, runtime_port, is_public, status, created_at, updated_at
`

func (q *Queries) MarkWorkloadRunning(ctx context.Context, id uuid.UUID) (Workload, error) {
	row := q.db.QueryRow(ctx, markWorkloadRunning, id)
	var i Workload
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Name,
		&i.Slug,
		&i.Subdomain,
		&i.ImageRef,
		&i.TargetReplicas,
		&i.PrimaryRegion,
		&i.RuntimePort,
		&i.IsPublic,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateWorkloadPrimaryRegion = `-- name: UpdateWorkloadPrimaryRegion :one
UPDATE workloads
SET primary_region = $2,
    updated_at = now()
WHERE id = $1
RETURNING id, project_id, name, slug, subdomain, image_ref, target_replicas, primary_region, runtime_port, is_public, status, created_at, updated_at
`

type UpdateWorkloadPrimaryRegionParams struct {
	ID            uuid.UUID
	PrimaryRegion string
}

func (q *Queries) UpdateWorkloadPrimaryRegion(ctx context.Context, arg UpdateWorkloadPrimaryRegionParams) (Workload, error) {
	row := q.db.QueryRow(ctx, updateWorkloadPrimaryRegion, arg.ID, arg.PrimaryRegion)
	var i Workload
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Name,
		&i.Slug,
		&i.Subdomain,
		&i.ImageRef,
		&i.TargetReplicas,
		&i.PrimaryRegion,
		&i.RuntimePort,
		&i.IsPublic,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertWorkloadRegistryCredential = `-- name: UpsertWorkloadRegistryCredential :exec
INSERT INTO workload_registry_credentials (workload_id, registry_credential_id, created_at, last_used)
VALUES ($1, $2, now(), NULL)
ON CONFLICT (workload_id, registry_credential_id) DO NOTHING
`

type UpsertWorkloadRegistryCredentialParams struct {
	WorkloadID           uuid.UUID
	RegistryCredentialID uuid.UUID
}

func (q *Queries) UpsertWorkloadRegistryCredential(ctx context.Context, arg UpsertWorkloadRegistryCredentialParams) error {
	_, err := q.db.Exec(ctx, upsertWorkloadRegistryCredential, arg.WorkloadID, arg.RegistryCredentialID)
	return err
}
