// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: apps.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const createApp = `-- name: CreateApp :one
INSERT INTO apps (project_id, name, slug, subdomain, image_ref, tier, primary_region, runtime_port, status, is_public, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, 'queued', $9, now(), now())
RETURNING id, project_id, name, slug, subdomain, image_ref, tier, primary_region, runtime_port, is_public, status, created_at, updated_at
`

type CreateAppParams struct {
	ProjectID     uuid.UUID
	Name          string
	Slug          string
	Subdomain     string
	ImageRef      string
	Tier          string
	PrimaryRegion string
	RuntimePort   int32
	IsPublic      bool
}

func (q *Queries) CreateApp(ctx context.Context, arg CreateAppParams) (App, error) {
	row := q.db.QueryRow(ctx, createApp,
		arg.ProjectID,
		arg.Name,
		arg.Slug,
		arg.Subdomain,
		arg.ImageRef,
		arg.Tier,
		arg.PrimaryRegion,
		arg.RuntimePort,
		arg.IsPublic,
	)
	var i App
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Name,
		&i.Slug,
		&i.Subdomain,
		&i.ImageRef,
		&i.Tier,
		&i.PrimaryRegion,
		&i.RuntimePort,
		&i.IsPublic,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

type CreateAppEnvVarsParams struct {
	AppID          uuid.UUID
	Key            string
	ValueEncrypted string
	IsSecret       bool
}

const getRegistryCredentialByIDAndProjectID = `-- name: GetRegistryCredentialByIDAndProjectID :one
SELECT id, project_id, name, registry_url, username, token_encrypted, created_at, updated_at, last_used
FROM registry_credentials
WHERE id = $1
  AND project_id = $2
`

type GetRegistryCredentialByIDAndProjectIDParams struct {
	ID        uuid.UUID
	ProjectID uuid.UUID
}

func (q *Queries) GetRegistryCredentialByIDAndProjectID(ctx context.Context, arg GetRegistryCredentialByIDAndProjectIDParams) (RegistryCredential, error) {
	row := q.db.QueryRow(ctx, getRegistryCredentialByIDAndProjectID, arg.ID, arg.ProjectID)
	var i RegistryCredential
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Name,
		&i.RegistryUrl,
		&i.Username,
		&i.TokenEncrypted,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastUsed,
	)
	return i, err
}

const markAppDeploying = `-- name: MarkAppDeploying :one
UPDATE apps
SET status = 'deploying',
    updated_at = now()
WHERE id = $1
RETURNING id, project_id, name, slug, subdomain, image_ref, tier, primary_region, runtime_port, is_public, status, created_at, updated_at
`

func (q *Queries) MarkAppDeploying(ctx context.Context, id uuid.UUID) (App, error) {
	row := q.db.QueryRow(ctx, markAppDeploying, id)
	var i App
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Name,
		&i.Slug,
		&i.Subdomain,
		&i.ImageRef,
		&i.Tier,
		&i.PrimaryRegion,
		&i.RuntimePort,
		&i.IsPublic,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const markAppFailed = `-- name: MarkAppFailed :one
UPDATE apps
SET status = 'failed',
    updated_at = now()
WHERE id = $1
RETURNING id, project_id, name, slug, subdomain, image_ref, tier, primary_region, runtime_port, is_public, status, created_at, updated_at
`

func (q *Queries) MarkAppFailed(ctx context.Context, id uuid.UUID) (App, error) {
	row := q.db.QueryRow(ctx, markAppFailed, id)
	var i App
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Name,
		&i.Slug,
		&i.Subdomain,
		&i.ImageRef,
		&i.Tier,
		&i.PrimaryRegion,
		&i.RuntimePort,
		&i.IsPublic,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const markAppRunning = `-- name: MarkAppRunning :one
UPDATE apps
SET status = 'running',
    updated_at = now()
WHERE id = $1
RETURNING id, project_id, name, slug, subdomain, image_ref, tier, primary_region, runtime_port, is_public, status, created_at, updated_at
`

func (q *Queries) MarkAppRunning(ctx context.Context, id uuid.UUID) (App, error) {
	row := q.db.QueryRow(ctx, markAppRunning, id)
	var i App
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Name,
		&i.Slug,
		&i.Subdomain,
		&i.ImageRef,
		&i.Tier,
		&i.PrimaryRegion,
		&i.RuntimePort,
		&i.IsPublic,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertAppRegistryCredential = `-- name: UpsertAppRegistryCredential :exec
INSERT INTO app_registry_credentials (app_id, registry_credential_id, created_at, last_used)
VALUES ($1, $2, now(), NULL)
ON CONFLICT (app_id, registry_credential_id) DO NOTHING
`

type UpsertAppRegistryCredentialParams struct {
	AppID                uuid.UUID
	RegistryCredentialID uuid.UUID
}

func (q *Queries) UpsertAppRegistryCredential(ctx context.Context, arg UpsertAppRegistryCredentialParams) error {
	_, err := q.db.Exec(ctx, upsertAppRegistryCredential, arg.AppID, arg.RegistryCredentialID)
	return err
}
