// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: apps.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const createApp = `-- name: CreateApp :one
INSERT INTO apps (project_id, name, slug, subdomain, image_ref, runtime_port, status, is_public, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, 'queued', $7, now(), now())
RETURNING id, project_id, name, slug, subdomain, image_ref, runtime_port, is_public, status, created_at, updated_at
`

type CreateAppParams struct {
	ProjectID   uuid.UUID
	Name        string
	Slug        string
	Subdomain   string
	ImageRef    string
	RuntimePort int32
	IsPublic    bool
}

func (q *Queries) CreateApp(ctx context.Context, arg CreateAppParams) (App, error) {
	row := q.db.QueryRow(ctx, createApp,
		arg.ProjectID,
		arg.Name,
		arg.Slug,
		arg.Subdomain,
		arg.ImageRef,
		arg.RuntimePort,
		arg.IsPublic,
	)
	var i App
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Name,
		&i.Slug,
		&i.Subdomain,
		&i.ImageRef,
		&i.RuntimePort,
		&i.IsPublic,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createAppEnvVar = `-- name: CreateAppEnvVar :exec
INSERT INTO app_env_vars (app_id, key, value_encrypted, is_secret, created_at, updated_at)
VALUES ($1, $2, $3, $4, now(), now())
`

type CreateAppEnvVarParams struct {
	AppID          uuid.UUID
	Key            string
	ValueEncrypted string
	IsSecret       bool
}

func (q *Queries) CreateAppEnvVar(ctx context.Context, arg CreateAppEnvVarParams) error {
	_, err := q.db.Exec(ctx, createAppEnvVar,
		arg.AppID,
		arg.Key,
		arg.ValueEncrypted,
		arg.IsSecret,
	)
	return err
}

const createQueuedDeployment = `-- name: CreateQueuedDeployment :exec
INSERT INTO deployments (app_id, status, image_ref, runtime_port, public_url, created_at, updated_at)
VALUES ($1, 'queued', $2, $3, NULL, now(), now())
`

type CreateQueuedDeploymentParams struct {
	AppID       uuid.UUID
	ImageRef    string
	RuntimePort int32
}

func (q *Queries) CreateQueuedDeployment(ctx context.Context, arg CreateQueuedDeploymentParams) error {
	_, err := q.db.Exec(ctx, createQueuedDeployment, arg.AppID, arg.ImageRef, arg.RuntimePort)
	return err
}

const getRegistryCredentialByIDAndProjectID = `-- name: GetRegistryCredentialByIDAndProjectID :one
SELECT id, project_id, name, registry_url, username, token_encrypted, created_at, updated_at, last_used
FROM registry_credentials
WHERE id = $1
  AND project_id = $2
`

type GetRegistryCredentialByIDAndProjectIDParams struct {
	ID        uuid.UUID
	ProjectID uuid.UUID
}

func (q *Queries) GetRegistryCredentialByIDAndProjectID(ctx context.Context, arg GetRegistryCredentialByIDAndProjectIDParams) (RegistryCredential, error) {
	row := q.db.QueryRow(ctx, getRegistryCredentialByIDAndProjectID, arg.ID, arg.ProjectID)
	var i RegistryCredential
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Name,
		&i.RegistryUrl,
		&i.Username,
		&i.TokenEncrypted,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastUsed,
	)
	return i, err
}

const upsertAppRegistryCredential = `-- name: UpsertAppRegistryCredential :exec
INSERT INTO app_registry_credentials (app_id, registry_credential_id, created_at, last_used)
VALUES ($1, $2, now(), NULL)
ON CONFLICT (app_id, registry_credential_id) DO NOTHING
`

type UpsertAppRegistryCredentialParams struct {
	AppID                uuid.UUID
	RegistryCredentialID uuid.UUID
}

func (q *Queries) UpsertAppRegistryCredential(ctx context.Context, arg UpsertAppRegistryCredentialParams) error {
	_, err := q.db.Exec(ctx, upsertAppRegistryCredential, arg.AppID, arg.RegistryCredentialID)
	return err
}
