// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: copyfrom.go

package sqlc

import (
	"context"
)

// iteratorForCreateAppEnvVars implements pgx.CopyFromSource.
type iteratorForCreateAppEnvVars struct {
	rows                 []CreateAppEnvVarsParams
	skippedFirstNextCall bool
}

func (r *iteratorForCreateAppEnvVars) Next() bool {
	if len(r.rows) == 0 {
		return false
	}
	if !r.skippedFirstNextCall {
		r.skippedFirstNextCall = true
		return true
	}
	r.rows = r.rows[1:]
	return len(r.rows) > 0
}

func (r iteratorForCreateAppEnvVars) Values() ([]interface{}, error) {
	return []interface{}{
		r.rows[0].AppID,
		r.rows[0].Key,
		r.rows[0].ValueEncrypted,
		r.rows[0].IsSecret,
	}, nil
}

func (r iteratorForCreateAppEnvVars) Err() error {
	return nil
}

func (q *Queries) CreateAppEnvVars(ctx context.Context, arg []CreateAppEnvVarsParams) (int64, error) {
	return q.db.CopyFrom(ctx, []string{"app_env_vars"}, []string{"app_id", "key", "value_encrypted", "is_secret"}, &iteratorForCreateAppEnvVars{rows: arg})
}
