// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: deployments.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const createQueuedDeployment = `-- name: CreateQueuedDeployment :one
INSERT INTO deployments (app_id, status, image_ref, runtime_port, public_url, created_at, updated_at)
VALUES ($1, 'queued', $2, $3, NULL, now(), now())
RETURNING id, app_id, status, image_ref, runtime_port, public_url, error_message, created_at, updated_at
`

type CreateQueuedDeploymentParams struct {
	AppID       uuid.UUID
	ImageRef    string
	RuntimePort int32
}

func (q *Queries) CreateQueuedDeployment(ctx context.Context, arg CreateQueuedDeploymentParams) (Deployment, error) {
	row := q.db.QueryRow(ctx, createQueuedDeployment, arg.AppID, arg.ImageRef, arg.RuntimePort)
	var i Deployment
	err := row.Scan(
		&i.ID,
		&i.AppID,
		&i.Status,
		&i.ImageRef,
		&i.RuntimePort,
		&i.PublicUrl,
		&i.ErrorMessage,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const markDeploymentDeploying = `-- name: MarkDeploymentDeploying :one
UPDATE deployments
SET status = 'deploying',
    error_message = NULL,
    updated_at = now()
WHERE id = $1
RETURNING id, app_id, status, image_ref, runtime_port, public_url, error_message, created_at, updated_at
`

func (q *Queries) MarkDeploymentDeploying(ctx context.Context, id uuid.UUID) (Deployment, error) {
	row := q.db.QueryRow(ctx, markDeploymentDeploying, id)
	var i Deployment
	err := row.Scan(
		&i.ID,
		&i.AppID,
		&i.Status,
		&i.ImageRef,
		&i.RuntimePort,
		&i.PublicUrl,
		&i.ErrorMessage,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const markDeploymentFailed = `-- name: MarkDeploymentFailed :one
UPDATE deployments
SET status = 'failed',
    error_message = $2,
    updated_at = now()
WHERE id = $1
RETURNING id, app_id, status, image_ref, runtime_port, public_url, error_message, created_at, updated_at
`

type MarkDeploymentFailedParams struct {
	ID           uuid.UUID
	ErrorMessage *string
}

func (q *Queries) MarkDeploymentFailed(ctx context.Context, arg MarkDeploymentFailedParams) (Deployment, error) {
	row := q.db.QueryRow(ctx, markDeploymentFailed, arg.ID, arg.ErrorMessage)
	var i Deployment
	err := row.Scan(
		&i.ID,
		&i.AppID,
		&i.Status,
		&i.ImageRef,
		&i.RuntimePort,
		&i.PublicUrl,
		&i.ErrorMessage,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const markDeploymentRunning = `-- name: MarkDeploymentRunning :one
UPDATE deployments
SET status = 'running',
    error_message = NULL,
    updated_at = now()
WHERE id = $1
RETURNING id, app_id, status, image_ref, runtime_port, public_url, error_message, created_at, updated_at
`

func (q *Queries) MarkDeploymentRunning(ctx context.Context, id uuid.UUID) (Deployment, error) {
	row := q.db.QueryRow(ctx, markDeploymentRunning, id)
	var i Deployment
	err := row.Scan(
		&i.ID,
		&i.AppID,
		&i.Status,
		&i.ImageRef,
		&i.RuntimePort,
		&i.PublicUrl,
		&i.ErrorMessage,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
