// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: machines.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const assignMachineToNode = `-- name: AssignMachineToNode :one
UPDATE machines
SET node_id = $2,
    status = 'assigned',
    updated_at = now()
WHERE id = $1
RETURNING id, app_id, deployment_id, node_id, region, tier, status, error_message, created_at, updated_at
`

type AssignMachineToNodeParams struct {
	ID     uuid.UUID
	NodeID *string
}

func (q *Queries) AssignMachineToNode(ctx context.Context, arg AssignMachineToNodeParams) (Machine, error) {
	row := q.db.QueryRow(ctx, assignMachineToNode, arg.ID, arg.NodeID)
	var i Machine
	err := row.Scan(
		&i.ID,
		&i.AppID,
		&i.DeploymentID,
		&i.NodeID,
		&i.Region,
		&i.Tier,
		&i.Status,
		&i.ErrorMessage,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createQueuedMachine = `-- name: CreateQueuedMachine :one
INSERT INTO machines (
    app_id,
    deployment_id,
    region,
    tier,
    created_at,
    updated_at
)
VALUES (
    $1,
    $2,
    $3,
    $4,
    now(),
    now()
)
RETURNING id, app_id, deployment_id, node_id, region, tier, status, error_message, created_at, updated_at
`

type CreateQueuedMachineParams struct {
	AppID        uuid.UUID
	DeploymentID uuid.UUID
	Region       string
	Tier         string
}

func (q *Queries) CreateQueuedMachine(ctx context.Context, arg CreateQueuedMachineParams) (Machine, error) {
	row := q.db.QueryRow(ctx, createQueuedMachine,
		arg.AppID,
		arg.DeploymentID,
		arg.Region,
		arg.Tier,
	)
	var i Machine
	err := row.Scan(
		&i.ID,
		&i.AppID,
		&i.DeploymentID,
		&i.NodeID,
		&i.Region,
		&i.Tier,
		&i.Status,
		&i.ErrorMessage,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getMachineByID = `-- name: GetMachineByID :one
SELECT id, app_id, deployment_id, node_id, region, tier, status, error_message, created_at, updated_at
FROM machines
WHERE id = $1
`

func (q *Queries) GetMachineByID(ctx context.Context, id uuid.UUID) (Machine, error) {
	row := q.db.QueryRow(ctx, getMachineByID, id)
	var i Machine
	err := row.Scan(
		&i.ID,
		&i.AppID,
		&i.DeploymentID,
		&i.NodeID,
		&i.Region,
		&i.Tier,
		&i.Status,
		&i.ErrorMessage,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listMachinesByAppID = `-- name: ListMachinesByAppID :many
SELECT id, app_id, deployment_id, node_id, region, tier, status, error_message, created_at, updated_at
FROM machines
WHERE app_id = $1
ORDER BY created_at ASC, id ASC
`

func (q *Queries) ListMachinesByAppID(ctx context.Context, appID uuid.UUID) ([]Machine, error) {
	rows, err := q.db.Query(ctx, listMachinesByAppID, appID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Machine
	for rows.Next() {
		var i Machine
		if err := rows.Scan(
			&i.ID,
			&i.AppID,
			&i.DeploymentID,
			&i.NodeID,
			&i.Region,
			&i.Tier,
			&i.Status,
			&i.ErrorMessage,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markMachineFailed = `-- name: MarkMachineFailed :one
UPDATE machines
SET status = 'failed',
    error_message = $2,
    updated_at = now()
WHERE id = $1
RETURNING id, app_id, deployment_id, node_id, region, tier, status, error_message, created_at, updated_at
`

type MarkMachineFailedParams struct {
	ID           uuid.UUID
	ErrorMessage *string
}

func (q *Queries) MarkMachineFailed(ctx context.Context, arg MarkMachineFailedParams) (Machine, error) {
	row := q.db.QueryRow(ctx, markMachineFailed, arg.ID, arg.ErrorMessage)
	var i Machine
	err := row.Scan(
		&i.ID,
		&i.AppID,
		&i.DeploymentID,
		&i.NodeID,
		&i.Region,
		&i.Tier,
		&i.Status,
		&i.ErrorMessage,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const markMachineRunning = `-- name: MarkMachineRunning :one
UPDATE machines
SET status = 'running',
    error_message = NULL,
    updated_at = now()
WHERE id = $1
RETURNING id, app_id, deployment_id, node_id, region, tier, status, error_message, created_at, updated_at
`

func (q *Queries) MarkMachineRunning(ctx context.Context, id uuid.UUID) (Machine, error) {
	row := q.db.QueryRow(ctx, markMachineRunning, id)
	var i Machine
	err := row.Scan(
		&i.ID,
		&i.AppID,
		&i.DeploymentID,
		&i.NodeID,
		&i.Region,
		&i.Tier,
		&i.Status,
		&i.ErrorMessage,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const markMachineStarting = `-- name: MarkMachineStarting :one
UPDATE machines
SET status = 'starting',
    error_message = NULL,
    updated_at = now()
WHERE id = $1
RETURNING id, app_id, deployment_id, node_id, region, tier, status, error_message, created_at, updated_at
`

func (q *Queries) MarkMachineStarting(ctx context.Context, id uuid.UUID) (Machine, error) {
	row := q.db.QueryRow(ctx, markMachineStarting, id)
	var i Machine
	err := row.Scan(
		&i.ID,
		&i.AppID,
		&i.DeploymentID,
		&i.NodeID,
		&i.Region,
		&i.Tier,
		&i.Status,
		&i.ErrorMessage,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
