// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: microvms.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const assignMicroVMToNode = `-- name: AssignMicroVMToNode :one
UPDATE microvms
SET node_id    = $2,
    status     = 'assigned',
    updated_at = NOW()
WHERE id = $1
RETURNING id, workspace_id, resource_type, resource_id, metadata, node_id, region, vcpu, ram_mb, cpu_mode, root_disk_mb, volume_mb, status, error_message, created_at, updated_at
`

type AssignMicroVMToNodeParams struct {
	ID     uuid.UUID
	NodeID *uuid.UUID
}

func (q *Queries) AssignMicroVMToNode(ctx context.Context, arg AssignMicroVMToNodeParams) (Microvm, error) {
	row := q.db.QueryRow(ctx, assignMicroVMToNode, arg.ID, arg.NodeID)
	var i Microvm
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.ResourceType,
		&i.ResourceID,
		&i.Metadata,
		&i.NodeID,
		&i.Region,
		&i.Vcpu,
		&i.RamMb,
		&i.CpuMode,
		&i.RootDiskMb,
		&i.VolumeMb,
		&i.Status,
		&i.ErrorMessage,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createQueuedMicroVM = `-- name: CreateQueuedMicroVM :one
INSERT INTO microvms (workspace_id,
                      resource_type,
                      resource_id,
                      region,
                      vcpu,
                      ram_mb,
                      cpu_mode,
                      root_disk_mb,
                      volume_mb,
                      created_at,
                      updated_at)
VALUES ($1,
        $2,
        $3,
        $4,
        $5,
        $6,
        $7,
        $8,
        $9,
        NOW(),
        NOW())
RETURNING id, workspace_id, resource_type, resource_id, metadata, node_id, region, vcpu, ram_mb, cpu_mode, root_disk_mb, volume_mb, status, error_message, created_at, updated_at
`

type CreateQueuedMicroVMParams struct {
	WorkspaceID  uuid.UUID
	ResourceType string
	ResourceID   *uuid.UUID
	Region       string
	Vcpu         int32
	RamMb        int64
	CpuMode      string
	RootDiskMb   int64
	VolumeMb     int64
}

func (q *Queries) CreateQueuedMicroVM(ctx context.Context, arg CreateQueuedMicroVMParams) (Microvm, error) {
	row := q.db.QueryRow(ctx, createQueuedMicroVM,
		arg.WorkspaceID,
		arg.ResourceType,
		arg.ResourceID,
		arg.Region,
		arg.Vcpu,
		arg.RamMb,
		arg.CpuMode,
		arg.RootDiskMb,
		arg.VolumeMb,
	)
	var i Microvm
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.ResourceType,
		&i.ResourceID,
		&i.Metadata,
		&i.NodeID,
		&i.Region,
		&i.Vcpu,
		&i.RamMb,
		&i.CpuMode,
		&i.RootDiskMb,
		&i.VolumeMb,
		&i.Status,
		&i.ErrorMessage,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getMicroVMByID = `-- name: GetMicroVMByID :one
SELECT id, workspace_id, resource_type, resource_id, metadata, node_id, region, vcpu, ram_mb, cpu_mode, root_disk_mb, volume_mb, status, error_message, created_at, updated_at
FROM microvms
WHERE id = $1
`

func (q *Queries) GetMicroVMByID(ctx context.Context, id uuid.UUID) (Microvm, error) {
	row := q.db.QueryRow(ctx, getMicroVMByID, id)
	var i Microvm
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.ResourceType,
		&i.ResourceID,
		&i.Metadata,
		&i.NodeID,
		&i.Region,
		&i.Vcpu,
		&i.RamMb,
		&i.CpuMode,
		&i.RootDiskMb,
		&i.VolumeMb,
		&i.Status,
		&i.ErrorMessage,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listMicroVMsByResource = `-- name: ListMicroVMsByResource :many
SELECT id, workspace_id, resource_type, resource_id, metadata, node_id, region, vcpu, ram_mb, cpu_mode, root_disk_mb, volume_mb, status, error_message, created_at, updated_at
FROM microvms
WHERE resource_type = $1
  AND resource_id = $2
ORDER BY created_at ASC, id ASC
`

type ListMicroVMsByResourceParams struct {
	ResourceType string
	ResourceID   *uuid.UUID
}

func (q *Queries) ListMicroVMsByResource(ctx context.Context, arg ListMicroVMsByResourceParams) ([]Microvm, error) {
	rows, err := q.db.Query(ctx, listMicroVMsByResource, arg.ResourceType, arg.ResourceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Microvm
	for rows.Next() {
		var i Microvm
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.ResourceType,
			&i.ResourceID,
			&i.Metadata,
			&i.NodeID,
			&i.Region,
			&i.Vcpu,
			&i.RamMb,
			&i.CpuMode,
			&i.RootDiskMb,
			&i.VolumeMb,
			&i.Status,
			&i.ErrorMessage,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markMicroVMFailed = `-- name: MarkMicroVMFailed :one
UPDATE microvms
SET status        = 'failed',
    error_message = $2,
    updated_at    = NOW()
WHERE id = $1
RETURNING id, workspace_id, resource_type, resource_id, metadata, node_id, region, vcpu, ram_mb, cpu_mode, root_disk_mb, volume_mb, status, error_message, created_at, updated_at
`

type MarkMicroVMFailedParams struct {
	ID           uuid.UUID
	ErrorMessage *string
}

func (q *Queries) MarkMicroVMFailed(ctx context.Context, arg MarkMicroVMFailedParams) (Microvm, error) {
	row := q.db.QueryRow(ctx, markMicroVMFailed, arg.ID, arg.ErrorMessage)
	var i Microvm
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.ResourceType,
		&i.ResourceID,
		&i.Metadata,
		&i.NodeID,
		&i.Region,
		&i.Vcpu,
		&i.RamMb,
		&i.CpuMode,
		&i.RootDiskMb,
		&i.VolumeMb,
		&i.Status,
		&i.ErrorMessage,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const markMicroVMRunning = `-- name: MarkMicroVMRunning :one
UPDATE microvms
SET status        = 'running',
    error_message = NULL,
    updated_at    = NOW()
WHERE id = $1
RETURNING id, workspace_id, resource_type, resource_id, metadata, node_id, region, vcpu, ram_mb, cpu_mode, root_disk_mb, volume_mb, status, error_message, created_at, updated_at
`

func (q *Queries) MarkMicroVMRunning(ctx context.Context, id uuid.UUID) (Microvm, error) {
	row := q.db.QueryRow(ctx, markMicroVMRunning, id)
	var i Microvm
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.ResourceType,
		&i.ResourceID,
		&i.Metadata,
		&i.NodeID,
		&i.Region,
		&i.Vcpu,
		&i.RamMb,
		&i.CpuMode,
		&i.RootDiskMb,
		&i.VolumeMb,
		&i.Status,
		&i.ErrorMessage,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const markMicroVMStarting = `-- name: MarkMicroVMStarting :one
UPDATE microvms
SET status        = 'starting',
    error_message = NULL,
    updated_at    = NOW()
WHERE id = $1
RETURNING id, workspace_id, resource_type, resource_id, metadata, node_id, region, vcpu, ram_mb, cpu_mode, root_disk_mb, volume_mb, status, error_message, created_at, updated_at
`

func (q *Queries) MarkMicroVMStarting(ctx context.Context, id uuid.UUID) (Microvm, error) {
	row := q.db.QueryRow(ctx, markMicroVMStarting, id)
	var i Microvm
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.ResourceType,
		&i.ResourceID,
		&i.Metadata,
		&i.NodeID,
		&i.Region,
		&i.Vcpu,
		&i.RamMb,
		&i.CpuMode,
		&i.RootDiskMb,
		&i.VolumeMb,
		&i.Status,
		&i.ErrorMessage,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
