// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type App struct {
	ID            uuid.UUID
	ProjectID     uuid.UUID
	Name          string
	Slug          string
	Subdomain     string
	ImageRef      string
	Tier          string
	PrimaryRegion string
	RuntimePort   int32
	IsPublic      bool
	Status        string
	CreatedAt     time.Time
	UpdatedAt     time.Time
}

type AppEnvVar struct {
	ID             uuid.UUID
	AppID          uuid.UUID
	Key            string
	ValueEncrypted string
	CipherVersion  *string
	CipherAlgo     *string
	CipherKeyID    *string
	IsSecret       bool
	CreatedAt      time.Time
	UpdatedAt      time.Time
}

type AppRegistryCredential struct {
	AppID                uuid.UUID
	RegistryCredentialID uuid.UUID
	CreatedAt            time.Time
	LastUsed             *time.Time
}

type Deployment struct {
	ID           uuid.UUID
	AppID        uuid.UUID
	Status       string
	ImageRef     string
	RuntimePort  int32
	PublicUrl    *string
	ErrorMessage *string
	CreatedAt    time.Time
	UpdatedAt    time.Time
}

type Machine struct {
	ID           uuid.UUID
	AppID        uuid.UUID
	DeploymentID uuid.UUID
	NodeID       *string
	Region       string
	Tier         string
	Status       string
	ErrorMessage *string
	CreatedAt    time.Time
	UpdatedAt    time.Time
}

type Metal struct {
	ID                 uuid.UUID
	ProviderID         string
	ProviderServerID   string
	PrimaryIpv4        string
	PrimaryIpv6        *string
	HostOsFamily       *string
	HostOsVersion      *string
	HostImageRef       *string
	Region             string
	ProviderLocation   string
	TierTarget         string
	TotalCpuCore       int32
	TotalThreads       int32
	TotalRamMb         int64
	TotalDiskMb        int64
	Status             string
	BootstrapTokenHash *string
	CreatedAt          time.Time
	UpdatedAt          time.Time
}

type NameWord struct {
	ID        uuid.UUID
	Word      string
	Kind      string
	Enabled   bool
	CreatedAt time.Time
	UpdatedAt time.Time
}

type Project struct {
	ID          uuid.UUID
	WorkspaceID uuid.UUID
	Name        string
	Slug        string
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

type Provider struct {
	ID                string
	Name              string
	ApiTokenEncrypted string
	IsActive          pgtype.Bool
	CreatedAt         time.Time
	UpdatedAt         time.Time
}

type RegistryCredential struct {
	ID             uuid.UUID
	ProjectID      uuid.UUID
	Name           string
	RegistryUrl    string
	Username       string
	TokenEncrypted string
	CreatedAt      time.Time
	UpdatedAt      time.Time
	LastUsed       *time.Time
}

type Scaled struct {
	ID        string
	Version   string
	MetalID   uuid.UUID
	CreatedAt time.Time
	UpdatedAt time.Time
}

type SystemsConfig struct {
	Key         string
	Value       string
	IsSecret    bool
	Description *string
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

type User struct {
	ID                  uuid.UUID
	IdentityKey         string
	Email               *string
	Name                *string
	AvatarUrl           *string
	OnboardingCompleted bool
	CreatedAt           time.Time
	UpdatedAt           time.Time
}

type Workspace struct {
	ID          uuid.UUID
	OwnerUserID uuid.UUID
	Name        string
	CreatedAt   time.Time
	UpdatedAt   time.Time
}
