// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: scaled.sql

package sqlc

import (
	"context"
	"time"
)

const markScaledOffline = `-- name: MarkScaledOffline :execrows
UPDATE scaled
SET status = 'offline',
    last_seen_at = $2,
    updated_at = now()
WHERE id = $1
`

type MarkScaledOfflineParams struct {
	ID         string
	LastSeenAt time.Time
}

func (q *Queries) MarkScaledOffline(ctx context.Context, arg MarkScaledOfflineParams) (int64, error) {
	result, err := q.db.Exec(ctx, markScaledOffline, arg.ID, arg.LastSeenAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const markStaleScaledOffline = `-- name: MarkStaleScaledOffline :execrows
UPDATE scaled
SET status = 'offline',
    updated_at = now()
WHERE status <> 'offline'
  AND last_seen_at <= $1
`

func (q *Queries) MarkStaleScaledOffline(ctx context.Context, lastSeenAt time.Time) (int64, error) {
	result, err := q.db.Exec(ctx, markStaleScaledOffline, lastSeenAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateScaledLastSeenAndStatus = `-- name: UpdateScaledLastSeenAndStatus :execrows
UPDATE scaled
SET region = $2,
    status = $3,
    last_seen_at = $4,
    memory_available = $5,
    cpu_usage = $6,
    disk_available = $7,
    updated_at = now()
WHERE id = $1
`

type UpdateScaledLastSeenAndStatusParams struct {
	ID              string
	Region          string
	Status          string
	LastSeenAt      time.Time
	MemoryAvailable int64
	CpuUsage        float64
	DiskAvailable   int64
}

func (q *Queries) UpdateScaledLastSeenAndStatus(ctx context.Context, arg UpdateScaledLastSeenAndStatusParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateScaledLastSeenAndStatus,
		arg.ID,
		arg.Region,
		arg.Status,
		arg.LastSeenAt,
		arg.MemoryAvailable,
		arg.CpuUsage,
		arg.DiskAvailable,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const upsertScaled = `-- name: UpsertScaled :exec
INSERT INTO scaled (id, name, region, status, last_seen_at, memory_available, cpu_usage, disk_available, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, now(), now())
ON CONFLICT (id) DO UPDATE
    SET name = EXCLUDED.name,
        region = EXCLUDED.region,
        status = EXCLUDED.status,
        last_seen_at = EXCLUDED.last_seen_at,
        memory_available = EXCLUDED.memory_available,
        cpu_usage = EXCLUDED.cpu_usage,
        disk_available = EXCLUDED.disk_available,
        updated_at = now()
`

type UpsertScaledParams struct {
	ID              string
	Name            string
	Region          string
	Status          string
	LastSeenAt      time.Time
	MemoryAvailable int64
	CpuUsage        float64
	DiskAvailable   int64
}

func (q *Queries) UpsertScaled(ctx context.Context, arg UpsertScaledParams) error {
	_, err := q.db.Exec(ctx, upsertScaled,
		arg.ID,
		arg.Name,
		arg.Region,
		arg.Status,
		arg.LastSeenAt,
		arg.MemoryAvailable,
		arg.CpuUsage,
		arg.DiskAvailable,
	)
	return err
}
