// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: scaled.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const getScaledByID = `-- name: GetScaledByID :one
SELECT id, version, metal_id, created_at, updated_at
FROM scaled
WHERE id = $1
`

func (q *Queries) GetScaledByID(ctx context.Context, id string) (Scaled, error) {
	row := q.db.QueryRow(ctx, getScaledByID, id)
	var i Scaled
	err := row.Scan(
		&i.ID,
		&i.Version,
		&i.MetalID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getScaledByMetalID = `-- name: GetScaledByMetalID :one
SELECT id, version, metal_id, created_at, updated_at
FROM scaled
WHERE metal_id = $1
`

func (q *Queries) GetScaledByMetalID(ctx context.Context, metalID uuid.UUID) (Scaled, error) {
	row := q.db.QueryRow(ctx, getScaledByMetalID, metalID)
	var i Scaled
	err := row.Scan(
		&i.ID,
		&i.Version,
		&i.MetalID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertScaledBootstrap = `-- name: UpsertScaledBootstrap :one
INSERT INTO scaled (
    id,
    version,
    metal_id,
    created_at,
    updated_at
)
VALUES (
           $1,
           $2,
           $3,
           now(),
           now()
       )
ON CONFLICT (metal_id) DO UPDATE
    SET version = EXCLUDED.version,
        updated_at = now()
RETURNING id, version, metal_id, created_at, updated_at
`

type UpsertScaledBootstrapParams struct {
	ID      string
	Version string
	MetalID uuid.UUID
}

func (q *Queries) UpsertScaledBootstrap(ctx context.Context, arg UpsertScaledBootstrapParams) (Scaled, error) {
	row := q.db.QueryRow(ctx, upsertScaledBootstrap, arg.ID, arg.Version, arg.MetalID)
	var i Scaled
	err := row.Scan(
		&i.ID,
		&i.Version,
		&i.MetalID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
