services:
  api:
    build:
      context: ./api
    environment:
      DATABASE_URL: postgres://spacescale:spacescale@db:5432/spacescale?sslmode=disable
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped

  db:
    image: postgres:18-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: spacescale
      POSTGRES_PASSWORD: spacescale
      POSTGRES_DB: postgres
      PGDATA: /var/lib/postgresql/18/docker
    volumes:
      - pgdata:/var/lib/postgresql # PG 18+ recommends mounting parent dir for pg_upgrade
      - ./db/init:/docker-entrypoint-initdb.d:ro # run init scripts on first boot
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U spacescale -d postgres"]
      interval: 5s
      timeout: 5s
      retries: 10
    restart: unless-stopped


volumes:
  pgdata:
