services:
  db:
    image: postgres:18-alpine
    environment:
      POSTGRES_USER: spacescale
      POSTGRES_PASSWORD: spacescale
      POSTGRES_DB: postgres
      PGDATA: /var/lib/postgresql/18/docker
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/18/docker
      - ./scalecp/db/init:/docker-entrypoint-initdb.d:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U spacescale -d postgres"]
      interval: 5s
      timeout: 5s
      retries: 20

  nats:
    image: nats:2.14-alpine
    command: [ "-js", "-m", "8222", "-sd", "/data" ]
    ports:
      - "4222:4222"
      - "8222:8222"

volumes:
  pgdata:
  natsdata:
