// Package system provides the hardware discovery and pre-flight telemetry for
// the edge node.
//
// This package is the source of truth for the local capacity ledger. It
// interfaces directly with the Linux kernel via procfs and syscalls to determine
// the physical boundaries of the node before it joins the regional auction fabric.
//
// The discovery process is designed to be deterministic. We prioritize raw
// physical hardware metrics over volatile operating system state to ensure
// that our decentralized auctions are based on the absolute capacity of the
// machine rather than transient kernel memory fluctuations.
package system

import (
	"bufio"
	"fmt"
	"os"
	"path/filepath"
	"strconv"
	"strings"
	"syscall"
)

const (
	// bootIDPath is the kernel-generated unique ID for the current boot lifecycle.
	// We use this as a unique anchor for our NATS subjects to ensure that launch
	// commands from a previous, crashed daemon instance are naturally dropped by
	// the network fabric.
	bootIDPath = "/proc/sys/kernel/random/boot_id"

	// memInfoPath is the primary source for hardware-level RAM telemetry.
	memInfoPath = "/proc/meminfo"

	// rootMountDir is the path used to calculate local block storage availability.
	rootMountDir = "/"

	// cpuTopologyCoreIDGlob is the kernel's glob pattern for discovering the
	// hardware-level core identifiers for every logical CPU thread.
	//
	// We use this pattern to perform a manual audit of the underlying physical
	// core topology. By globbing all CPU entries (cpu0, cpu1, etc.), we can
	// inspect the "core_id" and "physical_package_id" of every thread to identify
	// its true silicon origin. This is the foundation of our "Physical Core Truth"
	// model, ensuring we do not confuse logical SMT threads with physical cores.
	cpuTopologyCoreIDGlob = "/sys/devices/system/cpu/cpu[0-9]*/topology/core_id"
)

// Snapshot represents the physical and logical boundaries of the edge node at
// the moment of boot. It is used to initialize the deterministic Capacity ledger.
//
// We intentionally exclude volatile metrics like MemAvailable from this snapshot.
// The edge node manages its own internal capacity ledger and treats the host
// operating system as a tenant that has already been paid a fixed memory tax.
type Snapshot struct {
	// BootID is a unique identifier generated by the kernel upon every reboot.
	// This acts as the lifetime identifier for the current daemon process.
	BootID string

	// TotalCores is the physical CPU count discovered on the host.
	TotalCores uint32

	// TotalRamMb is the physical RAM installed on the machine in megabytes.
	// This is the raw truth used to calculate the sellable pool.
	TotalRamMb uint64

	// TotalDiskMb is the size of the root block device in megabytes.
	TotalDiskMb uint64

	// AvailableDiskMb is the free space on the root block device.
	AvailableDiskMb uint64
}

type memoryStats struct {
	TotalMb uint64
}

type diskStats struct {
	TotalMb     uint64
	AvailableMb uint64
}

// Read performs a one-time scan of the local hardware and returns a Snapshot.
// This is used during the daemon's bootstrap phase to initialize the
// local Capacity ledger and announce the node's presence to the Control Plane.
func Read() (Snapshot, error) {
	bootID, err := readBootID()
	if err != nil {
		return Snapshot{}, err
	}

	totalCores, err := readPhysicalCoreCount()
	if err != nil {
		return Snapshot{}, err
	}

	memory, err := readMemoryStats()
	if err != nil {
		return Snapshot{}, err
	}

	disk, err := readDiskStats(rootMountDir)
	if err != nil {
		return Snapshot{}, err
	}

	return Snapshot{
		BootID:          bootID,
		TotalCores:      totalCores,
		TotalRamMb:      memory.TotalMb,
		TotalDiskMb:     disk.TotalMb,
		AvailableDiskMb: disk.AvailableMb,
	}, nil
}

// readBootID retrieves the unique kernel boot identifier. This ensures that
// even if a node keeps the same hardware ID across reboots, each lifecycle
// is treated as a fresh start by the network fabric.
func readBootID() (string, error) {
	raw, err := os.ReadFile(bootIDPath)
	if err != nil {
		return "", fmt.Errorf("read boot id: %w", err)
	}

	bootID := strings.TrimSpace(string(raw))
	if bootID == "" {
		return "", fmt.Errorf("read boot id: empty value")
	}

	return bootID, nil
}

// readMemoryStats parses the kernel memory information file to find the
// total physical RAM installed. We focus exclusively on MemTotal to ensure
// that our capacity calculations remain deterministic and are not affected
// by transient OS buffer or cache changes.
func readMemoryStats() (memoryStats, error) {
	file, err := os.Open(memInfoPath)
	if err != nil {
		return memoryStats{}, fmt.Errorf("open %s: %w", memInfoPath, err)
	}
	defer file.Close()

	var stats memoryStats
	var foundTotal bool

	scanner := bufio.NewScanner(file)
	for scanner.Scan() {
		line := strings.TrimSpace(scanner.Text())

		if strings.HasPrefix(line, "MemTotal:") {
			value, err := parseMemInfoKBLine(line, "MemTotal:")
			if err != nil {
				return memoryStats{}, err
			}
			stats.TotalMb = value
			foundTotal = true
			break
		}
	}

	if err := scanner.Err(); err != nil {
		return memoryStats{}, fmt.Errorf("scan %s: %w", memInfoPath, err)
	}
	if !foundTotal {
		return memoryStats{}, fmt.Errorf("scan %s: MemTotal not found", memInfoPath)
	}

	return stats, nil
}

// parseMemInfoKBLine extracts the numeric value from a meminfo field and
// converts it from kilobytes to megabytes for consistency across the platform.
func parseMemInfoKBLine(line string, label string) (uint64, error) {
	fields := strings.Fields(line)
	if len(fields) < 3 {
		return 0, fmt.Errorf("invalid %s line: %q", strings.TrimSuffix(label, ":"), line)
	}
	if fields[0] != label {
		return 0, fmt.Errorf("unexpected meminfo label %q", fields[0])
	}
	if !strings.EqualFold(fields[2], "kB") {
		return 0, fmt.Errorf("unexpected %s unit %q", strings.TrimSuffix(label, ":"), fields[2])
	}

	kb, err := strconv.ParseUint(fields[1], 10, 64)
	if err != nil {
		return 0, fmt.Errorf("parse %s value: %w", strings.TrimSuffix(label, ":"), err)
	}

	return kb / 1024, nil
}

// readDiskStats uses the host filesystem statistics to calculate how much
// block storage is available for the microVM image cache and temporary volumes.
func readDiskStats(path string) (diskStats, error) {
	var stat syscall.Statfs_t
	if err := syscall.Statfs(path, &stat); err != nil {
		return diskStats{}, fmt.Errorf("statfs %q: %w", path, err)
	}

	totalBytes := stat.Blocks * uint64(stat.Bsize)
	availableBytes := stat.Bavail * uint64(stat.Bsize)

	return diskStats{
		TotalMb:     totalBytes / 1024 / 1024,
		AvailableMb: availableBytes / 1024 / 1024,
	}, nil
}

// readPhysicalCoreCount performs a deep audit of the CPU topology to identify
// unique physical silicon cores. This prevents over-counting logical SMT siblings
// and ensures our capacity ledger is based on true physical execution resources.
//
// Example Architecture (4-Core / 8-Thread CPU):
//
//  1. Glob finds 8 logical threads: /sys/devices/system/cpu/cpu[0-7]
//  2. Thread cpu0: Socket 0, Core 0 -> Key "0:0"
//  3. Thread cpu1: Socket 0, Core 0 -> Key "0:0" (DUPLICATE)
//  4. Thread cpu2: Socket 0, Core 1 -> Key "0:1"
//     ...
//     Result: 4 Unique Keys in Map = 4 Physical Cores.
func readPhysicalCoreCount() (uint32, error) {
	// We glob all CPU entries in the sysfs to find every logical thread
	// presented by the kernel's scheduler. This allows us to inspect the
	// hardware-level topology of each thread.
	paths, err := filepath.Glob(cpuTopologyCoreIDGlob)
	if err != nil {
		return 0, fmt.Errorf("glob cpu topology: %w", err)
	}
	if len(paths) == 0 {
		// If no topology is found, we cannot accurately determine physical
		// boundaries, so we fail the pre-flight check for security.
		return 0, fmt.Errorf("glob cpu topology: no cpu topology found (ensure sysfs is mounted)")
	}

	// We use a map to de-duplicate logical threads. By combining the
	// physical_package_id (the hardware socket) and the core_id (the silicon core),
	// we generate a unique "Silicon Coordinate" for every physical core.
	//
	// Even if Hyperthreading (SMT) is enabled, both sibling threads will point
	// to the same coordinate, causing them to collapse into a single map entry.
	cores := make(map[string]struct{}, len(paths))
	for _, corePath := range paths {
		// coreID is the kernel's identifier for a core within a socket.
		coreID, err := readTopologyValue(corePath)
		if err != nil {
			return 0, err
		}

		// We locate the sibling "physical_package_id" file. This identifies
		// which physical CPU socket this thread belongs to.
		packagePath := strings.TrimSuffix(corePath, "core_id") + "physical_package_id"
		packageID, err := readTopologyValue(packagePath)
		if err != nil {
			return 0, err
		}

		// Combined key: "SocketID:CoreID". This creates a globally unique
		// identity for the physical silicon core across all CPU sockets.
		cores[packageID+":"+coreID] = struct{}{}
	}

	// If we found threads but no unique cores, something is fundamentally
	// broken in the host's hardware representation.
	if len(cores) == 0 {
		return 0, fmt.Errorf("read physical core count: no cores found (potential sysfs corruption)")
	}

	return uint32(len(cores)), nil
}

// readTopologyValue extracts a single hardware metric from a sysfs topology file.
//
// These virtual kernel files typically contain a single numeric identifier or
// status string, followed by a newline. This function handles the raw I/O
// and performs necessary whitespace normalization to ensure the value is
// ready for architectural de-duplication.
//
// Example (core_id file):
//
//  1. Path: /sys/devices/system/cpu/cpu0/topology/core_id
//  2. Raw Kernel Output: "0\n"
//  3. Normalized Result: "0"
//
// By normalizing these values, we can safely use them as keys in our global
// core identity map without worrying about trailing newlines or extra spaces
// produced by different kernel versions.
func readTopologyValue(path string) (string, error) {
	// We read the raw file content from the kernel's virtual filesystem.
	raw, err := os.ReadFile(path)
	if err != nil {
		return "", fmt.Errorf("read topology %q: %w", path, err)
	}

	// We trim all whitespace and ensure the value is not empty. Hardware
	// files in sysfs often contain trailing newlines produced by the kernel
	// driver's formatting logic.
	value := strings.TrimSpace(string(raw))
	if value == "" {
		return "", fmt.Errorf("read topology %q: empty value", path)
	}
	return value, nil
}
