// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: contracts/proto/control.proto

package controlv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// HealthRequest carries caller metadata for tracing/correlation.
type HealthRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Caller        string                 `protobuf:"bytes,1,opt,name=caller,proto3" json:"caller,omitempty"`
	RequestId     string                 `protobuf:"bytes,2,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthRequest) Reset() {
	*x = HealthRequest{}
	mi := &file_contracts_proto_control_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthRequest) ProtoMessage() {}

func (x *HealthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_contracts_proto_control_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthRequest.ProtoReflect.Descriptor instead.
func (*HealthRequest) Descriptor() ([]byte, []int) {
	return file_contracts_proto_control_proto_rawDescGZIP(), []int{0}
}

func (x *HealthRequest) GetCaller() string {
	if x != nil {
		return x.Caller
	}
	return ""
}

func (x *HealthRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

// HealthResponse reports current runtime status.
type HealthResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	AgentVersion  string                 `protobuf:"bytes,3,opt,name=agent_version,json=agentVersion,proto3" json:"agent_version,omitempty"`
	StartedUnix   int64                  `protobuf:"varint,4,opt,name=started_unix,json=startedUnix,proto3" json:"started_unix,omitempty"`
	Message       string                 `protobuf:"bytes,5,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthResponse) Reset() {
	*x = HealthResponse{}
	mi := &file_contracts_proto_control_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthResponse) ProtoMessage() {}

func (x *HealthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_contracts_proto_control_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthResponse.ProtoReflect.Descriptor instead.
func (*HealthResponse) Descriptor() ([]byte, []int) {
	return file_contracts_proto_control_proto_rawDescGZIP(), []int{1}
}

func (x *HealthResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *HealthResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *HealthResponse) GetAgentVersion() string {
	if x != nil {
		return x.AgentVersion
	}
	return ""
}

func (x *HealthResponse) GetStartedUnix() int64 {
	if x != nil {
		return x.StartedUnix
	}
	return 0
}

func (x *HealthResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// RegisterRequest carries one-time startup identity hints.
type RegisterRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Caller           string                 `protobuf:"bytes,1,opt,name=caller,proto3" json:"caller,omitempty"`
	RequestId        string                 `protobuf:"bytes,2,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	DesiredAgentName string                 `protobuf:"bytes,3,opt,name=desired_agent_name,json=desiredAgentName,proto3" json:"desired_agent_name,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *RegisterRequest) Reset() {
	*x = RegisterRequest{}
	mi := &file_contracts_proto_control_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterRequest) ProtoMessage() {}

func (x *RegisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_contracts_proto_control_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterRequest.ProtoReflect.Descriptor instead.
func (*RegisterRequest) Descriptor() ([]byte, []int) {
	return file_contracts_proto_control_proto_rawDescGZIP(), []int{2}
}

func (x *RegisterRequest) GetCaller() string {
	if x != nil {
		return x.Caller
	}
	return ""
}

func (x *RegisterRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *RegisterRequest) GetDesiredAgentName() string {
	if x != nil {
		return x.DesiredAgentName
	}
	return ""
}

// RegisterResponse returns accepted identity and capability metadata.
type RegisterResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Accepted      bool                   `protobuf:"varint,1,opt,name=accepted,proto3" json:"accepted,omitempty"`
	AgentId       string                 `protobuf:"bytes,2,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	AgentVersion  string                 `protobuf:"bytes,3,opt,name=agent_version,json=agentVersion,proto3" json:"agent_version,omitempty"`
	Capabilities  []string               `protobuf:"bytes,4,rep,name=capabilities,proto3" json:"capabilities,omitempty"`
	Message       string                 `protobuf:"bytes,5,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterResponse) Reset() {
	*x = RegisterResponse{}
	mi := &file_contracts_proto_control_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterResponse) ProtoMessage() {}

func (x *RegisterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_contracts_proto_control_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterResponse.ProtoReflect.Descriptor instead.
func (*RegisterResponse) Descriptor() ([]byte, []int) {
	return file_contracts_proto_control_proto_rawDescGZIP(), []int{3}
}

func (x *RegisterResponse) GetAccepted() bool {
	if x != nil {
		return x.Accepted
	}
	return false
}

func (x *RegisterResponse) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *RegisterResponse) GetAgentVersion() string {
	if x != nil {
		return x.AgentVersion
	}
	return ""
}

func (x *RegisterResponse) GetCapabilities() []string {
	if x != nil {
		return x.Capabilities
	}
	return nil
}

func (x *RegisterResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_contracts_proto_control_proto protoreflect.FileDescriptor

const file_contracts_proto_control_proto_rawDesc = "" +
	"\n" +
	"\x1dcontracts/proto/control.proto\x12\n" +
	"control.v1\"F\n" +
	"\rHealthRequest\x12\x16\n" +
	"\x06caller\x18\x01 \x01(\tR\x06caller\x12\x1d\n" +
	"\n" +
	"request_id\x18\x02 \x01(\tR\trequestId\"\x9a\x01\n" +
	"\x0eHealthResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12#\n" +
	"\ragent_version\x18\x03 \x01(\tR\fagentVersion\x12!\n" +
	"\fstarted_unix\x18\x04 \x01(\x03R\vstartedUnix\x12\x18\n" +
	"\amessage\x18\x05 \x01(\tR\amessage\"v\n" +
	"\x0fRegisterRequest\x12\x16\n" +
	"\x06caller\x18\x01 \x01(\tR\x06caller\x12\x1d\n" +
	"\n" +
	"request_id\x18\x02 \x01(\tR\trequestId\x12,\n" +
	"\x12desired_agent_name\x18\x03 \x01(\tR\x10desiredAgentName\"\xac\x01\n" +
	"\x10RegisterResponse\x12\x1a\n" +
	"\baccepted\x18\x01 \x01(\bR\baccepted\x12\x19\n" +
	"\bagent_id\x18\x02 \x01(\tR\aagentId\x12#\n" +
	"\ragent_version\x18\x03 \x01(\tR\fagentVersion\x12\"\n" +
	"\fcapabilities\x18\x04 \x03(\tR\fcapabilities\x12\x18\n" +
	"\amessage\x18\x05 \x01(\tR\amessage2\x96\x01\n" +
	"\fAgentControl\x12?\n" +
	"\x06Health\x12\x19.control.v1.HealthRequest\x1a\x1a.control.v1.HealthResponse\x12E\n" +
	"\bRegister\x12\x1b.control.v1.RegisterRequest\x1a\x1c.control.v1.RegisterResponseBDZBgithub.com/t0gun/spacescale/packages/proto-go/control/v1;controlv1b\x06proto3"

var (
	file_contracts_proto_control_proto_rawDescOnce sync.Once
	file_contracts_proto_control_proto_rawDescData []byte
)

func file_contracts_proto_control_proto_rawDescGZIP() []byte {
	file_contracts_proto_control_proto_rawDescOnce.Do(func() {
		file_contracts_proto_control_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_contracts_proto_control_proto_rawDesc), len(file_contracts_proto_control_proto_rawDesc)))
	})
	return file_contracts_proto_control_proto_rawDescData
}

var file_contracts_proto_control_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_contracts_proto_control_proto_goTypes = []any{
	(*HealthRequest)(nil),    // 0: control.v1.HealthRequest
	(*HealthResponse)(nil),   // 1: control.v1.HealthResponse
	(*RegisterRequest)(nil),  // 2: control.v1.RegisterRequest
	(*RegisterResponse)(nil), // 3: control.v1.RegisterResponse
}
var file_contracts_proto_control_proto_depIdxs = []int32{
	0, // 0: control.v1.AgentControl.Health:input_type -> control.v1.HealthRequest
	2, // 1: control.v1.AgentControl.Register:input_type -> control.v1.RegisterRequest
	1, // 2: control.v1.AgentControl.Health:output_type -> control.v1.HealthResponse
	3, // 3: control.v1.AgentControl.Register:output_type -> control.v1.RegisterResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_contracts_proto_control_proto_init() }
func file_contracts_proto_control_proto_init() {
	if File_contracts_proto_control_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_contracts_proto_control_proto_rawDesc), len(file_contracts_proto_control_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_contracts_proto_control_proto_goTypes,
		DependencyIndexes: file_contracts_proto_control_proto_depIdxs,
		MessageInfos:      file_contracts_proto_control_proto_msgTypes,
	}.Build()
	File_contracts_proto_control_proto = out.File
	file_contracts_proto_control_proto_goTypes = nil
	file_contracts_proto_control_proto_depIdxs = nil
}
