// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: contracts/proto/control.proto

package controlv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// NodeDirectiveType enumerates host-level operations.
type NodeDirectiveType int32

const (
	NodeDirectiveType_NODE_DIRECTIVE_TYPE_UNSPECIFIED NodeDirectiveType = 0
	NodeDirectiveType_NODE_DIRECTIVE_TYPE_DRAIN       NodeDirectiveType = 1 // NODE_DIRECTIVE_TYPE_DRAIN stops new workloads and drains running workloads.
	NodeDirectiveType_NODE_DIRECTIVE_TYPE_RESUME      NodeDirectiveType = 2 // NODE_DIRECTIVE_TYPE_RESUME clears draining state and accepts new workloads.
	NodeDirectiveType_NODE_DIRECTIVE_TYPE_REBOOT      NodeDirectiveType = 3 // NODE_DIRECTIVE_TYPE_REBOOT requests a controlled node reboot.
)

// Enum value maps for NodeDirectiveType.
var (
	NodeDirectiveType_name = map[int32]string{
		0: "NODE_DIRECTIVE_TYPE_UNSPECIFIED",
		1: "NODE_DIRECTIVE_TYPE_DRAIN",
		2: "NODE_DIRECTIVE_TYPE_RESUME",
		3: "NODE_DIRECTIVE_TYPE_REBOOT",
	}
	NodeDirectiveType_value = map[string]int32{
		"NODE_DIRECTIVE_TYPE_UNSPECIFIED": 0,
		"NODE_DIRECTIVE_TYPE_DRAIN":       1,
		"NODE_DIRECTIVE_TYPE_RESUME":      2,
		"NODE_DIRECTIVE_TYPE_REBOOT":      3,
	}
)

func (x NodeDirectiveType) Enum() *NodeDirectiveType {
	p := new(NodeDirectiveType)
	*p = x
	return p
}

func (x NodeDirectiveType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (NodeDirectiveType) Descriptor() protoreflect.EnumDescriptor {
	return file_contracts_proto_control_proto_enumTypes[0].Descriptor()
}

func (NodeDirectiveType) Type() protoreflect.EnumType {
	return &file_contracts_proto_control_proto_enumTypes[0]
}

func (x NodeDirectiveType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use NodeDirectiveType.Descriptor instead.
func (NodeDirectiveType) EnumDescriptor() ([]byte, []int) {
	return file_contracts_proto_control_proto_rawDescGZIP(), []int{0}
}

// AgentDirectiveType enumerates agent process operations.
type AgentDirectiveType int32

const (
	AgentDirectiveType_AGENT_DIRECTIVE_TYPE_UNSPECIFIED AgentDirectiveType = 0
	AgentDirectiveType_AGENT_DIRECTIVE_TYPE_RELOAD      AgentDirectiveType = 1 // AGENT_DIRECTIVE_TYPE_RELOAD requests in-place config/runtime reload.
	AgentDirectiveType_AGENT_DIRECTIVE_TYPE_UPGRADE     AgentDirectiveType = 2 // AGENT_DIRECTIVE_TYPE_UPGRADE requests binary upgrade with verification.
	AgentDirectiveType_AGENT_DIRECTIVE_TYPE_RESTART     AgentDirectiveType = 3 // AGENT_DIRECTIVE_TYPE_RESTART requests controlled process restart.
)

// Enum value maps for AgentDirectiveType.
var (
	AgentDirectiveType_name = map[int32]string{
		0: "AGENT_DIRECTIVE_TYPE_UNSPECIFIED",
		1: "AGENT_DIRECTIVE_TYPE_RELOAD",
		2: "AGENT_DIRECTIVE_TYPE_UPGRADE",
		3: "AGENT_DIRECTIVE_TYPE_RESTART",
	}
	AgentDirectiveType_value = map[string]int32{
		"AGENT_DIRECTIVE_TYPE_UNSPECIFIED": 0,
		"AGENT_DIRECTIVE_TYPE_RELOAD":      1,
		"AGENT_DIRECTIVE_TYPE_UPGRADE":     2,
		"AGENT_DIRECTIVE_TYPE_RESTART":     3,
	}
)

func (x AgentDirectiveType) Enum() *AgentDirectiveType {
	p := new(AgentDirectiveType)
	*p = x
	return p
}

func (x AgentDirectiveType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AgentDirectiveType) Descriptor() protoreflect.EnumDescriptor {
	return file_contracts_proto_control_proto_enumTypes[1].Descriptor()
}

func (AgentDirectiveType) Type() protoreflect.EnumType {
	return &file_contracts_proto_control_proto_enumTypes[1]
}

func (x AgentDirectiveType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AgentDirectiveType.Descriptor instead.
func (AgentDirectiveType) EnumDescriptor() ([]byte, []int) {
	return file_contracts_proto_control_proto_rawDescGZIP(), []int{1}
}

// WorkloadDirectiveType enumerates workload lifecycle operations.
type WorkloadDirectiveType int32

const (
	WorkloadDirectiveType_WORKLOAD_DIRECTIVE_TYPE_UNSPECIFIED WorkloadDirectiveType = 0
	WorkloadDirectiveType_WORKLOAD_DIRECTIVE_TYPE_DEPLOY      WorkloadDirectiveType = 1 // WORKLOAD_DIRECTIVE_TYPE_DEPLOY creates or updates a workload revision.
	WorkloadDirectiveType_WORKLOAD_DIRECTIVE_TYPE_STOP        WorkloadDirectiveType = 2 // WORKLOAD_DIRECTIVE_TYPE_STOP gracefully stops a workload.
	WorkloadDirectiveType_WORKLOAD_DIRECTIVE_TYPE_RESTART     WorkloadDirectiveType = 3 // WORKLOAD_DIRECTIVE_TYPE_RESTART restarts workload processes.
	WorkloadDirectiveType_WORKLOAD_DIRECTIVE_TYPE_SCALE       WorkloadDirectiveType = 4 // WORKLOAD_DIRECTIVE_TYPE_SCALE changes desired workload replicas.
)

// Enum value maps for WorkloadDirectiveType.
var (
	WorkloadDirectiveType_name = map[int32]string{
		0: "WORKLOAD_DIRECTIVE_TYPE_UNSPECIFIED",
		1: "WORKLOAD_DIRECTIVE_TYPE_DEPLOY",
		2: "WORKLOAD_DIRECTIVE_TYPE_STOP",
		3: "WORKLOAD_DIRECTIVE_TYPE_RESTART",
		4: "WORKLOAD_DIRECTIVE_TYPE_SCALE",
	}
	WorkloadDirectiveType_value = map[string]int32{
		"WORKLOAD_DIRECTIVE_TYPE_UNSPECIFIED": 0,
		"WORKLOAD_DIRECTIVE_TYPE_DEPLOY":      1,
		"WORKLOAD_DIRECTIVE_TYPE_STOP":        2,
		"WORKLOAD_DIRECTIVE_TYPE_RESTART":     3,
		"WORKLOAD_DIRECTIVE_TYPE_SCALE":       4,
	}
)

func (x WorkloadDirectiveType) Enum() *WorkloadDirectiveType {
	p := new(WorkloadDirectiveType)
	*p = x
	return p
}

func (x WorkloadDirectiveType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (WorkloadDirectiveType) Descriptor() protoreflect.EnumDescriptor {
	return file_contracts_proto_control_proto_enumTypes[2].Descriptor()
}

func (WorkloadDirectiveType) Type() protoreflect.EnumType {
	return &file_contracts_proto_control_proto_enumTypes[2]
}

func (x WorkloadDirectiveType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use WorkloadDirectiveType.Descriptor instead.
func (WorkloadDirectiveType) EnumDescriptor() ([]byte, []int) {
	return file_contracts_proto_control_proto_rawDescGZIP(), []int{2}
}

// DirectiveResultStatus enumerates final directive execution outcomes.
type DirectiveResultStatus int32

const (
	DirectiveResultStatus_DIRECTIVE_RESULT_STATUS_UNSPECIFIED DirectiveResultStatus = 0
	DirectiveResultStatus_DIRECTIVE_RESULT_STATUS_SUCCEEDED   DirectiveResultStatus = 1
	DirectiveResultStatus_DIRECTIVE_RESULT_STATUS_FAILED      DirectiveResultStatus = 2
	DirectiveResultStatus_DIRECTIVE_RESULT_STATUS_CANCELLED   DirectiveResultStatus = 3
)

// Enum value maps for DirectiveResultStatus.
var (
	DirectiveResultStatus_name = map[int32]string{
		0: "DIRECTIVE_RESULT_STATUS_UNSPECIFIED",
		1: "DIRECTIVE_RESULT_STATUS_SUCCEEDED",
		2: "DIRECTIVE_RESULT_STATUS_FAILED",
		3: "DIRECTIVE_RESULT_STATUS_CANCELLED",
	}
	DirectiveResultStatus_value = map[string]int32{
		"DIRECTIVE_RESULT_STATUS_UNSPECIFIED": 0,
		"DIRECTIVE_RESULT_STATUS_SUCCEEDED":   1,
		"DIRECTIVE_RESULT_STATUS_FAILED":      2,
		"DIRECTIVE_RESULT_STATUS_CANCELLED":   3,
	}
)

func (x DirectiveResultStatus) Enum() *DirectiveResultStatus {
	p := new(DirectiveResultStatus)
	*p = x
	return p
}

func (x DirectiveResultStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DirectiveResultStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_contracts_proto_control_proto_enumTypes[3].Descriptor()
}

func (DirectiveResultStatus) Type() protoreflect.EnumType {
	return &file_contracts_proto_control_proto_enumTypes[3]
}

func (x DirectiveResultStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DirectiveResultStatus.Descriptor instead.
func (DirectiveResultStatus) EnumDescriptor() ([]byte, []int) {
	return file_contracts_proto_control_proto_rawDescGZIP(), []int{3}
}

// WorkloadRuntimeState enumerates per-workload lifecycle states reported by the agent.
type WorkloadRuntimeState int32

const (
	WorkloadRuntimeState_WORKLOAD_RUNTIME_STATE_UNSPECIFIED WorkloadRuntimeState = 0
	WorkloadRuntimeState_WORKLOAD_RUNTIME_STATE_PENDING     WorkloadRuntimeState = 1 // WORKLOAD_RUNTIME_STATE_PENDING means workload resources are not ready yet.
	WorkloadRuntimeState_WORKLOAD_RUNTIME_STATE_STARTING    WorkloadRuntimeState = 2 // WORKLOAD_RUNTIME_STATE_STARTING means workload startup is in progress.
	WorkloadRuntimeState_WORKLOAD_RUNTIME_STATE_RUNNING     WorkloadRuntimeState = 3 // WORKLOAD_RUNTIME_STATE_RUNNING means workload is healthy and serving.
	WorkloadRuntimeState_WORKLOAD_RUNTIME_STATE_DRAINING    WorkloadRuntimeState = 4 // WORKLOAD_RUNTIME_STATE_DRAINING means workload is finishing in-flight work.
	WorkloadRuntimeState_WORKLOAD_RUNTIME_STATE_STOPPED     WorkloadRuntimeState = 5 // WORKLOAD_RUNTIME_STATE_STOPPED means workload is intentionally not running.
	WorkloadRuntimeState_WORKLOAD_RUNTIME_STATE_FAILED      WorkloadRuntimeState = 6 // WORKLOAD_RUNTIME_STATE_FAILED means workload reached terminal failure.
)

// Enum value maps for WorkloadRuntimeState.
var (
	WorkloadRuntimeState_name = map[int32]string{
		0: "WORKLOAD_RUNTIME_STATE_UNSPECIFIED",
		1: "WORKLOAD_RUNTIME_STATE_PENDING",
		2: "WORKLOAD_RUNTIME_STATE_STARTING",
		3: "WORKLOAD_RUNTIME_STATE_RUNNING",
		4: "WORKLOAD_RUNTIME_STATE_DRAINING",
		5: "WORKLOAD_RUNTIME_STATE_STOPPED",
		6: "WORKLOAD_RUNTIME_STATE_FAILED",
	}
	WorkloadRuntimeState_value = map[string]int32{
		"WORKLOAD_RUNTIME_STATE_UNSPECIFIED": 0,
		"WORKLOAD_RUNTIME_STATE_PENDING":     1,
		"WORKLOAD_RUNTIME_STATE_STARTING":    2,
		"WORKLOAD_RUNTIME_STATE_RUNNING":     3,
		"WORKLOAD_RUNTIME_STATE_DRAINING":    4,
		"WORKLOAD_RUNTIME_STATE_STOPPED":     5,
		"WORKLOAD_RUNTIME_STATE_FAILED":      6,
	}
)

func (x WorkloadRuntimeState) Enum() *WorkloadRuntimeState {
	p := new(WorkloadRuntimeState)
	*p = x
	return p
}

func (x WorkloadRuntimeState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (WorkloadRuntimeState) Descriptor() protoreflect.EnumDescriptor {
	return file_contracts_proto_control_proto_enumTypes[4].Descriptor()
}

func (WorkloadRuntimeState) Type() protoreflect.EnumType {
	return &file_contracts_proto_control_proto_enumTypes[4]
}

func (x WorkloadRuntimeState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use WorkloadRuntimeState.Descriptor instead.
func (WorkloadRuntimeState) EnumDescriptor() ([]byte, []int) {
	return file_contracts_proto_control_proto_rawDescGZIP(), []int{4}
}

// HealthRequest carries caller metadata for tracing and correlation.
type HealthRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Caller        string                 `protobuf:"bytes,1,opt,name=caller,proto3" json:"caller,omitempty"`                        // caller identifies who is probing health (for example: "scaled/bootstrap").
	RequestId     string                 `protobuf:"bytes,2,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"` // request_id is an optional correlation id for distributed tracing.
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthRequest) Reset() {
	*x = HealthRequest{}
	mi := &file_contracts_proto_control_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthRequest) ProtoMessage() {}

func (x *HealthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_contracts_proto_control_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthRequest.ProtoReflect.Descriptor instead.
func (*HealthRequest) Descriptor() ([]byte, []int) {
	return file_contracts_proto_control_proto_rawDescGZIP(), []int{0}
}

func (x *HealthRequest) GetCaller() string {
	if x != nil {
		return x.Caller
	}
	return ""
}

func (x *HealthRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

// HealthResponse reports current control-plane status.
type HealthResponse struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	Ok                  bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`                                                               // ok indicates whether the control plane is currently ready.
	Status              string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`                                                        // status is a compact readiness label (for example: "ready", "degraded").
	ControlPlaneVersion string                 `protobuf:"bytes,3,opt,name=control_plane_version,json=controlPlaneVersion,proto3" json:"control_plane_version,omitempty"` // control_plane_version identifies the serving build/version.
	StartedUnix         int64                  `protobuf:"varint,4,opt,name=started_unix,json=startedUnix,proto3" json:"started_unix,omitempty"`                          // started_unix is the control-plane process start time in unix seconds.
	Message             string                 `protobuf:"bytes,5,opt,name=message,proto3" json:"message,omitempty"`                                                      // message provides human-readable details for logs and diagnostics.
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *HealthResponse) Reset() {
	*x = HealthResponse{}
	mi := &file_contracts_proto_control_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthResponse) ProtoMessage() {}

func (x *HealthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_contracts_proto_control_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthResponse.ProtoReflect.Descriptor instead.
func (*HealthResponse) Descriptor() ([]byte, []int) {
	return file_contracts_proto_control_proto_rawDescGZIP(), []int{1}
}

func (x *HealthResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *HealthResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *HealthResponse) GetControlPlaneVersion() string {
	if x != nil {
		return x.ControlPlaneVersion
	}
	return ""
}

func (x *HealthResponse) GetStartedUnix() int64 {
	if x != nil {
		return x.StartedUnix
	}
	return 0
}

func (x *HealthResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// AgentSessionRequest is an envelope for agent-to-control stream events.
// Exactly one event payload should be set per message.
type AgentSessionRequest struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	RequestId string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"` // request_id is optional, may be echoed by responses, and helps stream log correlation.
	// Types that are valid to be assigned to Event:
	//
	//	*AgentSessionRequest_Register
	//	*AgentSessionRequest_Heartbeat
	//	*AgentSessionRequest_CapabilityUpdate
	//	*AgentSessionRequest_DirectiveAck
	//	*AgentSessionRequest_DirectiveProgress
	//	*AgentSessionRequest_DirectiveResult
	//	*AgentSessionRequest_NodeHealth
	//	*AgentSessionRequest_WorkloadsReport
	Event         isAgentSessionRequest_Event `protobuf_oneof:"event"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentSessionRequest) Reset() {
	*x = AgentSessionRequest{}
	mi := &file_contracts_proto_control_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentSessionRequest) ProtoMessage() {}

func (x *AgentSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_contracts_proto_control_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentSessionRequest.ProtoReflect.Descriptor instead.
func (*AgentSessionRequest) Descriptor() ([]byte, []int) {
	return file_contracts_proto_control_proto_rawDescGZIP(), []int{2}
}

func (x *AgentSessionRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *AgentSessionRequest) GetEvent() isAgentSessionRequest_Event {
	if x != nil {
		return x.Event
	}
	return nil
}

func (x *AgentSessionRequest) GetRegister() *RegisterRequest {
	if x != nil {
		if x, ok := x.Event.(*AgentSessionRequest_Register); ok {
			return x.Register
		}
	}
	return nil
}

func (x *AgentSessionRequest) GetHeartbeat() *HeartbeatRequest {
	if x != nil {
		if x, ok := x.Event.(*AgentSessionRequest_Heartbeat); ok {
			return x.Heartbeat
		}
	}
	return nil
}

func (x *AgentSessionRequest) GetCapabilityUpdate() *CapabilityUpdate {
	if x != nil {
		if x, ok := x.Event.(*AgentSessionRequest_CapabilityUpdate); ok {
			return x.CapabilityUpdate
		}
	}
	return nil
}

func (x *AgentSessionRequest) GetDirectiveAck() *DirectiveAck {
	if x != nil {
		if x, ok := x.Event.(*AgentSessionRequest_DirectiveAck); ok {
			return x.DirectiveAck
		}
	}
	return nil
}

func (x *AgentSessionRequest) GetDirectiveProgress() *DirectiveProgress {
	if x != nil {
		if x, ok := x.Event.(*AgentSessionRequest_DirectiveProgress); ok {
			return x.DirectiveProgress
		}
	}
	return nil
}

func (x *AgentSessionRequest) GetDirectiveResult() *DirectiveResult {
	if x != nil {
		if x, ok := x.Event.(*AgentSessionRequest_DirectiveResult); ok {
			return x.DirectiveResult
		}
	}
	return nil
}

func (x *AgentSessionRequest) GetNodeHealth() *NodeHealthReport {
	if x != nil {
		if x, ok := x.Event.(*AgentSessionRequest_NodeHealth); ok {
			return x.NodeHealth
		}
	}
	return nil
}

func (x *AgentSessionRequest) GetWorkloadsReport() *WorkloadsReport {
	if x != nil {
		if x, ok := x.Event.(*AgentSessionRequest_WorkloadsReport); ok {
			return x.WorkloadsReport
		}
	}
	return nil
}

type isAgentSessionRequest_Event interface {
	isAgentSessionRequest_Event()
}

type AgentSessionRequest_Register struct {
	Register *RegisterRequest `protobuf:"bytes,2,opt,name=register,proto3,oneof"` // register starts a new logical control session.
}

type AgentSessionRequest_Heartbeat struct {
	Heartbeat *HeartbeatRequest `protobuf:"bytes,3,opt,name=heartbeat,proto3,oneof"` // heartbeat updates liveness and runtime load signals.
}

type AgentSessionRequest_CapabilityUpdate struct {
	CapabilityUpdate *CapabilityUpdate `protobuf:"bytes,4,opt,name=capability_update,json=capabilityUpdate,proto3,oneof"` // capability_update reports runtime changes to supported features.
}

type AgentSessionRequest_DirectiveAck struct {
	DirectiveAck *DirectiveAck `protobuf:"bytes,5,opt,name=directive_ack,json=directiveAck,proto3,oneof"` // directive_ack reports immediate accept/reject for a directive.
}

type AgentSessionRequest_DirectiveProgress struct {
	DirectiveProgress *DirectiveProgress `protobuf:"bytes,6,opt,name=directive_progress,json=directiveProgress,proto3,oneof"` // directive_progress reports in-flight execution state.
}

type AgentSessionRequest_DirectiveResult struct {
	DirectiveResult *DirectiveResult `protobuf:"bytes,7,opt,name=directive_result,json=directiveResult,proto3,oneof"` // directive_result reports final directive completion status.
}

type AgentSessionRequest_NodeHealth struct {
	NodeHealth *NodeHealthReport `protobuf:"bytes,8,opt,name=node_health,json=nodeHealth,proto3,oneof"` // node_health reports machine-level resource and health telemetry.
}

type AgentSessionRequest_WorkloadsReport struct {
	WorkloadsReport *WorkloadsReport `protobuf:"bytes,9,opt,name=workloads_report,json=workloadsReport,proto3,oneof"` // workloads_report reports per-workload runtime telemetry for scheduling and operations.
}

func (*AgentSessionRequest_Register) isAgentSessionRequest_Event() {}

func (*AgentSessionRequest_Heartbeat) isAgentSessionRequest_Event() {}

func (*AgentSessionRequest_CapabilityUpdate) isAgentSessionRequest_Event() {}

func (*AgentSessionRequest_DirectiveAck) isAgentSessionRequest_Event() {}

func (*AgentSessionRequest_DirectiveProgress) isAgentSessionRequest_Event() {}

func (*AgentSessionRequest_DirectiveResult) isAgentSessionRequest_Event() {}

func (*AgentSessionRequest_NodeHealth) isAgentSessionRequest_Event() {}

func (*AgentSessionRequest_WorkloadsReport) isAgentSessionRequest_Event() {}

// AgentSessionResponse is an envelope for control-to-agent stream events.
// Exactly one event payload should be set per message.
type AgentSessionResponse struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	RequestId string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"` // request_id echoes the originating AgentSessionRequest.request_id when present.
	// Types that are valid to be assigned to Event:
	//
	//	*AgentSessionResponse_Register
	//	*AgentSessionResponse_Heartbeat
	//	*AgentSessionResponse_Directive
	Event         isAgentSessionResponse_Event `protobuf_oneof:"event"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentSessionResponse) Reset() {
	*x = AgentSessionResponse{}
	mi := &file_contracts_proto_control_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentSessionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentSessionResponse) ProtoMessage() {}

func (x *AgentSessionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_contracts_proto_control_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentSessionResponse.ProtoReflect.Descriptor instead.
func (*AgentSessionResponse) Descriptor() ([]byte, []int) {
	return file_contracts_proto_control_proto_rawDescGZIP(), []int{3}
}

func (x *AgentSessionResponse) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *AgentSessionResponse) GetEvent() isAgentSessionResponse_Event {
	if x != nil {
		return x.Event
	}
	return nil
}

func (x *AgentSessionResponse) GetRegister() *RegisterResponse {
	if x != nil {
		if x, ok := x.Event.(*AgentSessionResponse_Register); ok {
			return x.Register
		}
	}
	return nil
}

func (x *AgentSessionResponse) GetHeartbeat() *HeartbeatResponse {
	if x != nil {
		if x, ok := x.Event.(*AgentSessionResponse_Heartbeat); ok {
			return x.Heartbeat
		}
	}
	return nil
}

func (x *AgentSessionResponse) GetDirective() *ControlDirective {
	if x != nil {
		if x, ok := x.Event.(*AgentSessionResponse_Directive); ok {
			return x.Directive
		}
	}
	return nil
}

type isAgentSessionResponse_Event interface {
	isAgentSessionResponse_Event()
}

type AgentSessionResponse_Register struct {
	Register *RegisterResponse `protobuf:"bytes,2,opt,name=register,proto3,oneof"` // register returns accepted identity and heartbeat lease settings.
}

type AgentSessionResponse_Heartbeat struct {
	Heartbeat *HeartbeatResponse `protobuf:"bytes,3,opt,name=heartbeat,proto3,oneof"` // heartbeat acknowledges liveness updates from the agent.
}

type AgentSessionResponse_Directive struct {
	Directive *ControlDirective `protobuf:"bytes,4,opt,name=directive,proto3,oneof"` // directive requests a control-plane initiated action on the agent.
}

func (*AgentSessionResponse_Register) isAgentSessionResponse_Event() {}

func (*AgentSessionResponse_Heartbeat) isAgentSessionResponse_Event() {}

func (*AgentSessionResponse_Directive) isAgentSessionResponse_Event() {}

// RegisterRequest announces agent identity at session start.
//
// Security and stability notes:
// - agent_key must be stable across reconnects and unique per agent identity.
// - caller should reflect execution context (for example: "scaled/startup").
// - capabilities should contain machine-parseable identifiers.
type RegisterRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Caller           string                 `protobuf:"bytes,1,opt,name=caller,proto3" json:"caller,omitempty"`                                                                           // caller identifies source code path or subsystem emitting registration.
	AgentKey         string                 `protobuf:"bytes,2,opt,name=agent_key,json=agentKey,proto3" json:"agent_key,omitempty"`                                                       // agent_key is a stable identity key used for idempotent registration.
	DesiredAgentName string                 `protobuf:"bytes,3,opt,name=desired_agent_name,json=desiredAgentName,proto3" json:"desired_agent_name,omitempty"`                             // desired_agent_name is an optional human-readable display name hint.
	AgentVersion     string                 `protobuf:"bytes,4,opt,name=agent_version,json=agentVersion,proto3" json:"agent_version,omitempty"`                                           // agent_version identifies the running agent build/version.
	Capabilities     []string               `protobuf:"bytes,5,rep,name=capabilities,proto3" json:"capabilities,omitempty"`                                                               // capabilities lists runtime features the agent can serve.
	Labels           map[string]string      `protobuf:"bytes,6,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // labels is optional routing/filtering metadata; keep values low-cardinality and free of secrets.
	StartedUnix      int64                  `protobuf:"varint,7,opt,name=started_unix,json=startedUnix,proto3" json:"started_unix,omitempty"`                                             // started_unix is the agent process start time in unix seconds.
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *RegisterRequest) Reset() {
	*x = RegisterRequest{}
	mi := &file_contracts_proto_control_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterRequest) ProtoMessage() {}

func (x *RegisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_contracts_proto_control_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterRequest.ProtoReflect.Descriptor instead.
func (*RegisterRequest) Descriptor() ([]byte, []int) {
	return file_contracts_proto_control_proto_rawDescGZIP(), []int{4}
}

func (x *RegisterRequest) GetCaller() string {
	if x != nil {
		return x.Caller
	}
	return ""
}

func (x *RegisterRequest) GetAgentKey() string {
	if x != nil {
		return x.AgentKey
	}
	return ""
}

func (x *RegisterRequest) GetDesiredAgentName() string {
	if x != nil {
		return x.DesiredAgentName
	}
	return ""
}

func (x *RegisterRequest) GetAgentVersion() string {
	if x != nil {
		return x.AgentVersion
	}
	return ""
}

func (x *RegisterRequest) GetCapabilities() []string {
	if x != nil {
		return x.Capabilities
	}
	return nil
}

func (x *RegisterRequest) GetLabels() map[string]string {
	if x != nil {
		return x.Labels
	}
	return nil
}

func (x *RegisterRequest) GetStartedUnix() int64 {
	if x != nil {
		return x.StartedUnix
	}
	return 0
}

// RegisterResponse communicates registration acceptance and lease policy.
type RegisterResponse struct {
	state                    protoimpl.MessageState `protogen:"open.v1"`
	Accepted                 bool                   `protobuf:"varint,1,opt,name=accepted,proto3" json:"accepted,omitempty"`                                                                   // accepted indicates whether registration is admitted.
	AgentId                  string                 `protobuf:"bytes,2,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`                                                       // agent_id is the canonical control-plane identity for this agent.
	SessionId                string                 `protobuf:"bytes,3,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`                                                 // session_id identifies this stream session for heartbeat correlation.
	HeartbeatIntervalSeconds int64                  `protobuf:"varint,4,opt,name=heartbeat_interval_seconds,json=heartbeatIntervalSeconds,proto3" json:"heartbeat_interval_seconds,omitempty"` // heartbeat_interval_seconds is the expected heartbeat cadence.
	LeaseTtlSeconds          int64                  `protobuf:"varint,5,opt,name=lease_ttl_seconds,json=leaseTtlSeconds,proto3" json:"lease_ttl_seconds,omitempty"`                            // lease_ttl_seconds is the offline cutoff if heartbeats are missed.
	Message                  string                 `protobuf:"bytes,6,opt,name=message,proto3" json:"message,omitempty"`                                                                      // message provides human-readable acceptance or rejection details.
	unknownFields            protoimpl.UnknownFields
	sizeCache                protoimpl.SizeCache
}

func (x *RegisterResponse) Reset() {
	*x = RegisterResponse{}
	mi := &file_contracts_proto_control_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterResponse) ProtoMessage() {}

func (x *RegisterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_contracts_proto_control_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterResponse.ProtoReflect.Descriptor instead.
func (*RegisterResponse) Descriptor() ([]byte, []int) {
	return file_contracts_proto_control_proto_rawDescGZIP(), []int{5}
}

func (x *RegisterResponse) GetAccepted() bool {
	if x != nil {
		return x.Accepted
	}
	return false
}

func (x *RegisterResponse) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *RegisterResponse) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *RegisterResponse) GetHeartbeatIntervalSeconds() int64 {
	if x != nil {
		return x.HeartbeatIntervalSeconds
	}
	return 0
}

func (x *RegisterResponse) GetLeaseTtlSeconds() int64 {
	if x != nil {
		return x.LeaseTtlSeconds
	}
	return 0
}

func (x *RegisterResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// HeartbeatRequest updates liveness and runtime pressure for an active session.
type HeartbeatRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	SessionId        string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`                       // session_id must match the RegisterResponse session id.
	SentUnix         int64                  `protobuf:"varint,2,opt,name=sent_unix,json=sentUnix,proto3" json:"sent_unix,omitempty"`                         // sent_unix is when heartbeat was emitted by the agent in unix seconds.
	Status           string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`                                              // status is a compact runtime label (for example: "ready", "draining").
	RunningWorkloads uint32                 `protobuf:"varint,4,opt,name=running_workloads,json=runningWorkloads,proto3" json:"running_workloads,omitempty"` // running_workloads is the count of active workloads.
	QueuedWorkloads  uint32                 `protobuf:"varint,5,opt,name=queued_workloads,json=queuedWorkloads,proto3" json:"queued_workloads,omitempty"`    // queued_workloads is the count of pending workloads.
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *HeartbeatRequest) Reset() {
	*x = HeartbeatRequest{}
	mi := &file_contracts_proto_control_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatRequest) ProtoMessage() {}

func (x *HeartbeatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_contracts_proto_control_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatRequest.ProtoReflect.Descriptor instead.
func (*HeartbeatRequest) Descriptor() ([]byte, []int) {
	return file_contracts_proto_control_proto_rawDescGZIP(), []int{6}
}

func (x *HeartbeatRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *HeartbeatRequest) GetSentUnix() int64 {
	if x != nil {
		return x.SentUnix
	}
	return 0
}

func (x *HeartbeatRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *HeartbeatRequest) GetRunningWorkloads() uint32 {
	if x != nil {
		return x.RunningWorkloads
	}
	return 0
}

func (x *HeartbeatRequest) GetQueuedWorkloads() uint32 {
	if x != nil {
		return x.QueuedWorkloads
	}
	return 0
}

// HeartbeatResponse acknowledges a heartbeat and conveys server time.
type HeartbeatResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`                                   // ok indicates whether heartbeat processing was accepted.
	ServerUnix    int64                  `protobuf:"varint,2,opt,name=server_unix,json=serverUnix,proto3" json:"server_unix,omitempty"` // server_unix is control-plane unix time when heartbeat was handled.
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`                          // message provides optional diagnostics for operators.
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatResponse) Reset() {
	*x = HeartbeatResponse{}
	mi := &file_contracts_proto_control_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatResponse) ProtoMessage() {}

func (x *HeartbeatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_contracts_proto_control_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatResponse.ProtoReflect.Descriptor instead.
func (*HeartbeatResponse) Descriptor() ([]byte, []int) {
	return file_contracts_proto_control_proto_rawDescGZIP(), []int{7}
}

func (x *HeartbeatResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *HeartbeatResponse) GetServerUnix() int64 {
	if x != nil {
		return x.ServerUnix
	}
	return 0
}

func (x *HeartbeatResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// CapabilityUpdate reports runtime capability changes on the same session.
type CapabilityUpdate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"` // session_id identifies the active control session.
	Capabilities  []string               `protobuf:"bytes,2,rep,name=capabilities,proto3" json:"capabilities,omitempty"`            // capabilities replaces the currently advertised capability set.
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CapabilityUpdate) Reset() {
	*x = CapabilityUpdate{}
	mi := &file_contracts_proto_control_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CapabilityUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CapabilityUpdate) ProtoMessage() {}

func (x *CapabilityUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_contracts_proto_control_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CapabilityUpdate.ProtoReflect.Descriptor instead.
func (*CapabilityUpdate) Descriptor() ([]byte, []int) {
	return file_contracts_proto_control_proto_rawDescGZIP(), []int{8}
}

func (x *CapabilityUpdate) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *CapabilityUpdate) GetCapabilities() []string {
	if x != nil {
		return x.Capabilities
	}
	return nil
}

// ControlDirective communicates asynchronous control-plane instructions.
//
// Domain payloads are split so node, agent, and workload controls evolve independently.
type ControlDirective struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	DirectiveId    string                 `protobuf:"bytes,1,opt,name=directive_id,json=directiveId,proto3" json:"directive_id,omitempty"`           // directive_id is a unique id for idempotent processing and audit.
	Reason         string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`                                        // reason provides operator-readable context for the directive.
	EffectiveUnix  int64                  `protobuf:"varint,3,opt,name=effective_unix,json=effectiveUnix,proto3" json:"effective_unix,omitempty"`    // effective_unix is when the directive should be considered active.
	TimeoutSeconds uint32                 `protobuf:"varint,4,opt,name=timeout_seconds,json=timeoutSeconds,proto3" json:"timeout_seconds,omitempty"` // timeout_seconds bounds directive execution before timeout failure is reported.
	// Types that are valid to be assigned to Target:
	//
	//	*ControlDirective_Node
	//	*ControlDirective_Agent
	//	*ControlDirective_Workload
	Target        isControlDirective_Target `protobuf_oneof:"target"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ControlDirective) Reset() {
	*x = ControlDirective{}
	mi := &file_contracts_proto_control_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ControlDirective) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ControlDirective) ProtoMessage() {}

func (x *ControlDirective) ProtoReflect() protoreflect.Message {
	mi := &file_contracts_proto_control_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ControlDirective.ProtoReflect.Descriptor instead.
func (*ControlDirective) Descriptor() ([]byte, []int) {
	return file_contracts_proto_control_proto_rawDescGZIP(), []int{9}
}

func (x *ControlDirective) GetDirectiveId() string {
	if x != nil {
		return x.DirectiveId
	}
	return ""
}

func (x *ControlDirective) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *ControlDirective) GetEffectiveUnix() int64 {
	if x != nil {
		return x.EffectiveUnix
	}
	return 0
}

func (x *ControlDirective) GetTimeoutSeconds() uint32 {
	if x != nil {
		return x.TimeoutSeconds
	}
	return 0
}

func (x *ControlDirective) GetTarget() isControlDirective_Target {
	if x != nil {
		return x.Target
	}
	return nil
}

func (x *ControlDirective) GetNode() *NodeDirective {
	if x != nil {
		if x, ok := x.Target.(*ControlDirective_Node); ok {
			return x.Node
		}
	}
	return nil
}

func (x *ControlDirective) GetAgent() *AgentDirective {
	if x != nil {
		if x, ok := x.Target.(*ControlDirective_Agent); ok {
			return x.Agent
		}
	}
	return nil
}

func (x *ControlDirective) GetWorkload() *WorkloadDirective {
	if x != nil {
		if x, ok := x.Target.(*ControlDirective_Workload); ok {
			return x.Workload
		}
	}
	return nil
}

type isControlDirective_Target interface {
	isControlDirective_Target()
}

type ControlDirective_Node struct {
	Node *NodeDirective `protobuf:"bytes,10,opt,name=node,proto3,oneof"` // node targets host lifecycle controls such as drain and reboot.
}

type ControlDirective_Agent struct {
	Agent *AgentDirective `protobuf:"bytes,11,opt,name=agent,proto3,oneof"` // agent targets runtime lifecycle controls such as reload and upgrade.
}

type ControlDirective_Workload struct {
	Workload *WorkloadDirective `protobuf:"bytes,12,opt,name=workload,proto3,oneof"` // workload targets workload lifecycle controls such as deploy and scale.
}

func (*ControlDirective_Node) isControlDirective_Target() {}

func (*ControlDirective_Agent) isControlDirective_Target() {}

func (*ControlDirective_Workload) isControlDirective_Target() {}

// NodeDirective configures host-level operations.
//
// Safety note:
// - NODE_POWEROFF is intentionally excluded in this revision.
type NodeDirective struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          NodeDirectiveType      `protobuf:"varint,1,opt,name=type,proto3,enum=control.v1.NodeDirectiveType" json:"type,omitempty"`   // type selects the node operation.
	GraceSeconds  uint32                 `protobuf:"varint,2,opt,name=grace_seconds,json=graceSeconds,proto3" json:"grace_seconds,omitempty"` // grace_seconds is drain/termination grace for operations that require quiescing.
	Force         bool                   `protobuf:"varint,3,opt,name=force,proto3" json:"force,omitempty"`                                   // force allows emergency execution when graceful constraints cannot be met.
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NodeDirective) Reset() {
	*x = NodeDirective{}
	mi := &file_contracts_proto_control_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeDirective) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeDirective) ProtoMessage() {}

func (x *NodeDirective) ProtoReflect() protoreflect.Message {
	mi := &file_contracts_proto_control_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeDirective.ProtoReflect.Descriptor instead.
func (*NodeDirective) Descriptor() ([]byte, []int) {
	return file_contracts_proto_control_proto_rawDescGZIP(), []int{10}
}

func (x *NodeDirective) GetType() NodeDirectiveType {
	if x != nil {
		return x.Type
	}
	return NodeDirectiveType_NODE_DIRECTIVE_TYPE_UNSPECIFIED
}

func (x *NodeDirective) GetGraceSeconds() uint32 {
	if x != nil {
		return x.GraceSeconds
	}
	return 0
}

func (x *NodeDirective) GetForce() bool {
	if x != nil {
		return x.Force
	}
	return false
}

// AgentDirective configures agent process operations.
type AgentDirective struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Type               AgentDirectiveType     `protobuf:"varint,1,opt,name=type,proto3,enum=control.v1.AgentDirectiveType" json:"type,omitempty"`                      // type selects the agent operation.
	TargetVersion      string                 `protobuf:"bytes,2,opt,name=target_version,json=targetVersion,proto3" json:"target_version,omitempty"`                   // target_version is the desired agent version for upgrade.
	ArtifactUrl        string                 `protobuf:"bytes,3,opt,name=artifact_url,json=artifactUrl,proto3" json:"artifact_url,omitempty"`                         // artifact_url points to the signed upgrade artifact.
	ArtifactSha256     string                 `protobuf:"bytes,4,opt,name=artifact_sha256,json=artifactSha256,proto3" json:"artifact_sha256,omitempty"`                // artifact_sha256 verifies artifact integrity before install.
	RequireDrain       bool                   `protobuf:"varint,5,opt,name=require_drain,json=requireDrain,proto3" json:"require_drain,omitempty"`                     // require_drain forces node drain before disruptive agent operations.
	RebootAfterUpgrade bool                   `protobuf:"varint,6,opt,name=reboot_after_upgrade,json=rebootAfterUpgrade,proto3" json:"reboot_after_upgrade,omitempty"` // reboot_after_upgrade requests explicit reboot after a successful upgrade.
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *AgentDirective) Reset() {
	*x = AgentDirective{}
	mi := &file_contracts_proto_control_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentDirective) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentDirective) ProtoMessage() {}

func (x *AgentDirective) ProtoReflect() protoreflect.Message {
	mi := &file_contracts_proto_control_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentDirective.ProtoReflect.Descriptor instead.
func (*AgentDirective) Descriptor() ([]byte, []int) {
	return file_contracts_proto_control_proto_rawDescGZIP(), []int{11}
}

func (x *AgentDirective) GetType() AgentDirectiveType {
	if x != nil {
		return x.Type
	}
	return AgentDirectiveType_AGENT_DIRECTIVE_TYPE_UNSPECIFIED
}

func (x *AgentDirective) GetTargetVersion() string {
	if x != nil {
		return x.TargetVersion
	}
	return ""
}

func (x *AgentDirective) GetArtifactUrl() string {
	if x != nil {
		return x.ArtifactUrl
	}
	return ""
}

func (x *AgentDirective) GetArtifactSha256() string {
	if x != nil {
		return x.ArtifactSha256
	}
	return ""
}

func (x *AgentDirective) GetRequireDrain() bool {
	if x != nil {
		return x.RequireDrain
	}
	return false
}

func (x *AgentDirective) GetRebootAfterUpgrade() bool {
	if x != nil {
		return x.RebootAfterUpgrade
	}
	return false
}

// WorkloadDirective configures workload lifecycle operations.
type WorkloadDirective struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Type            WorkloadDirectiveType  `protobuf:"varint,1,opt,name=type,proto3,enum=control.v1.WorkloadDirectiveType" json:"type,omitempty"`                                        // type selects the workload operation.
	WorkloadId      string                 `protobuf:"bytes,2,opt,name=workload_id,json=workloadId,proto3" json:"workload_id,omitempty"`                                                 // workload_id is the stable control-plane workload identity.
	WorkloadName    string                 `protobuf:"bytes,3,opt,name=workload_name,json=workloadName,proto3" json:"workload_name,omitempty"`                                           // workload_name is an optional human-readable workload name.
	ImageRef        string                 `protobuf:"bytes,4,opt,name=image_ref,json=imageRef,proto3" json:"image_ref,omitempty"`                                                       // image_ref identifies the image/artifact for deploy or restart-from-image.
	DesiredReplicas uint32                 `protobuf:"varint,5,opt,name=desired_replicas,json=desiredReplicas,proto3" json:"desired_replicas,omitempty"`                                 // desired_replicas applies to scale operations.
	Labels          map[string]string      `protobuf:"bytes,6,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // labels carry optional workload metadata hints for scheduling/routing.
	ProjectId       string                 `protobuf:"bytes,7,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`                                                    // project_id scopes the workload to its owning project and must be paired with workload_id.
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *WorkloadDirective) Reset() {
	*x = WorkloadDirective{}
	mi := &file_contracts_proto_control_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkloadDirective) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkloadDirective) ProtoMessage() {}

func (x *WorkloadDirective) ProtoReflect() protoreflect.Message {
	mi := &file_contracts_proto_control_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkloadDirective.ProtoReflect.Descriptor instead.
func (*WorkloadDirective) Descriptor() ([]byte, []int) {
	return file_contracts_proto_control_proto_rawDescGZIP(), []int{12}
}

func (x *WorkloadDirective) GetType() WorkloadDirectiveType {
	if x != nil {
		return x.Type
	}
	return WorkloadDirectiveType_WORKLOAD_DIRECTIVE_TYPE_UNSPECIFIED
}

func (x *WorkloadDirective) GetWorkloadId() string {
	if x != nil {
		return x.WorkloadId
	}
	return ""
}

func (x *WorkloadDirective) GetWorkloadName() string {
	if x != nil {
		return x.WorkloadName
	}
	return ""
}

func (x *WorkloadDirective) GetImageRef() string {
	if x != nil {
		return x.ImageRef
	}
	return ""
}

func (x *WorkloadDirective) GetDesiredReplicas() uint32 {
	if x != nil {
		return x.DesiredReplicas
	}
	return 0
}

func (x *WorkloadDirective) GetLabels() map[string]string {
	if x != nil {
		return x.Labels
	}
	return nil
}

func (x *WorkloadDirective) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

// DirectiveAck reports immediate acceptance/rejection of a directive.
type DirectiveAck struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	DirectiveId      string                 `protobuf:"bytes,1,opt,name=directive_id,json=directiveId,proto3" json:"directive_id,omitempty"`                 // directive_id identifies which control-plane directive this ack references.
	Accepted         bool                   `protobuf:"varint,2,opt,name=accepted,proto3" json:"accepted,omitempty"`                                         // accepted indicates whether directive validation/admission succeeded.
	Message          string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`                                            // message provides a concise accept/reject reason.
	AcknowledgedUnix int64                  `protobuf:"varint,4,opt,name=acknowledged_unix,json=acknowledgedUnix,proto3" json:"acknowledged_unix,omitempty"` // acknowledged_unix is when the directive was acknowledged by the agent.
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *DirectiveAck) Reset() {
	*x = DirectiveAck{}
	mi := &file_contracts_proto_control_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DirectiveAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DirectiveAck) ProtoMessage() {}

func (x *DirectiveAck) ProtoReflect() protoreflect.Message {
	mi := &file_contracts_proto_control_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DirectiveAck.ProtoReflect.Descriptor instead.
func (*DirectiveAck) Descriptor() ([]byte, []int) {
	return file_contracts_proto_control_proto_rawDescGZIP(), []int{13}
}

func (x *DirectiveAck) GetDirectiveId() string {
	if x != nil {
		return x.DirectiveId
	}
	return ""
}

func (x *DirectiveAck) GetAccepted() bool {
	if x != nil {
		return x.Accepted
	}
	return false
}

func (x *DirectiveAck) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *DirectiveAck) GetAcknowledgedUnix() int64 {
	if x != nil {
		return x.AcknowledgedUnix
	}
	return 0
}

// DirectiveProgress reports in-flight execution status for a directive.
type DirectiveProgress struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DirectiveId   string                 `protobuf:"bytes,1,opt,name=directive_id,json=directiveId,proto3" json:"directive_id,omitempty"`  // directive_id identifies which control-plane directive this progress references.
	Phase         string                 `protobuf:"bytes,2,opt,name=phase,proto3" json:"phase,omitempty"`                                 // phase is an implementation-defined state label (for example: "draining", "downloading").
	Percent       uint32                 `protobuf:"varint,3,opt,name=percent,proto3" json:"percent,omitempty"`                            // percent is optional coarse completion percentage in [0, 100].
	Message       string                 `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`                             // message provides operator-readable progress details.
	UpdatedUnix   int64                  `protobuf:"varint,5,opt,name=updated_unix,json=updatedUnix,proto3" json:"updated_unix,omitempty"` // updated_unix is when this progress snapshot was emitted.
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DirectiveProgress) Reset() {
	*x = DirectiveProgress{}
	mi := &file_contracts_proto_control_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DirectiveProgress) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DirectiveProgress) ProtoMessage() {}

func (x *DirectiveProgress) ProtoReflect() protoreflect.Message {
	mi := &file_contracts_proto_control_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DirectiveProgress.ProtoReflect.Descriptor instead.
func (*DirectiveProgress) Descriptor() ([]byte, []int) {
	return file_contracts_proto_control_proto_rawDescGZIP(), []int{14}
}

func (x *DirectiveProgress) GetDirectiveId() string {
	if x != nil {
		return x.DirectiveId
	}
	return ""
}

func (x *DirectiveProgress) GetPhase() string {
	if x != nil {
		return x.Phase
	}
	return ""
}

func (x *DirectiveProgress) GetPercent() uint32 {
	if x != nil {
		return x.Percent
	}
	return 0
}

func (x *DirectiveProgress) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *DirectiveProgress) GetUpdatedUnix() int64 {
	if x != nil {
		return x.UpdatedUnix
	}
	return 0
}

// DirectiveResult reports final completion state for a directive.
type DirectiveResult struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	DirectiveId     string                 `protobuf:"bytes,1,opt,name=directive_id,json=directiveId,proto3" json:"directive_id,omitempty"`              // directive_id identifies which control-plane directive this result references.
	Status          DirectiveResultStatus  `protobuf:"varint,2,opt,name=status,proto3,enum=control.v1.DirectiveResultStatus" json:"status,omitempty"`    // status reports final completion outcome.
	Message         string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`                                         // message provides terminal details, including failure context.
	CompletedUnix   int64                  `protobuf:"varint,4,opt,name=completed_unix,json=completedUnix,proto3" json:"completed_unix,omitempty"`       // completed_unix is when final completion was reached.
	RollbackApplied bool                   `protobuf:"varint,5,opt,name=rollback_applied,json=rollbackApplied,proto3" json:"rollback_applied,omitempty"` // rollback_applied indicates whether rollback logic executed.
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *DirectiveResult) Reset() {
	*x = DirectiveResult{}
	mi := &file_contracts_proto_control_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DirectiveResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DirectiveResult) ProtoMessage() {}

func (x *DirectiveResult) ProtoReflect() protoreflect.Message {
	mi := &file_contracts_proto_control_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DirectiveResult.ProtoReflect.Descriptor instead.
func (*DirectiveResult) Descriptor() ([]byte, []int) {
	return file_contracts_proto_control_proto_rawDescGZIP(), []int{15}
}

func (x *DirectiveResult) GetDirectiveId() string {
	if x != nil {
		return x.DirectiveId
	}
	return ""
}

func (x *DirectiveResult) GetStatus() DirectiveResultStatus {
	if x != nil {
		return x.Status
	}
	return DirectiveResultStatus_DIRECTIVE_RESULT_STATUS_UNSPECIFIED
}

func (x *DirectiveResult) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *DirectiveResult) GetCompletedUnix() int64 {
	if x != nil {
		return x.CompletedUnix
	}
	return 0
}

func (x *DirectiveResult) GetRollbackApplied() bool {
	if x != nil {
		return x.RollbackApplied
	}
	return false
}

// WorkloadsReport carries per-workload runtime telemetry for one sample window.
type WorkloadsReport struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"` // session_id identifies the active control session emitting this report.
	SentUnix      int64                  `protobuf:"varint,2,opt,name=sent_unix,json=sentUnix,proto3" json:"sent_unix,omitempty"`   // sent_unix is when this report snapshot was sampled by the agent.
	Sequence      uint64                 `protobuf:"varint,3,opt,name=sequence,proto3" json:"sequence,omitempty"`                   // sequence is monotonic per session and helps detect dropped report frames.
	Workloads     []*WorkloadRuntime     `protobuf:"bytes,4,rep,name=workloads,proto3" json:"workloads,omitempty"`                  // workloads is the current set of workload runtime records observed on the node.
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WorkloadsReport) Reset() {
	*x = WorkloadsReport{}
	mi := &file_contracts_proto_control_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkloadsReport) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkloadsReport) ProtoMessage() {}

func (x *WorkloadsReport) ProtoReflect() protoreflect.Message {
	mi := &file_contracts_proto_control_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkloadsReport.ProtoReflect.Descriptor instead.
func (*WorkloadsReport) Descriptor() ([]byte, []int) {
	return file_contracts_proto_control_proto_rawDescGZIP(), []int{16}
}

func (x *WorkloadsReport) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *WorkloadsReport) GetSentUnix() int64 {
	if x != nil {
		return x.SentUnix
	}
	return 0
}

func (x *WorkloadsReport) GetSequence() uint64 {
	if x != nil {
		return x.Sequence
	}
	return 0
}

func (x *WorkloadsReport) GetWorkloads() []*WorkloadRuntime {
	if x != nil {
		return x.Workloads
	}
	return nil
}

// WorkloadRuntime captures runtime state and resource usage for one workload instance.
type WorkloadRuntime struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ProjectId       string                 `protobuf:"bytes,1,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`                       // project_id scopes the workload to its owning project.
	WorkloadId      string                 `protobuf:"bytes,2,opt,name=workload_id,json=workloadId,proto3" json:"workload_id,omitempty"`                    // workload_id is the stable control-plane workload identity.
	VmId            string                 `protobuf:"bytes,3,opt,name=vm_id,json=vmId,proto3" json:"vm_id,omitempty"`                                      // vm_id identifies the firecracker microVM instance running this workload.
	State           WorkloadRuntimeState   `protobuf:"varint,4,opt,name=state,proto3,enum=control.v1.WorkloadRuntimeState" json:"state,omitempty"`          // state is the current lifecycle state for this workload instance.
	CpuUsagePercent float64                `protobuf:"fixed64,5,opt,name=cpu_usage_percent,json=cpuUsagePercent,proto3" json:"cpu_usage_percent,omitempty"` // cpu_usage_percent is current workload CPU usage percentage.
	MemoryUsedBytes uint64                 `protobuf:"varint,6,opt,name=memory_used_bytes,json=memoryUsedBytes,proto3" json:"memory_used_bytes,omitempty"`  // memory_used_bytes is current workload memory usage.
	DiskUsedBytes   uint64                 `protobuf:"varint,7,opt,name=disk_used_bytes,json=diskUsedBytes,proto3" json:"disk_used_bytes,omitempty"`        // disk_used_bytes is current writable disk usage for this workload.
	NetworkRxBytes  uint64                 `protobuf:"varint,8,opt,name=network_rx_bytes,json=networkRxBytes,proto3" json:"network_rx_bytes,omitempty"`     // network_rx_bytes is cumulative inbound network traffic for this workload.
	NetworkTxBytes  uint64                 `protobuf:"varint,9,opt,name=network_tx_bytes,json=networkTxBytes,proto3" json:"network_tx_bytes,omitempty"`     // network_tx_bytes is cumulative outbound network traffic for this workload.
	RestartCount    uint32                 `protobuf:"varint,10,opt,name=restart_count,json=restartCount,proto3" json:"restart_count,omitempty"`            // restart_count is the number of restarts observed for this workload instance.
	StartedUnix     int64                  `protobuf:"varint,11,opt,name=started_unix,json=startedUnix,proto3" json:"started_unix,omitempty"`               // started_unix is the workload instance start time in unix seconds.
	Message         string                 `protobuf:"bytes,12,opt,name=message,proto3" json:"message,omitempty"`                                           // message provides optional operator-readable runtime context.
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *WorkloadRuntime) Reset() {
	*x = WorkloadRuntime{}
	mi := &file_contracts_proto_control_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkloadRuntime) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkloadRuntime) ProtoMessage() {}

func (x *WorkloadRuntime) ProtoReflect() protoreflect.Message {
	mi := &file_contracts_proto_control_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkloadRuntime.ProtoReflect.Descriptor instead.
func (*WorkloadRuntime) Descriptor() ([]byte, []int) {
	return file_contracts_proto_control_proto_rawDescGZIP(), []int{17}
}

func (x *WorkloadRuntime) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

func (x *WorkloadRuntime) GetWorkloadId() string {
	if x != nil {
		return x.WorkloadId
	}
	return ""
}

func (x *WorkloadRuntime) GetVmId() string {
	if x != nil {
		return x.VmId
	}
	return ""
}

func (x *WorkloadRuntime) GetState() WorkloadRuntimeState {
	if x != nil {
		return x.State
	}
	return WorkloadRuntimeState_WORKLOAD_RUNTIME_STATE_UNSPECIFIED
}

func (x *WorkloadRuntime) GetCpuUsagePercent() float64 {
	if x != nil {
		return x.CpuUsagePercent
	}
	return 0
}

func (x *WorkloadRuntime) GetMemoryUsedBytes() uint64 {
	if x != nil {
		return x.MemoryUsedBytes
	}
	return 0
}

func (x *WorkloadRuntime) GetDiskUsedBytes() uint64 {
	if x != nil {
		return x.DiskUsedBytes
	}
	return 0
}

func (x *WorkloadRuntime) GetNetworkRxBytes() uint64 {
	if x != nil {
		return x.NetworkRxBytes
	}
	return 0
}

func (x *WorkloadRuntime) GetNetworkTxBytes() uint64 {
	if x != nil {
		return x.NetworkTxBytes
	}
	return 0
}

func (x *WorkloadRuntime) GetRestartCount() uint32 {
	if x != nil {
		return x.RestartCount
	}
	return 0
}

func (x *WorkloadRuntime) GetStartedUnix() int64 {
	if x != nil {
		return x.StartedUnix
	}
	return 0
}

func (x *WorkloadRuntime) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// NodeHealthReport carries machine-level telemetry for scheduling and operations.
type NodeHealthReport struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	SessionId            string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`                                     // session_id identifies the active control session emitting telemetry.
	SentUnix             int64                  `protobuf:"varint,2,opt,name=sent_unix,json=sentUnix,proto3" json:"sent_unix,omitempty"`                                       // sent_unix is when this telemetry snapshot was sampled by the agent.
	NodeStatus           string                 `protobuf:"bytes,3,opt,name=node_status,json=nodeStatus,proto3" json:"node_status,omitempty"`                                  // node_status is a compact label (for example: "ready", "draining", "degraded").
	CpuUsagePercent      float64                `protobuf:"fixed64,4,opt,name=cpu_usage_percent,json=cpuUsagePercent,proto3" json:"cpu_usage_percent,omitempty"`               // cpu_usage_percent is total CPU usage percentage across all cores.
	CpuCores             uint32                 `protobuf:"varint,5,opt,name=cpu_cores,json=cpuCores,proto3" json:"cpu_cores,omitempty"`                                       // cpu_cores is the number of logical CPU cores visible to the agent.
	MemoryTotalBytes     uint64                 `protobuf:"varint,6,opt,name=memory_total_bytes,json=memoryTotalBytes,proto3" json:"memory_total_bytes,omitempty"`             // memory_total_bytes is total node memory capacity.
	MemoryAvailableBytes uint64                 `protobuf:"varint,7,opt,name=memory_available_bytes,json=memoryAvailableBytes,proto3" json:"memory_available_bytes,omitempty"` // memory_available_bytes is currently available memory.
	DiskTotalBytes       uint64                 `protobuf:"varint,8,opt,name=disk_total_bytes,json=diskTotalBytes,proto3" json:"disk_total_bytes,omitempty"`                   // disk_total_bytes is total disk capacity for the primary data volume.
	DiskAvailableBytes   uint64                 `protobuf:"varint,9,opt,name=disk_available_bytes,json=diskAvailableBytes,proto3" json:"disk_available_bytes,omitempty"`       // disk_available_bytes is currently available space on the primary data volume.
	RunningWorkloads     uint32                 `protobuf:"varint,10,opt,name=running_workloads,json=runningWorkloads,proto3" json:"running_workloads,omitempty"`              // running_workloads is the number of active workloads currently running.
	QueuedWorkloads      uint32                 `protobuf:"varint,11,opt,name=queued_workloads,json=queuedWorkloads,proto3" json:"queued_workloads,omitempty"`                 // queued_workloads is the number of pending workloads waiting to start.
	UptimeSeconds        uint64                 `protobuf:"varint,12,opt,name=uptime_seconds,json=uptimeSeconds,proto3" json:"uptime_seconds,omitempty"`                       // uptime_seconds is host uptime since the last reboot.
	BootIdHash           string                 `protobuf:"bytes,13,opt,name=boot_id_hash,json=bootIdHash,proto3" json:"boot_id_hash,omitempty"`                               // boot_id_hash is a privacy-safe hash used to detect host reboot cycles.
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *NodeHealthReport) Reset() {
	*x = NodeHealthReport{}
	mi := &file_contracts_proto_control_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeHealthReport) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeHealthReport) ProtoMessage() {}

func (x *NodeHealthReport) ProtoReflect() protoreflect.Message {
	mi := &file_contracts_proto_control_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeHealthReport.ProtoReflect.Descriptor instead.
func (*NodeHealthReport) Descriptor() ([]byte, []int) {
	return file_contracts_proto_control_proto_rawDescGZIP(), []int{18}
}

func (x *NodeHealthReport) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *NodeHealthReport) GetSentUnix() int64 {
	if x != nil {
		return x.SentUnix
	}
	return 0
}

func (x *NodeHealthReport) GetNodeStatus() string {
	if x != nil {
		return x.NodeStatus
	}
	return ""
}

func (x *NodeHealthReport) GetCpuUsagePercent() float64 {
	if x != nil {
		return x.CpuUsagePercent
	}
	return 0
}

func (x *NodeHealthReport) GetCpuCores() uint32 {
	if x != nil {
		return x.CpuCores
	}
	return 0
}

func (x *NodeHealthReport) GetMemoryTotalBytes() uint64 {
	if x != nil {
		return x.MemoryTotalBytes
	}
	return 0
}

func (x *NodeHealthReport) GetMemoryAvailableBytes() uint64 {
	if x != nil {
		return x.MemoryAvailableBytes
	}
	return 0
}

func (x *NodeHealthReport) GetDiskTotalBytes() uint64 {
	if x != nil {
		return x.DiskTotalBytes
	}
	return 0
}

func (x *NodeHealthReport) GetDiskAvailableBytes() uint64 {
	if x != nil {
		return x.DiskAvailableBytes
	}
	return 0
}

func (x *NodeHealthReport) GetRunningWorkloads() uint32 {
	if x != nil {
		return x.RunningWorkloads
	}
	return 0
}

func (x *NodeHealthReport) GetQueuedWorkloads() uint32 {
	if x != nil {
		return x.QueuedWorkloads
	}
	return 0
}

func (x *NodeHealthReport) GetUptimeSeconds() uint64 {
	if x != nil {
		return x.UptimeSeconds
	}
	return 0
}

func (x *NodeHealthReport) GetBootIdHash() string {
	if x != nil {
		return x.BootIdHash
	}
	return ""
}

var File_contracts_proto_control_proto protoreflect.FileDescriptor

const file_contracts_proto_control_proto_rawDesc = "" +
	"\n" +
	"\x1dcontracts/proto/control.proto\x12\n" +
	"control.v1\"F\n" +
	"\rHealthRequest\x12\x16\n" +
	"\x06caller\x18\x01 \x01(\tR\x06caller\x12\x1d\n" +
	"\n" +
	"request_id\x18\x02 \x01(\tR\trequestId\"\xa9\x01\n" +
	"\x0eHealthResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x122\n" +
	"\x15control_plane_version\x18\x03 \x01(\tR\x13controlPlaneVersion\x12!\n" +
	"\fstarted_unix\x18\x04 \x01(\x03R\vstartedUnix\x12\x18\n" +
	"\amessage\x18\x05 \x01(\tR\amessage\"\xe9\x04\n" +
	"\x13AgentSessionRequest\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x129\n" +
	"\bregister\x18\x02 \x01(\v2\x1b.control.v1.RegisterRequestH\x00R\bregister\x12<\n" +
	"\theartbeat\x18\x03 \x01(\v2\x1c.control.v1.HeartbeatRequestH\x00R\theartbeat\x12K\n" +
	"\x11capability_update\x18\x04 \x01(\v2\x1c.control.v1.CapabilityUpdateH\x00R\x10capabilityUpdate\x12?\n" +
	"\rdirective_ack\x18\x05 \x01(\v2\x18.control.v1.DirectiveAckH\x00R\fdirectiveAck\x12N\n" +
	"\x12directive_progress\x18\x06 \x01(\v2\x1d.control.v1.DirectiveProgressH\x00R\x11directiveProgress\x12H\n" +
	"\x10directive_result\x18\a \x01(\v2\x1b.control.v1.DirectiveResultH\x00R\x0fdirectiveResult\x12?\n" +
	"\vnode_health\x18\b \x01(\v2\x1c.control.v1.NodeHealthReportH\x00R\n" +
	"nodeHealth\x12H\n" +
	"\x10workloads_report\x18\t \x01(\v2\x1b.control.v1.WorkloadsReportH\x00R\x0fworkloadsReportB\a\n" +
	"\x05event\"\xf7\x01\n" +
	"\x14AgentSessionResponse\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12:\n" +
	"\bregister\x18\x02 \x01(\v2\x1c.control.v1.RegisterResponseH\x00R\bregister\x12=\n" +
	"\theartbeat\x18\x03 \x01(\v2\x1d.control.v1.HeartbeatResponseH\x00R\theartbeat\x12<\n" +
	"\tdirective\x18\x04 \x01(\v2\x1c.control.v1.ControlDirectiveH\x00R\tdirectiveB\a\n" +
	"\x05event\"\xdc\x02\n" +
	"\x0fRegisterRequest\x12\x16\n" +
	"\x06caller\x18\x01 \x01(\tR\x06caller\x12\x1b\n" +
	"\tagent_key\x18\x02 \x01(\tR\bagentKey\x12,\n" +
	"\x12desired_agent_name\x18\x03 \x01(\tR\x10desiredAgentName\x12#\n" +
	"\ragent_version\x18\x04 \x01(\tR\fagentVersion\x12\"\n" +
	"\fcapabilities\x18\x05 \x03(\tR\fcapabilities\x12?\n" +
	"\x06labels\x18\x06 \x03(\v2'.control.v1.RegisterRequest.LabelsEntryR\x06labels\x12!\n" +
	"\fstarted_unix\x18\a \x01(\x03R\vstartedUnix\x1a9\n" +
	"\vLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xec\x01\n" +
	"\x10RegisterResponse\x12\x1a\n" +
	"\baccepted\x18\x01 \x01(\bR\baccepted\x12\x19\n" +
	"\bagent_id\x18\x02 \x01(\tR\aagentId\x12\x1d\n" +
	"\n" +
	"session_id\x18\x03 \x01(\tR\tsessionId\x12<\n" +
	"\x1aheartbeat_interval_seconds\x18\x04 \x01(\x03R\x18heartbeatIntervalSeconds\x12*\n" +
	"\x11lease_ttl_seconds\x18\x05 \x01(\x03R\x0fleaseTtlSeconds\x12\x18\n" +
	"\amessage\x18\x06 \x01(\tR\amessage\"\xbe\x01\n" +
	"\x10HeartbeatRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x1b\n" +
	"\tsent_unix\x18\x02 \x01(\x03R\bsentUnix\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\x12+\n" +
	"\x11running_workloads\x18\x04 \x01(\rR\x10runningWorkloads\x12)\n" +
	"\x10queued_workloads\x18\x05 \x01(\rR\x0fqueuedWorkloads\"^\n" +
	"\x11HeartbeatResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\x12\x1f\n" +
	"\vserver_unix\x18\x02 \x01(\x03R\n" +
	"serverUnix\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\"U\n" +
	"\x10CapabilityUpdate\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\"\n" +
	"\fcapabilities\x18\x02 \x03(\tR\fcapabilities\"\xc9\x02\n" +
	"\x10ControlDirective\x12!\n" +
	"\fdirective_id\x18\x01 \x01(\tR\vdirectiveId\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\x12%\n" +
	"\x0eeffective_unix\x18\x03 \x01(\x03R\reffectiveUnix\x12'\n" +
	"\x0ftimeout_seconds\x18\x04 \x01(\rR\x0etimeoutSeconds\x12/\n" +
	"\x04node\x18\n" +
	" \x01(\v2\x19.control.v1.NodeDirectiveH\x00R\x04node\x122\n" +
	"\x05agent\x18\v \x01(\v2\x1a.control.v1.AgentDirectiveH\x00R\x05agent\x12;\n" +
	"\bworkload\x18\f \x01(\v2\x1d.control.v1.WorkloadDirectiveH\x00R\bworkloadB\b\n" +
	"\x06target\"}\n" +
	"\rNodeDirective\x121\n" +
	"\x04type\x18\x01 \x01(\x0e2\x1d.control.v1.NodeDirectiveTypeR\x04type\x12#\n" +
	"\rgrace_seconds\x18\x02 \x01(\rR\fgraceSeconds\x12\x14\n" +
	"\x05force\x18\x03 \x01(\bR\x05force\"\x8e\x02\n" +
	"\x0eAgentDirective\x122\n" +
	"\x04type\x18\x01 \x01(\x0e2\x1e.control.v1.AgentDirectiveTypeR\x04type\x12%\n" +
	"\x0etarget_version\x18\x02 \x01(\tR\rtargetVersion\x12!\n" +
	"\fartifact_url\x18\x03 \x01(\tR\vartifactUrl\x12'\n" +
	"\x0fartifact_sha256\x18\x04 \x01(\tR\x0eartifactSha256\x12#\n" +
	"\rrequire_drain\x18\x05 \x01(\bR\frequireDrain\x120\n" +
	"\x14reboot_after_upgrade\x18\x06 \x01(\bR\x12rebootAfterUpgrade\"\xf5\x02\n" +
	"\x11WorkloadDirective\x125\n" +
	"\x04type\x18\x01 \x01(\x0e2!.control.v1.WorkloadDirectiveTypeR\x04type\x12\x1f\n" +
	"\vworkload_id\x18\x02 \x01(\tR\n" +
	"workloadId\x12#\n" +
	"\rworkload_name\x18\x03 \x01(\tR\fworkloadName\x12\x1b\n" +
	"\timage_ref\x18\x04 \x01(\tR\bimageRef\x12)\n" +
	"\x10desired_replicas\x18\x05 \x01(\rR\x0fdesiredReplicas\x12A\n" +
	"\x06labels\x18\x06 \x03(\v2).control.v1.WorkloadDirective.LabelsEntryR\x06labels\x12\x1d\n" +
	"\n" +
	"project_id\x18\a \x01(\tR\tprojectId\x1a9\n" +
	"\vLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x94\x01\n" +
	"\fDirectiveAck\x12!\n" +
	"\fdirective_id\x18\x01 \x01(\tR\vdirectiveId\x12\x1a\n" +
	"\baccepted\x18\x02 \x01(\bR\baccepted\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\x12+\n" +
	"\x11acknowledged_unix\x18\x04 \x01(\x03R\x10acknowledgedUnix\"\xa3\x01\n" +
	"\x11DirectiveProgress\x12!\n" +
	"\fdirective_id\x18\x01 \x01(\tR\vdirectiveId\x12\x14\n" +
	"\x05phase\x18\x02 \x01(\tR\x05phase\x12\x18\n" +
	"\apercent\x18\x03 \x01(\rR\apercent\x12\x18\n" +
	"\amessage\x18\x04 \x01(\tR\amessage\x12!\n" +
	"\fupdated_unix\x18\x05 \x01(\x03R\vupdatedUnix\"\xdb\x01\n" +
	"\x0fDirectiveResult\x12!\n" +
	"\fdirective_id\x18\x01 \x01(\tR\vdirectiveId\x129\n" +
	"\x06status\x18\x02 \x01(\x0e2!.control.v1.DirectiveResultStatusR\x06status\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\x12%\n" +
	"\x0ecompleted_unix\x18\x04 \x01(\x03R\rcompletedUnix\x12)\n" +
	"\x10rollback_applied\x18\x05 \x01(\bR\x0frollbackApplied\"\xa4\x01\n" +
	"\x0fWorkloadsReport\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x1b\n" +
	"\tsent_unix\x18\x02 \x01(\x03R\bsentUnix\x12\x1a\n" +
	"\bsequence\x18\x03 \x01(\x04R\bsequence\x129\n" +
	"\tworkloads\x18\x04 \x03(\v2\x1b.control.v1.WorkloadRuntimeR\tworkloads\"\xd4\x03\n" +
	"\x0fWorkloadRuntime\x12\x1d\n" +
	"\n" +
	"project_id\x18\x01 \x01(\tR\tprojectId\x12\x1f\n" +
	"\vworkload_id\x18\x02 \x01(\tR\n" +
	"workloadId\x12\x13\n" +
	"\x05vm_id\x18\x03 \x01(\tR\x04vmId\x126\n" +
	"\x05state\x18\x04 \x01(\x0e2 .control.v1.WorkloadRuntimeStateR\x05state\x12*\n" +
	"\x11cpu_usage_percent\x18\x05 \x01(\x01R\x0fcpuUsagePercent\x12*\n" +
	"\x11memory_used_bytes\x18\x06 \x01(\x04R\x0fmemoryUsedBytes\x12&\n" +
	"\x0fdisk_used_bytes\x18\a \x01(\x04R\rdiskUsedBytes\x12(\n" +
	"\x10network_rx_bytes\x18\b \x01(\x04R\x0enetworkRxBytes\x12(\n" +
	"\x10network_tx_bytes\x18\t \x01(\x04R\x0enetworkTxBytes\x12#\n" +
	"\rrestart_count\x18\n" +
	" \x01(\rR\frestartCount\x12!\n" +
	"\fstarted_unix\x18\v \x01(\x03R\vstartedUnix\x12\x18\n" +
	"\amessage\x18\f \x01(\tR\amessage\"\x99\x04\n" +
	"\x10NodeHealthReport\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x1b\n" +
	"\tsent_unix\x18\x02 \x01(\x03R\bsentUnix\x12\x1f\n" +
	"\vnode_status\x18\x03 \x01(\tR\n" +
	"nodeStatus\x12*\n" +
	"\x11cpu_usage_percent\x18\x04 \x01(\x01R\x0fcpuUsagePercent\x12\x1b\n" +
	"\tcpu_cores\x18\x05 \x01(\rR\bcpuCores\x12,\n" +
	"\x12memory_total_bytes\x18\x06 \x01(\x04R\x10memoryTotalBytes\x124\n" +
	"\x16memory_available_bytes\x18\a \x01(\x04R\x14memoryAvailableBytes\x12(\n" +
	"\x10disk_total_bytes\x18\b \x01(\x04R\x0ediskTotalBytes\x120\n" +
	"\x14disk_available_bytes\x18\t \x01(\x04R\x12diskAvailableBytes\x12+\n" +
	"\x11running_workloads\x18\n" +
	" \x01(\rR\x10runningWorkloads\x12)\n" +
	"\x10queued_workloads\x18\v \x01(\rR\x0fqueuedWorkloads\x12%\n" +
	"\x0euptime_seconds\x18\f \x01(\x04R\ruptimeSeconds\x12 \n" +
	"\fboot_id_hash\x18\r \x01(\tR\n" +
	"bootIdHash*\x97\x01\n" +
	"\x11NodeDirectiveType\x12#\n" +
	"\x1fNODE_DIRECTIVE_TYPE_UNSPECIFIED\x10\x00\x12\x1d\n" +
	"\x19NODE_DIRECTIVE_TYPE_DRAIN\x10\x01\x12\x1e\n" +
	"\x1aNODE_DIRECTIVE_TYPE_RESUME\x10\x02\x12\x1e\n" +
	"\x1aNODE_DIRECTIVE_TYPE_REBOOT\x10\x03*\x9f\x01\n" +
	"\x12AgentDirectiveType\x12$\n" +
	" AGENT_DIRECTIVE_TYPE_UNSPECIFIED\x10\x00\x12\x1f\n" +
	"\x1bAGENT_DIRECTIVE_TYPE_RELOAD\x10\x01\x12 \n" +
	"\x1cAGENT_DIRECTIVE_TYPE_UPGRADE\x10\x02\x12 \n" +
	"\x1cAGENT_DIRECTIVE_TYPE_RESTART\x10\x03*\xce\x01\n" +
	"\x15WorkloadDirectiveType\x12'\n" +
	"#WORKLOAD_DIRECTIVE_TYPE_UNSPECIFIED\x10\x00\x12\"\n" +
	"\x1eWORKLOAD_DIRECTIVE_TYPE_DEPLOY\x10\x01\x12 \n" +
	"\x1cWORKLOAD_DIRECTIVE_TYPE_STOP\x10\x02\x12#\n" +
	"\x1fWORKLOAD_DIRECTIVE_TYPE_RESTART\x10\x03\x12!\n" +
	"\x1dWORKLOAD_DIRECTIVE_TYPE_SCALE\x10\x04*\xb2\x01\n" +
	"\x15DirectiveResultStatus\x12'\n" +
	"#DIRECTIVE_RESULT_STATUS_UNSPECIFIED\x10\x00\x12%\n" +
	"!DIRECTIVE_RESULT_STATUS_SUCCEEDED\x10\x01\x12\"\n" +
	"\x1eDIRECTIVE_RESULT_STATUS_FAILED\x10\x02\x12%\n" +
	"!DIRECTIVE_RESULT_STATUS_CANCELLED\x10\x03*\x97\x02\n" +
	"\x14WorkloadRuntimeState\x12&\n" +
	"\"WORKLOAD_RUNTIME_STATE_UNSPECIFIED\x10\x00\x12\"\n" +
	"\x1eWORKLOAD_RUNTIME_STATE_PENDING\x10\x01\x12#\n" +
	"\x1fWORKLOAD_RUNTIME_STATE_STARTING\x10\x02\x12\"\n" +
	"\x1eWORKLOAD_RUNTIME_STATE_RUNNING\x10\x03\x12#\n" +
	"\x1fWORKLOAD_RUNTIME_STATE_DRAINING\x10\x04\x12\"\n" +
	"\x1eWORKLOAD_RUNTIME_STATE_STOPPED\x10\x05\x12!\n" +
	"\x1dWORKLOAD_RUNTIME_STATE_FAILED\x10\x062\xa5\x01\n" +
	"\fControlPlane\x12?\n" +
	"\x06Health\x12\x19.control.v1.HealthRequest\x1a\x1a.control.v1.HealthResponse\x12T\n" +
	"\vOpenSession\x12\x1f.control.v1.AgentSessionRequest\x1a .control.v1.AgentSessionResponse(\x010\x01BDZBgithub.com/t0gun/spacescale/packages/proto-go/control/v1;controlv1b\x06proto3"

var (
	file_contracts_proto_control_proto_rawDescOnce sync.Once
	file_contracts_proto_control_proto_rawDescData []byte
)

func file_contracts_proto_control_proto_rawDescGZIP() []byte {
	file_contracts_proto_control_proto_rawDescOnce.Do(func() {
		file_contracts_proto_control_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_contracts_proto_control_proto_rawDesc), len(file_contracts_proto_control_proto_rawDesc)))
	})
	return file_contracts_proto_control_proto_rawDescData
}

var file_contracts_proto_control_proto_enumTypes = make([]protoimpl.EnumInfo, 5)
var file_contracts_proto_control_proto_msgTypes = make([]protoimpl.MessageInfo, 21)
var file_contracts_proto_control_proto_goTypes = []any{
	(NodeDirectiveType)(0),       // 0: control.v1.NodeDirectiveType
	(AgentDirectiveType)(0),      // 1: control.v1.AgentDirectiveType
	(WorkloadDirectiveType)(0),   // 2: control.v1.WorkloadDirectiveType
	(DirectiveResultStatus)(0),   // 3: control.v1.DirectiveResultStatus
	(WorkloadRuntimeState)(0),    // 4: control.v1.WorkloadRuntimeState
	(*HealthRequest)(nil),        // 5: control.v1.HealthRequest
	(*HealthResponse)(nil),       // 6: control.v1.HealthResponse
	(*AgentSessionRequest)(nil),  // 7: control.v1.AgentSessionRequest
	(*AgentSessionResponse)(nil), // 8: control.v1.AgentSessionResponse
	(*RegisterRequest)(nil),      // 9: control.v1.RegisterRequest
	(*RegisterResponse)(nil),     // 10: control.v1.RegisterResponse
	(*HeartbeatRequest)(nil),     // 11: control.v1.HeartbeatRequest
	(*HeartbeatResponse)(nil),    // 12: control.v1.HeartbeatResponse
	(*CapabilityUpdate)(nil),     // 13: control.v1.CapabilityUpdate
	(*ControlDirective)(nil),     // 14: control.v1.ControlDirective
	(*NodeDirective)(nil),        // 15: control.v1.NodeDirective
	(*AgentDirective)(nil),       // 16: control.v1.AgentDirective
	(*WorkloadDirective)(nil),    // 17: control.v1.WorkloadDirective
	(*DirectiveAck)(nil),         // 18: control.v1.DirectiveAck
	(*DirectiveProgress)(nil),    // 19: control.v1.DirectiveProgress
	(*DirectiveResult)(nil),      // 20: control.v1.DirectiveResult
	(*WorkloadsReport)(nil),      // 21: control.v1.WorkloadsReport
	(*WorkloadRuntime)(nil),      // 22: control.v1.WorkloadRuntime
	(*NodeHealthReport)(nil),     // 23: control.v1.NodeHealthReport
	nil,                          // 24: control.v1.RegisterRequest.LabelsEntry
	nil,                          // 25: control.v1.WorkloadDirective.LabelsEntry
}
var file_contracts_proto_control_proto_depIdxs = []int32{
	9,  // 0: control.v1.AgentSessionRequest.register:type_name -> control.v1.RegisterRequest
	11, // 1: control.v1.AgentSessionRequest.heartbeat:type_name -> control.v1.HeartbeatRequest
	13, // 2: control.v1.AgentSessionRequest.capability_update:type_name -> control.v1.CapabilityUpdate
	18, // 3: control.v1.AgentSessionRequest.directive_ack:type_name -> control.v1.DirectiveAck
	19, // 4: control.v1.AgentSessionRequest.directive_progress:type_name -> control.v1.DirectiveProgress
	20, // 5: control.v1.AgentSessionRequest.directive_result:type_name -> control.v1.DirectiveResult
	23, // 6: control.v1.AgentSessionRequest.node_health:type_name -> control.v1.NodeHealthReport
	21, // 7: control.v1.AgentSessionRequest.workloads_report:type_name -> control.v1.WorkloadsReport
	10, // 8: control.v1.AgentSessionResponse.register:type_name -> control.v1.RegisterResponse
	12, // 9: control.v1.AgentSessionResponse.heartbeat:type_name -> control.v1.HeartbeatResponse
	14, // 10: control.v1.AgentSessionResponse.directive:type_name -> control.v1.ControlDirective
	24, // 11: control.v1.RegisterRequest.labels:type_name -> control.v1.RegisterRequest.LabelsEntry
	15, // 12: control.v1.ControlDirective.node:type_name -> control.v1.NodeDirective
	16, // 13: control.v1.ControlDirective.agent:type_name -> control.v1.AgentDirective
	17, // 14: control.v1.ControlDirective.workload:type_name -> control.v1.WorkloadDirective
	0,  // 15: control.v1.NodeDirective.type:type_name -> control.v1.NodeDirectiveType
	1,  // 16: control.v1.AgentDirective.type:type_name -> control.v1.AgentDirectiveType
	2,  // 17: control.v1.WorkloadDirective.type:type_name -> control.v1.WorkloadDirectiveType
	25, // 18: control.v1.WorkloadDirective.labels:type_name -> control.v1.WorkloadDirective.LabelsEntry
	3,  // 19: control.v1.DirectiveResult.status:type_name -> control.v1.DirectiveResultStatus
	22, // 20: control.v1.WorkloadsReport.workloads:type_name -> control.v1.WorkloadRuntime
	4,  // 21: control.v1.WorkloadRuntime.state:type_name -> control.v1.WorkloadRuntimeState
	5,  // 22: control.v1.ControlPlane.Health:input_type -> control.v1.HealthRequest
	7,  // 23: control.v1.ControlPlane.OpenSession:input_type -> control.v1.AgentSessionRequest
	6,  // 24: control.v1.ControlPlane.Health:output_type -> control.v1.HealthResponse
	8,  // 25: control.v1.ControlPlane.OpenSession:output_type -> control.v1.AgentSessionResponse
	24, // [24:26] is the sub-list for method output_type
	22, // [22:24] is the sub-list for method input_type
	22, // [22:22] is the sub-list for extension type_name
	22, // [22:22] is the sub-list for extension extendee
	0,  // [0:22] is the sub-list for field type_name
}

func init() { file_contracts_proto_control_proto_init() }
func file_contracts_proto_control_proto_init() {
	if File_contracts_proto_control_proto != nil {
		return
	}
	file_contracts_proto_control_proto_msgTypes[2].OneofWrappers = []any{
		(*AgentSessionRequest_Register)(nil),
		(*AgentSessionRequest_Heartbeat)(nil),
		(*AgentSessionRequest_CapabilityUpdate)(nil),
		(*AgentSessionRequest_DirectiveAck)(nil),
		(*AgentSessionRequest_DirectiveProgress)(nil),
		(*AgentSessionRequest_DirectiveResult)(nil),
		(*AgentSessionRequest_NodeHealth)(nil),
		(*AgentSessionRequest_WorkloadsReport)(nil),
	}
	file_contracts_proto_control_proto_msgTypes[3].OneofWrappers = []any{
		(*AgentSessionResponse_Register)(nil),
		(*AgentSessionResponse_Heartbeat)(nil),
		(*AgentSessionResponse_Directive)(nil),
	}
	file_contracts_proto_control_proto_msgTypes[9].OneofWrappers = []any{
		(*ControlDirective_Node)(nil),
		(*ControlDirective_Agent)(nil),
		(*ControlDirective_Workload)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_contracts_proto_control_proto_rawDesc), len(file_contracts_proto_control_proto_rawDesc)),
			NumEnums:      5,
			NumMessages:   21,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_contracts_proto_control_proto_goTypes,
		DependencyIndexes: file_contracts_proto_control_proto_depIdxs,
		EnumInfos:         file_contracts_proto_control_proto_enumTypes,
		MessageInfos:      file_contracts_proto_control_proto_msgTypes,
	}.Build()
	File_contracts_proto_control_proto = out.File
	file_contracts_proto_control_proto_goTypes = nil
	file_contracts_proto_control_proto_depIdxs = nil
}
