// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v6.33.4
// source: contracts/proto/control.proto

package controlv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AgentControl_Health_FullMethodName   = "/control.v1.AgentControl/Health"
	AgentControl_Register_FullMethodName = "/control.v1.AgentControl/Register"
)

// AgentControlClient is the client API for AgentControl service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// AgentControl defines minimal control-plane handshake operations.
// This is intentionally small and stable for early production rollout.
type AgentControlClient interface {
	// Health is a lightweight readiness/liveness check.
	// Control plane calls this to validate connectivity and agent runtime status.
	Health(ctx context.Context, in *HealthRequest, opts ...grpc.CallOption) (*HealthResponse, error)
	// Register is a startup handshake used to identify agent instance metadata.
	// This is not long-term scheduling yet; it only establishes a trusted baseline.
	Register(ctx context.Context, in *RegisterRequest, opts ...grpc.CallOption) (*RegisterResponse, error)
}

type agentControlClient struct {
	cc grpc.ClientConnInterface
}

func NewAgentControlClient(cc grpc.ClientConnInterface) AgentControlClient {
	return &agentControlClient{cc}
}

func (c *agentControlClient) Health(ctx context.Context, in *HealthRequest, opts ...grpc.CallOption) (*HealthResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HealthResponse)
	err := c.cc.Invoke(ctx, AgentControl_Health_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentControlClient) Register(ctx context.Context, in *RegisterRequest, opts ...grpc.CallOption) (*RegisterResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RegisterResponse)
	err := c.cc.Invoke(ctx, AgentControl_Register_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AgentControlServer is the server API for AgentControl service.
// All implementations must embed UnimplementedAgentControlServer
// for forward compatibility.
//
// AgentControl defines minimal control-plane handshake operations.
// This is intentionally small and stable for early production rollout.
type AgentControlServer interface {
	// Health is a lightweight readiness/liveness check.
	// Control plane calls this to validate connectivity and agent runtime status.
	Health(context.Context, *HealthRequest) (*HealthResponse, error)
	// Register is a startup handshake used to identify agent instance metadata.
	// This is not long-term scheduling yet; it only establishes a trusted baseline.
	Register(context.Context, *RegisterRequest) (*RegisterResponse, error)
	mustEmbedUnimplementedAgentControlServer()
}

// UnimplementedAgentControlServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAgentControlServer struct{}

func (UnimplementedAgentControlServer) Health(context.Context, *HealthRequest) (*HealthResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Health not implemented")
}
func (UnimplementedAgentControlServer) Register(context.Context, *RegisterRequest) (*RegisterResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Register not implemented")
}
func (UnimplementedAgentControlServer) mustEmbedUnimplementedAgentControlServer() {}
func (UnimplementedAgentControlServer) testEmbeddedByValue()                      {}

// UnsafeAgentControlServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AgentControlServer will
// result in compilation errors.
type UnsafeAgentControlServer interface {
	mustEmbedUnimplementedAgentControlServer()
}

func RegisterAgentControlServer(s grpc.ServiceRegistrar, srv AgentControlServer) {
	// If the following call panics, it indicates UnimplementedAgentControlServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AgentControl_ServiceDesc, srv)
}

func _AgentControl_Health_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HealthRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentControlServer).Health(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentControl_Health_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentControlServer).Health(ctx, req.(*HealthRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentControl_Register_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentControlServer).Register(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentControl_Register_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentControlServer).Register(ctx, req.(*RegisterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AgentControl_ServiceDesc is the grpc.ServiceDesc for AgentControl service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AgentControl_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "control.v1.AgentControl",
	HandlerType: (*AgentControlServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Health",
			Handler:    _AgentControl_Health_Handler,
		},
		{
			MethodName: "Register",
			Handler:    _AgentControl_Register_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "contracts/proto/control.proto",
}
