// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: contracts/proto/control/directives.proto

package controlpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// NodeDirectiveType enumerates host-level operations.
type NodeDirectiveType int32

const (
	NodeDirectiveType_NODE_DIRECTIVE_TYPE_UNSPECIFIED NodeDirectiveType = 0
	NodeDirectiveType_NODE_DIRECTIVE_TYPE_DRAIN       NodeDirectiveType = 1 // NODE_DIRECTIVE_TYPE_DRAIN stops new workloads and drains running workloads.
	NodeDirectiveType_NODE_DIRECTIVE_TYPE_RESUME      NodeDirectiveType = 2 // NODE_DIRECTIVE_TYPE_RESUME clears draining state and accepts new workloads.
	NodeDirectiveType_NODE_DIRECTIVE_TYPE_REBOOT      NodeDirectiveType = 3 // NODE_DIRECTIVE_TYPE_REBOOT requests a controlled node reboot.
)

// Enum value maps for NodeDirectiveType.
var (
	NodeDirectiveType_name = map[int32]string{
		0: "NODE_DIRECTIVE_TYPE_UNSPECIFIED",
		1: "NODE_DIRECTIVE_TYPE_DRAIN",
		2: "NODE_DIRECTIVE_TYPE_RESUME",
		3: "NODE_DIRECTIVE_TYPE_REBOOT",
	}
	NodeDirectiveType_value = map[string]int32{
		"NODE_DIRECTIVE_TYPE_UNSPECIFIED": 0,
		"NODE_DIRECTIVE_TYPE_DRAIN":       1,
		"NODE_DIRECTIVE_TYPE_RESUME":      2,
		"NODE_DIRECTIVE_TYPE_REBOOT":      3,
	}
)

func (x NodeDirectiveType) Enum() *NodeDirectiveType {
	p := new(NodeDirectiveType)
	*p = x
	return p
}

func (x NodeDirectiveType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (NodeDirectiveType) Descriptor() protoreflect.EnumDescriptor {
	return file_contracts_proto_control_directives_proto_enumTypes[0].Descriptor()
}

func (NodeDirectiveType) Type() protoreflect.EnumType {
	return &file_contracts_proto_control_directives_proto_enumTypes[0]
}

func (x NodeDirectiveType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use NodeDirectiveType.Descriptor instead.
func (NodeDirectiveType) EnumDescriptor() ([]byte, []int) {
	return file_contracts_proto_control_directives_proto_rawDescGZIP(), []int{0}
}

// AgentDirectiveType enumerates agent process operations.
type AgentDirectiveType int32

const (
	AgentDirectiveType_AGENT_DIRECTIVE_TYPE_UNSPECIFIED AgentDirectiveType = 0
	AgentDirectiveType_AGENT_DIRECTIVE_TYPE_RELOAD      AgentDirectiveType = 1 // AGENT_DIRECTIVE_TYPE_RELOAD requests in-place config/runtime reload.
	AgentDirectiveType_AGENT_DIRECTIVE_TYPE_UPGRADE     AgentDirectiveType = 2 // AGENT_DIRECTIVE_TYPE_UPGRADE requests binary upgrade with verification.
	AgentDirectiveType_AGENT_DIRECTIVE_TYPE_RESTART     AgentDirectiveType = 3 // AGENT_DIRECTIVE_TYPE_RESTART requests controlled process restart.
)

// Enum value maps for AgentDirectiveType.
var (
	AgentDirectiveType_name = map[int32]string{
		0: "AGENT_DIRECTIVE_TYPE_UNSPECIFIED",
		1: "AGENT_DIRECTIVE_TYPE_RELOAD",
		2: "AGENT_DIRECTIVE_TYPE_UPGRADE",
		3: "AGENT_DIRECTIVE_TYPE_RESTART",
	}
	AgentDirectiveType_value = map[string]int32{
		"AGENT_DIRECTIVE_TYPE_UNSPECIFIED": 0,
		"AGENT_DIRECTIVE_TYPE_RELOAD":      1,
		"AGENT_DIRECTIVE_TYPE_UPGRADE":     2,
		"AGENT_DIRECTIVE_TYPE_RESTART":     3,
	}
)

func (x AgentDirectiveType) Enum() *AgentDirectiveType {
	p := new(AgentDirectiveType)
	*p = x
	return p
}

func (x AgentDirectiveType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AgentDirectiveType) Descriptor() protoreflect.EnumDescriptor {
	return file_contracts_proto_control_directives_proto_enumTypes[1].Descriptor()
}

func (AgentDirectiveType) Type() protoreflect.EnumType {
	return &file_contracts_proto_control_directives_proto_enumTypes[1]
}

func (x AgentDirectiveType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AgentDirectiveType.Descriptor instead.
func (AgentDirectiveType) EnumDescriptor() ([]byte, []int) {
	return file_contracts_proto_control_directives_proto_rawDescGZIP(), []int{1}
}

// WorkloadDirectiveType enumerates workload lifecycle operations.
type WorkloadDirectiveType int32

const (
	WorkloadDirectiveType_WORKLOAD_DIRECTIVE_TYPE_UNSPECIFIED WorkloadDirectiveType = 0
	WorkloadDirectiveType_WORKLOAD_DIRECTIVE_TYPE_DEPLOY      WorkloadDirectiveType = 1 // WORKLOAD_DIRECTIVE_TYPE_DEPLOY creates or updates a workload revision.
	WorkloadDirectiveType_WORKLOAD_DIRECTIVE_TYPE_STOP        WorkloadDirectiveType = 2 // WORKLOAD_DIRECTIVE_TYPE_STOP gracefully stops a workload.
	WorkloadDirectiveType_WORKLOAD_DIRECTIVE_TYPE_RESTART     WorkloadDirectiveType = 3 // WORKLOAD_DIRECTIVE_TYPE_RESTART restarts workload processes.
	WorkloadDirectiveType_WORKLOAD_DIRECTIVE_TYPE_SCALE       WorkloadDirectiveType = 4 // WORKLOAD_DIRECTIVE_TYPE_SCALE changes desired workload replicas.
)

// Enum value maps for WorkloadDirectiveType.
var (
	WorkloadDirectiveType_name = map[int32]string{
		0: "WORKLOAD_DIRECTIVE_TYPE_UNSPECIFIED",
		1: "WORKLOAD_DIRECTIVE_TYPE_DEPLOY",
		2: "WORKLOAD_DIRECTIVE_TYPE_STOP",
		3: "WORKLOAD_DIRECTIVE_TYPE_RESTART",
		4: "WORKLOAD_DIRECTIVE_TYPE_SCALE",
	}
	WorkloadDirectiveType_value = map[string]int32{
		"WORKLOAD_DIRECTIVE_TYPE_UNSPECIFIED": 0,
		"WORKLOAD_DIRECTIVE_TYPE_DEPLOY":      1,
		"WORKLOAD_DIRECTIVE_TYPE_STOP":        2,
		"WORKLOAD_DIRECTIVE_TYPE_RESTART":     3,
		"WORKLOAD_DIRECTIVE_TYPE_SCALE":       4,
	}
)

func (x WorkloadDirectiveType) Enum() *WorkloadDirectiveType {
	p := new(WorkloadDirectiveType)
	*p = x
	return p
}

func (x WorkloadDirectiveType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (WorkloadDirectiveType) Descriptor() protoreflect.EnumDescriptor {
	return file_contracts_proto_control_directives_proto_enumTypes[2].Descriptor()
}

func (WorkloadDirectiveType) Type() protoreflect.EnumType {
	return &file_contracts_proto_control_directives_proto_enumTypes[2]
}

func (x WorkloadDirectiveType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use WorkloadDirectiveType.Descriptor instead.
func (WorkloadDirectiveType) EnumDescriptor() ([]byte, []int) {
	return file_contracts_proto_control_directives_proto_rawDescGZIP(), []int{2}
}

// DirectiveResultStatus enumerates final directive execution outcomes.
type DirectiveResultStatus int32

const (
	DirectiveResultStatus_DIRECTIVE_RESULT_STATUS_UNSPECIFIED DirectiveResultStatus = 0
	DirectiveResultStatus_DIRECTIVE_RESULT_STATUS_SUCCEEDED   DirectiveResultStatus = 1
	DirectiveResultStatus_DIRECTIVE_RESULT_STATUS_FAILED      DirectiveResultStatus = 2
	DirectiveResultStatus_DIRECTIVE_RESULT_STATUS_CANCELLED   DirectiveResultStatus = 3
)

// Enum value maps for DirectiveResultStatus.
var (
	DirectiveResultStatus_name = map[int32]string{
		0: "DIRECTIVE_RESULT_STATUS_UNSPECIFIED",
		1: "DIRECTIVE_RESULT_STATUS_SUCCEEDED",
		2: "DIRECTIVE_RESULT_STATUS_FAILED",
		3: "DIRECTIVE_RESULT_STATUS_CANCELLED",
	}
	DirectiveResultStatus_value = map[string]int32{
		"DIRECTIVE_RESULT_STATUS_UNSPECIFIED": 0,
		"DIRECTIVE_RESULT_STATUS_SUCCEEDED":   1,
		"DIRECTIVE_RESULT_STATUS_FAILED":      2,
		"DIRECTIVE_RESULT_STATUS_CANCELLED":   3,
	}
)

func (x DirectiveResultStatus) Enum() *DirectiveResultStatus {
	p := new(DirectiveResultStatus)
	*p = x
	return p
}

func (x DirectiveResultStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DirectiveResultStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_contracts_proto_control_directives_proto_enumTypes[3].Descriptor()
}

func (DirectiveResultStatus) Type() protoreflect.EnumType {
	return &file_contracts_proto_control_directives_proto_enumTypes[3]
}

func (x DirectiveResultStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DirectiveResultStatus.Descriptor instead.
func (DirectiveResultStatus) EnumDescriptor() ([]byte, []int) {
	return file_contracts_proto_control_directives_proto_rawDescGZIP(), []int{3}
}

// NodeDirective carries a single host-level control command.
//
// Keeping the directive metadata directly on this message avoids a second level
// of oneof nesting in generated Go code.
//
// Safety note:
// - NODE_POWEROFF is intentionally excluded in this revision.
type NodeDirective struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	DirectiveId    string                 `protobuf:"bytes,1,opt,name=directive_id,json=directiveId,proto3" json:"directive_id,omitempty"`           // directive_id is a unique id for idempotent processing and audit.
	Reason         string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`                                        // reason provides operator-readable context for the directive.
	EffectiveUnix  int64                  `protobuf:"varint,3,opt,name=effective_unix,json=effectiveUnix,proto3" json:"effective_unix,omitempty"`    // effective_unix is when the directive should be considered active.
	TimeoutSeconds uint32                 `protobuf:"varint,4,opt,name=timeout_seconds,json=timeoutSeconds,proto3" json:"timeout_seconds,omitempty"` // timeout_seconds bounds directive execution before timeout failure is reported.
	Type           NodeDirectiveType      `protobuf:"varint,5,opt,name=type,proto3,enum=control.v1.NodeDirectiveType" json:"type,omitempty"`         // type selects the node operation.
	GraceSeconds   uint32                 `protobuf:"varint,6,opt,name=grace_seconds,json=graceSeconds,proto3" json:"grace_seconds,omitempty"`       // grace_seconds is drain/termination grace for operations that require quiescing.
	Force          bool                   `protobuf:"varint,7,opt,name=force,proto3" json:"force,omitempty"`                                         // force allows emergency execution when graceful constraints cannot be met.
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *NodeDirective) Reset() {
	*x = NodeDirective{}
	mi := &file_contracts_proto_control_directives_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeDirective) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeDirective) ProtoMessage() {}

func (x *NodeDirective) ProtoReflect() protoreflect.Message {
	mi := &file_contracts_proto_control_directives_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeDirective.ProtoReflect.Descriptor instead.
func (*NodeDirective) Descriptor() ([]byte, []int) {
	return file_contracts_proto_control_directives_proto_rawDescGZIP(), []int{0}
}

func (x *NodeDirective) GetDirectiveId() string {
	if x != nil {
		return x.DirectiveId
	}
	return ""
}

func (x *NodeDirective) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *NodeDirective) GetEffectiveUnix() int64 {
	if x != nil {
		return x.EffectiveUnix
	}
	return 0
}

func (x *NodeDirective) GetTimeoutSeconds() uint32 {
	if x != nil {
		return x.TimeoutSeconds
	}
	return 0
}

func (x *NodeDirective) GetType() NodeDirectiveType {
	if x != nil {
		return x.Type
	}
	return NodeDirectiveType_NODE_DIRECTIVE_TYPE_UNSPECIFIED
}

func (x *NodeDirective) GetGraceSeconds() uint32 {
	if x != nil {
		return x.GraceSeconds
	}
	return 0
}

func (x *NodeDirective) GetForce() bool {
	if x != nil {
		return x.Force
	}
	return false
}

// AgentDirective carries a single agent-process control command.
type AgentDirective struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	DirectiveId        string                 `protobuf:"bytes,1,opt,name=directive_id,json=directiveId,proto3" json:"directive_id,omitempty"`                          // directive_id is a unique id for idempotent processing and audit.
	Reason             string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`                                                       // reason provides operator-readable context for the directive.
	EffectiveUnix      int64                  `protobuf:"varint,3,opt,name=effective_unix,json=effectiveUnix,proto3" json:"effective_unix,omitempty"`                   // effective_unix is when the directive should be considered active.
	TimeoutSeconds     uint32                 `protobuf:"varint,4,opt,name=timeout_seconds,json=timeoutSeconds,proto3" json:"timeout_seconds,omitempty"`                // timeout_seconds bounds directive execution before timeout failure is reported.
	Type               AgentDirectiveType     `protobuf:"varint,5,opt,name=type,proto3,enum=control.v1.AgentDirectiveType" json:"type,omitempty"`                       // type selects the agent operation.
	TargetVersion      string                 `protobuf:"bytes,6,opt,name=target_version,json=targetVersion,proto3" json:"target_version,omitempty"`                    // target_version is the desired agent version for upgrade.
	ArtifactUrl        string                 `protobuf:"bytes,7,opt,name=artifact_url,json=artifactUrl,proto3" json:"artifact_url,omitempty"`                          // artifact_url points to the signed upgrade artifact.
	ArtifactSha256     string                 `protobuf:"bytes,8,opt,name=artifact_sha256,json=artifactSha256,proto3" json:"artifact_sha256,omitempty"`                 // artifact_sha256 verifies artifact integrity before install.
	RequireDrain       bool                   `protobuf:"varint,9,opt,name=require_drain,json=requireDrain,proto3" json:"require_drain,omitempty"`                      // require_drain forces node drain before disruptive agent operations.
	RebootAfterUpgrade bool                   `protobuf:"varint,10,opt,name=reboot_after_upgrade,json=rebootAfterUpgrade,proto3" json:"reboot_after_upgrade,omitempty"` // reboot_after_upgrade requests explicit reboot after a successful upgrade.
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *AgentDirective) Reset() {
	*x = AgentDirective{}
	mi := &file_contracts_proto_control_directives_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentDirective) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentDirective) ProtoMessage() {}

func (x *AgentDirective) ProtoReflect() protoreflect.Message {
	mi := &file_contracts_proto_control_directives_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentDirective.ProtoReflect.Descriptor instead.
func (*AgentDirective) Descriptor() ([]byte, []int) {
	return file_contracts_proto_control_directives_proto_rawDescGZIP(), []int{1}
}

func (x *AgentDirective) GetDirectiveId() string {
	if x != nil {
		return x.DirectiveId
	}
	return ""
}

func (x *AgentDirective) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *AgentDirective) GetEffectiveUnix() int64 {
	if x != nil {
		return x.EffectiveUnix
	}
	return 0
}

func (x *AgentDirective) GetTimeoutSeconds() uint32 {
	if x != nil {
		return x.TimeoutSeconds
	}
	return 0
}

func (x *AgentDirective) GetType() AgentDirectiveType {
	if x != nil {
		return x.Type
	}
	return AgentDirectiveType_AGENT_DIRECTIVE_TYPE_UNSPECIFIED
}

func (x *AgentDirective) GetTargetVersion() string {
	if x != nil {
		return x.TargetVersion
	}
	return ""
}

func (x *AgentDirective) GetArtifactUrl() string {
	if x != nil {
		return x.ArtifactUrl
	}
	return ""
}

func (x *AgentDirective) GetArtifactSha256() string {
	if x != nil {
		return x.ArtifactSha256
	}
	return ""
}

func (x *AgentDirective) GetRequireDrain() bool {
	if x != nil {
		return x.RequireDrain
	}
	return false
}

func (x *AgentDirective) GetRebootAfterUpgrade() bool {
	if x != nil {
		return x.RebootAfterUpgrade
	}
	return false
}

// WorkloadDirective carries a single workload/VM control command.
type WorkloadDirective struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	DirectiveId     string                 `protobuf:"bytes,1,opt,name=directive_id,json=directiveId,proto3" json:"directive_id,omitempty"`              // directive_id is a unique id for idempotent processing and audit.
	Reason          string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`                                           // reason provides operator-readable context for the directive.
	EffectiveUnix   int64                  `protobuf:"varint,3,opt,name=effective_unix,json=effectiveUnix,proto3" json:"effective_unix,omitempty"`       // effective_unix is when the directive should be considered active.
	TimeoutSeconds  uint32                 `protobuf:"varint,4,opt,name=timeout_seconds,json=timeoutSeconds,proto3" json:"timeout_seconds,omitempty"`    // timeout_seconds bounds directive execution before timeout failure is reported.
	Type            WorkloadDirectiveType  `protobuf:"varint,5,opt,name=type,proto3,enum=control.v1.WorkloadDirectiveType" json:"type,omitempty"`        // type selects the workload operation.
	WorkloadId      string                 `protobuf:"bytes,6,opt,name=workload_id,json=workloadId,proto3" json:"workload_id,omitempty"`                 // workload_id is the stable control-plane workload identity.
	ImageRef        string                 `protobuf:"bytes,7,opt,name=image_ref,json=imageRef,proto3" json:"image_ref,omitempty"`                       // image_ref identifies the image/artifact for deploy or restart-from-image.
	DesiredReplicas uint32                 `protobuf:"varint,8,opt,name=desired_replicas,json=desiredReplicas,proto3" json:"desired_replicas,omitempty"` // desired_replicas applies to scale operations.
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *WorkloadDirective) Reset() {
	*x = WorkloadDirective{}
	mi := &file_contracts_proto_control_directives_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkloadDirective) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkloadDirective) ProtoMessage() {}

func (x *WorkloadDirective) ProtoReflect() protoreflect.Message {
	mi := &file_contracts_proto_control_directives_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkloadDirective.ProtoReflect.Descriptor instead.
func (*WorkloadDirective) Descriptor() ([]byte, []int) {
	return file_contracts_proto_control_directives_proto_rawDescGZIP(), []int{2}
}

func (x *WorkloadDirective) GetDirectiveId() string {
	if x != nil {
		return x.DirectiveId
	}
	return ""
}

func (x *WorkloadDirective) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *WorkloadDirective) GetEffectiveUnix() int64 {
	if x != nil {
		return x.EffectiveUnix
	}
	return 0
}

func (x *WorkloadDirective) GetTimeoutSeconds() uint32 {
	if x != nil {
		return x.TimeoutSeconds
	}
	return 0
}

func (x *WorkloadDirective) GetType() WorkloadDirectiveType {
	if x != nil {
		return x.Type
	}
	return WorkloadDirectiveType_WORKLOAD_DIRECTIVE_TYPE_UNSPECIFIED
}

func (x *WorkloadDirective) GetWorkloadId() string {
	if x != nil {
		return x.WorkloadId
	}
	return ""
}

func (x *WorkloadDirective) GetImageRef() string {
	if x != nil {
		return x.ImageRef
	}
	return ""
}

func (x *WorkloadDirective) GetDesiredReplicas() uint32 {
	if x != nil {
		return x.DesiredReplicas
	}
	return 0
}

// DirectiveAck reports immediate acceptance/rejection of a directive.
type DirectiveAck struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	DirectiveId      string                 `protobuf:"bytes,1,opt,name=directive_id,json=directiveId,proto3" json:"directive_id,omitempty"`                 // directive_id identifies which control-plane directive this ack references.
	Accepted         bool                   `protobuf:"varint,2,opt,name=accepted,proto3" json:"accepted,omitempty"`                                         // accepted indicates whether directive validation/admission succeeded.
	Message          string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`                                            // message provides a concise accept/reject reason.
	AcknowledgedUnix int64                  `protobuf:"varint,4,opt,name=acknowledged_unix,json=acknowledgedUnix,proto3" json:"acknowledged_unix,omitempty"` // acknowledged_unix is when the directive was acknowledged by the agent.
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *DirectiveAck) Reset() {
	*x = DirectiveAck{}
	mi := &file_contracts_proto_control_directives_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DirectiveAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DirectiveAck) ProtoMessage() {}

func (x *DirectiveAck) ProtoReflect() protoreflect.Message {
	mi := &file_contracts_proto_control_directives_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DirectiveAck.ProtoReflect.Descriptor instead.
func (*DirectiveAck) Descriptor() ([]byte, []int) {
	return file_contracts_proto_control_directives_proto_rawDescGZIP(), []int{3}
}

func (x *DirectiveAck) GetDirectiveId() string {
	if x != nil {
		return x.DirectiveId
	}
	return ""
}

func (x *DirectiveAck) GetAccepted() bool {
	if x != nil {
		return x.Accepted
	}
	return false
}

func (x *DirectiveAck) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *DirectiveAck) GetAcknowledgedUnix() int64 {
	if x != nil {
		return x.AcknowledgedUnix
	}
	return 0
}

// DirectiveProgress reports in-flight execution status for a directive.
type DirectiveProgress struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DirectiveId   string                 `protobuf:"bytes,1,opt,name=directive_id,json=directiveId,proto3" json:"directive_id,omitempty"`  // directive_id identifies which control-plane directive this progress references.
	Phase         string                 `protobuf:"bytes,2,opt,name=phase,proto3" json:"phase,omitempty"`                                 // phase is an implementation-defined state label (for example: "draining", "downloading").
	Percent       uint32                 `protobuf:"varint,3,opt,name=percent,proto3" json:"percent,omitempty"`                            // percent is optional coarse completion percentage in [0, 100].
	Message       string                 `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`                             // message provides operator-readable progress details.
	UpdatedUnix   int64                  `protobuf:"varint,5,opt,name=updated_unix,json=updatedUnix,proto3" json:"updated_unix,omitempty"` // updated_unix is when this progress snapshot was emitted.
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DirectiveProgress) Reset() {
	*x = DirectiveProgress{}
	mi := &file_contracts_proto_control_directives_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DirectiveProgress) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DirectiveProgress) ProtoMessage() {}

func (x *DirectiveProgress) ProtoReflect() protoreflect.Message {
	mi := &file_contracts_proto_control_directives_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DirectiveProgress.ProtoReflect.Descriptor instead.
func (*DirectiveProgress) Descriptor() ([]byte, []int) {
	return file_contracts_proto_control_directives_proto_rawDescGZIP(), []int{4}
}

func (x *DirectiveProgress) GetDirectiveId() string {
	if x != nil {
		return x.DirectiveId
	}
	return ""
}

func (x *DirectiveProgress) GetPhase() string {
	if x != nil {
		return x.Phase
	}
	return ""
}

func (x *DirectiveProgress) GetPercent() uint32 {
	if x != nil {
		return x.Percent
	}
	return 0
}

func (x *DirectiveProgress) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *DirectiveProgress) GetUpdatedUnix() int64 {
	if x != nil {
		return x.UpdatedUnix
	}
	return 0
}

// DirectiveResult reports final completion state for a directive.
type DirectiveResult struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	DirectiveId     string                 `protobuf:"bytes,1,opt,name=directive_id,json=directiveId,proto3" json:"directive_id,omitempty"`              // directive_id identifies which control-plane directive this result references.
	Status          DirectiveResultStatus  `protobuf:"varint,2,opt,name=status,proto3,enum=control.v1.DirectiveResultStatus" json:"status,omitempty"`    // status reports final completion outcome.
	Message         string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`                                         // message provides terminal details, including failure context.
	CompletedUnix   int64                  `protobuf:"varint,4,opt,name=completed_unix,json=completedUnix,proto3" json:"completed_unix,omitempty"`       // completed_unix is when final completion was reached.
	RollbackApplied bool                   `protobuf:"varint,5,opt,name=rollback_applied,json=rollbackApplied,proto3" json:"rollback_applied,omitempty"` // rollback_applied indicates whether rollback logic executed.
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *DirectiveResult) Reset() {
	*x = DirectiveResult{}
	mi := &file_contracts_proto_control_directives_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DirectiveResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DirectiveResult) ProtoMessage() {}

func (x *DirectiveResult) ProtoReflect() protoreflect.Message {
	mi := &file_contracts_proto_control_directives_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DirectiveResult.ProtoReflect.Descriptor instead.
func (*DirectiveResult) Descriptor() ([]byte, []int) {
	return file_contracts_proto_control_directives_proto_rawDescGZIP(), []int{5}
}

func (x *DirectiveResult) GetDirectiveId() string {
	if x != nil {
		return x.DirectiveId
	}
	return ""
}

func (x *DirectiveResult) GetStatus() DirectiveResultStatus {
	if x != nil {
		return x.Status
	}
	return DirectiveResultStatus_DIRECTIVE_RESULT_STATUS_UNSPECIFIED
}

func (x *DirectiveResult) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *DirectiveResult) GetCompletedUnix() int64 {
	if x != nil {
		return x.CompletedUnix
	}
	return 0
}

func (x *DirectiveResult) GetRollbackApplied() bool {
	if x != nil {
		return x.RollbackApplied
	}
	return false
}

var File_contracts_proto_control_directives_proto protoreflect.FileDescriptor

const file_contracts_proto_control_directives_proto_rawDesc = "" +
	"\n" +
	"(contracts/proto/control/directives.proto\x12\n" +
	"control.v1\"\x88\x02\n" +
	"\rNodeDirective\x12!\n" +
	"\fdirective_id\x18\x01 \x01(\tR\vdirectiveId\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\x12%\n" +
	"\x0eeffective_unix\x18\x03 \x01(\x03R\reffectiveUnix\x12'\n" +
	"\x0ftimeout_seconds\x18\x04 \x01(\rR\x0etimeoutSeconds\x121\n" +
	"\x04type\x18\x05 \x01(\x0e2\x1d.control.v1.NodeDirectiveTypeR\x04type\x12#\n" +
	"\rgrace_seconds\x18\x06 \x01(\rR\fgraceSeconds\x12\x14\n" +
	"\x05force\x18\a \x01(\bR\x05force\"\x99\x03\n" +
	"\x0eAgentDirective\x12!\n" +
	"\fdirective_id\x18\x01 \x01(\tR\vdirectiveId\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\x12%\n" +
	"\x0eeffective_unix\x18\x03 \x01(\x03R\reffectiveUnix\x12'\n" +
	"\x0ftimeout_seconds\x18\x04 \x01(\rR\x0etimeoutSeconds\x122\n" +
	"\x04type\x18\x05 \x01(\x0e2\x1e.control.v1.AgentDirectiveTypeR\x04type\x12%\n" +
	"\x0etarget_version\x18\x06 \x01(\tR\rtargetVersion\x12!\n" +
	"\fartifact_url\x18\a \x01(\tR\vartifactUrl\x12'\n" +
	"\x0fartifact_sha256\x18\b \x01(\tR\x0eartifactSha256\x12#\n" +
	"\rrequire_drain\x18\t \x01(\bR\frequireDrain\x120\n" +
	"\x14reboot_after_upgrade\x18\n" +
	" \x01(\bR\x12rebootAfterUpgrade\"\xbe\x02\n" +
	"\x11WorkloadDirective\x12!\n" +
	"\fdirective_id\x18\x01 \x01(\tR\vdirectiveId\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\x12%\n" +
	"\x0eeffective_unix\x18\x03 \x01(\x03R\reffectiveUnix\x12'\n" +
	"\x0ftimeout_seconds\x18\x04 \x01(\rR\x0etimeoutSeconds\x125\n" +
	"\x04type\x18\x05 \x01(\x0e2!.control.v1.WorkloadDirectiveTypeR\x04type\x12\x1f\n" +
	"\vworkload_id\x18\x06 \x01(\tR\n" +
	"workloadId\x12\x1b\n" +
	"\timage_ref\x18\a \x01(\tR\bimageRef\x12)\n" +
	"\x10desired_replicas\x18\b \x01(\rR\x0fdesiredReplicas\"\x94\x01\n" +
	"\fDirectiveAck\x12!\n" +
	"\fdirective_id\x18\x01 \x01(\tR\vdirectiveId\x12\x1a\n" +
	"\baccepted\x18\x02 \x01(\bR\baccepted\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\x12+\n" +
	"\x11acknowledged_unix\x18\x04 \x01(\x03R\x10acknowledgedUnix\"\xa3\x01\n" +
	"\x11DirectiveProgress\x12!\n" +
	"\fdirective_id\x18\x01 \x01(\tR\vdirectiveId\x12\x14\n" +
	"\x05phase\x18\x02 \x01(\tR\x05phase\x12\x18\n" +
	"\apercent\x18\x03 \x01(\rR\apercent\x12\x18\n" +
	"\amessage\x18\x04 \x01(\tR\amessage\x12!\n" +
	"\fupdated_unix\x18\x05 \x01(\x03R\vupdatedUnix\"\xdb\x01\n" +
	"\x0fDirectiveResult\x12!\n" +
	"\fdirective_id\x18\x01 \x01(\tR\vdirectiveId\x129\n" +
	"\x06status\x18\x02 \x01(\x0e2!.control.v1.DirectiveResultStatusR\x06status\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\x12%\n" +
	"\x0ecompleted_unix\x18\x04 \x01(\x03R\rcompletedUnix\x12)\n" +
	"\x10rollback_applied\x18\x05 \x01(\bR\x0frollbackApplied*\x97\x01\n" +
	"\x11NodeDirectiveType\x12#\n" +
	"\x1fNODE_DIRECTIVE_TYPE_UNSPECIFIED\x10\x00\x12\x1d\n" +
	"\x19NODE_DIRECTIVE_TYPE_DRAIN\x10\x01\x12\x1e\n" +
	"\x1aNODE_DIRECTIVE_TYPE_RESUME\x10\x02\x12\x1e\n" +
	"\x1aNODE_DIRECTIVE_TYPE_REBOOT\x10\x03*\x9f\x01\n" +
	"\x12AgentDirectiveType\x12$\n" +
	" AGENT_DIRECTIVE_TYPE_UNSPECIFIED\x10\x00\x12\x1f\n" +
	"\x1bAGENT_DIRECTIVE_TYPE_RELOAD\x10\x01\x12 \n" +
	"\x1cAGENT_DIRECTIVE_TYPE_UPGRADE\x10\x02\x12 \n" +
	"\x1cAGENT_DIRECTIVE_TYPE_RESTART\x10\x03*\xce\x01\n" +
	"\x15WorkloadDirectiveType\x12'\n" +
	"#WORKLOAD_DIRECTIVE_TYPE_UNSPECIFIED\x10\x00\x12\"\n" +
	"\x1eWORKLOAD_DIRECTIVE_TYPE_DEPLOY\x10\x01\x12 \n" +
	"\x1cWORKLOAD_DIRECTIVE_TYPE_STOP\x10\x02\x12#\n" +
	"\x1fWORKLOAD_DIRECTIVE_TYPE_RESTART\x10\x03\x12!\n" +
	"\x1dWORKLOAD_DIRECTIVE_TYPE_SCALE\x10\x04*\xb2\x01\n" +
	"\x15DirectiveResultStatus\x12'\n" +
	"#DIRECTIVE_RESULT_STATUS_UNSPECIFIED\x10\x00\x12%\n" +
	"!DIRECTIVE_RESULT_STATUS_SUCCEEDED\x10\x01\x12\"\n" +
	"\x1eDIRECTIVE_RESULT_STATUS_FAILED\x10\x02\x12%\n" +
	"!DIRECTIVE_RESULT_STATUS_CANCELLED\x10\x03B9Z7github.com/t0gun/spacescale/packages/go/pb/v1;controlpbb\x06proto3"

var (
	file_contracts_proto_control_directives_proto_rawDescOnce sync.Once
	file_contracts_proto_control_directives_proto_rawDescData []byte
)

func file_contracts_proto_control_directives_proto_rawDescGZIP() []byte {
	file_contracts_proto_control_directives_proto_rawDescOnce.Do(func() {
		file_contracts_proto_control_directives_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_contracts_proto_control_directives_proto_rawDesc), len(file_contracts_proto_control_directives_proto_rawDesc)))
	})
	return file_contracts_proto_control_directives_proto_rawDescData
}

var file_contracts_proto_control_directives_proto_enumTypes = make([]protoimpl.EnumInfo, 4)
var file_contracts_proto_control_directives_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_contracts_proto_control_directives_proto_goTypes = []any{
	(NodeDirectiveType)(0),     // 0: control.v1.NodeDirectiveType
	(AgentDirectiveType)(0),    // 1: control.v1.AgentDirectiveType
	(WorkloadDirectiveType)(0), // 2: control.v1.WorkloadDirectiveType
	(DirectiveResultStatus)(0), // 3: control.v1.DirectiveResultStatus
	(*NodeDirective)(nil),      // 4: control.v1.NodeDirective
	(*AgentDirective)(nil),     // 5: control.v1.AgentDirective
	(*WorkloadDirective)(nil),  // 6: control.v1.WorkloadDirective
	(*DirectiveAck)(nil),       // 7: control.v1.DirectiveAck
	(*DirectiveProgress)(nil),  // 8: control.v1.DirectiveProgress
	(*DirectiveResult)(nil),    // 9: control.v1.DirectiveResult
}
var file_contracts_proto_control_directives_proto_depIdxs = []int32{
	0, // 0: control.v1.NodeDirective.type:type_name -> control.v1.NodeDirectiveType
	1, // 1: control.v1.AgentDirective.type:type_name -> control.v1.AgentDirectiveType
	2, // 2: control.v1.WorkloadDirective.type:type_name -> control.v1.WorkloadDirectiveType
	3, // 3: control.v1.DirectiveResult.status:type_name -> control.v1.DirectiveResultStatus
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_contracts_proto_control_directives_proto_init() }
func file_contracts_proto_control_directives_proto_init() {
	if File_contracts_proto_control_directives_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_contracts_proto_control_directives_proto_rawDesc), len(file_contracts_proto_control_directives_proto_rawDesc)),
			NumEnums:      4,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_contracts_proto_control_directives_proto_goTypes,
		DependencyIndexes: file_contracts_proto_control_directives_proto_depIdxs,
		EnumInfos:         file_contracts_proto_control_directives_proto_enumTypes,
		MessageInfos:      file_contracts_proto_control_directives_proto_msgTypes,
	}.Build()
	File_contracts_proto_control_directives_proto = out.File
	file_contracts_proto_control_directives_proto_goTypes = nil
	file_contracts_proto_control_directives_proto_depIdxs = nil
}
