// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v6.33.4
// source: contracts/proto/control/service.proto

package controlpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ControlPlane_Health_FullMethodName          = "/control.v1.ControlPlane/Health"
	ControlPlane_OpenSession_FullMethodName     = "/control.v1.ControlPlane/OpenSession"
	ControlPlane_StreamTelemetry_FullMethodName = "/control.v1.ControlPlane/StreamTelemetry"
	ControlPlane_StreamLogs_FullMethodName      = "/control.v1.ControlPlane/StreamLogs"
)

// ControlPlaneClient is the client API for ControlPlane service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// ControlPlane is the server-side control API that agents dial.
//
// Architecture note:
//   - Agents initiate outbound connections to the control plane.
//   - OpenSession carries ordered control traffic such as registration, heartbeats,
//     directives, and directive lifecycle events.
//   - Bulk telemetry and log traffic move over separate RPCs so noisy reporting
//     does not interfere with directive delivery.
type ControlPlaneClient interface {
	// Health reports control-plane readiness to an agent.
	//
	// This unary method is a fast startup gate before opening OpenSession.
	Health(ctx context.Context, in *HealthRequest, opts ...grpc.CallOption) (*HealthResponse, error)
	// OpenSession establishes the long-lived bidirectional control stream.
	//
	// Protocol invariants:
	// - Agent MUST send RegisterRequest first.
	// - Control plane MUST answer with RegisterResponse before directives.
	// - Agent MUST continue HeartbeatRequest on the negotiated interval.
	// - Agent SHOULD report directive ack/progress/result on the same stream.
	OpenSession(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[AgentSessionRequest, AgentSessionResponse], error)
	// StreamTelemetry ingests bulk node/workload telemetry outside the control
	// session so large reports cannot block heartbeats or directives.
	StreamTelemetry(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[TelemetryEvent, TelemetryStreamSummary], error)
	// StreamLogs ingests batched workload or node logs outside the control
	// session so high-volume log traffic cannot interfere with control messages.
	StreamLogs(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[LogBatch, LogStreamSummary], error)
}

type controlPlaneClient struct {
	cc grpc.ClientConnInterface
}

func NewControlPlaneClient(cc grpc.ClientConnInterface) ControlPlaneClient {
	return &controlPlaneClient{cc}
}

func (c *controlPlaneClient) Health(ctx context.Context, in *HealthRequest, opts ...grpc.CallOption) (*HealthResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HealthResponse)
	err := c.cc.Invoke(ctx, ControlPlane_Health_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controlPlaneClient) OpenSession(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[AgentSessionRequest, AgentSessionResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &ControlPlane_ServiceDesc.Streams[0], ControlPlane_OpenSession_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[AgentSessionRequest, AgentSessionResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ControlPlane_OpenSessionClient = grpc.BidiStreamingClient[AgentSessionRequest, AgentSessionResponse]

func (c *controlPlaneClient) StreamTelemetry(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[TelemetryEvent, TelemetryStreamSummary], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &ControlPlane_ServiceDesc.Streams[1], ControlPlane_StreamTelemetry_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[TelemetryEvent, TelemetryStreamSummary]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ControlPlane_StreamTelemetryClient = grpc.ClientStreamingClient[TelemetryEvent, TelemetryStreamSummary]

func (c *controlPlaneClient) StreamLogs(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[LogBatch, LogStreamSummary], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &ControlPlane_ServiceDesc.Streams[2], ControlPlane_StreamLogs_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[LogBatch, LogStreamSummary]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ControlPlane_StreamLogsClient = grpc.ClientStreamingClient[LogBatch, LogStreamSummary]

// ControlPlaneServer is the server API for ControlPlane service.
// All implementations must embed UnimplementedControlPlaneServer
// for forward compatibility.
//
// ControlPlane is the server-side control API that agents dial.
//
// Architecture note:
//   - Agents initiate outbound connections to the control plane.
//   - OpenSession carries ordered control traffic such as registration, heartbeats,
//     directives, and directive lifecycle events.
//   - Bulk telemetry and log traffic move over separate RPCs so noisy reporting
//     does not interfere with directive delivery.
type ControlPlaneServer interface {
	// Health reports control-plane readiness to an agent.
	//
	// This unary method is a fast startup gate before opening OpenSession.
	Health(context.Context, *HealthRequest) (*HealthResponse, error)
	// OpenSession establishes the long-lived bidirectional control stream.
	//
	// Protocol invariants:
	// - Agent MUST send RegisterRequest first.
	// - Control plane MUST answer with RegisterResponse before directives.
	// - Agent MUST continue HeartbeatRequest on the negotiated interval.
	// - Agent SHOULD report directive ack/progress/result on the same stream.
	OpenSession(grpc.BidiStreamingServer[AgentSessionRequest, AgentSessionResponse]) error
	// StreamTelemetry ingests bulk node/workload telemetry outside the control
	// session so large reports cannot block heartbeats or directives.
	StreamTelemetry(grpc.ClientStreamingServer[TelemetryEvent, TelemetryStreamSummary]) error
	// StreamLogs ingests batched workload or node logs outside the control
	// session so high-volume log traffic cannot interfere with control messages.
	StreamLogs(grpc.ClientStreamingServer[LogBatch, LogStreamSummary]) error
	mustEmbedUnimplementedControlPlaneServer()
}

// UnimplementedControlPlaneServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedControlPlaneServer struct{}

func (UnimplementedControlPlaneServer) Health(context.Context, *HealthRequest) (*HealthResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Health not implemented")
}
func (UnimplementedControlPlaneServer) OpenSession(grpc.BidiStreamingServer[AgentSessionRequest, AgentSessionResponse]) error {
	return status.Error(codes.Unimplemented, "method OpenSession not implemented")
}
func (UnimplementedControlPlaneServer) StreamTelemetry(grpc.ClientStreamingServer[TelemetryEvent, TelemetryStreamSummary]) error {
	return status.Error(codes.Unimplemented, "method StreamTelemetry not implemented")
}
func (UnimplementedControlPlaneServer) StreamLogs(grpc.ClientStreamingServer[LogBatch, LogStreamSummary]) error {
	return status.Error(codes.Unimplemented, "method StreamLogs not implemented")
}
func (UnimplementedControlPlaneServer) mustEmbedUnimplementedControlPlaneServer() {}
func (UnimplementedControlPlaneServer) testEmbeddedByValue()                      {}

// UnsafeControlPlaneServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ControlPlaneServer will
// result in compilation errors.
type UnsafeControlPlaneServer interface {
	mustEmbedUnimplementedControlPlaneServer()
}

func RegisterControlPlaneServer(s grpc.ServiceRegistrar, srv ControlPlaneServer) {
	// If the following call panics, it indicates UnimplementedControlPlaneServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ControlPlane_ServiceDesc, srv)
}

func _ControlPlane_Health_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HealthRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControlPlaneServer).Health(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ControlPlane_Health_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControlPlaneServer).Health(ctx, req.(*HealthRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ControlPlane_OpenSession_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(ControlPlaneServer).OpenSession(&grpc.GenericServerStream[AgentSessionRequest, AgentSessionResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ControlPlane_OpenSessionServer = grpc.BidiStreamingServer[AgentSessionRequest, AgentSessionResponse]

func _ControlPlane_StreamTelemetry_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(ControlPlaneServer).StreamTelemetry(&grpc.GenericServerStream[TelemetryEvent, TelemetryStreamSummary]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ControlPlane_StreamTelemetryServer = grpc.ClientStreamingServer[TelemetryEvent, TelemetryStreamSummary]

func _ControlPlane_StreamLogs_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(ControlPlaneServer).StreamLogs(&grpc.GenericServerStream[LogBatch, LogStreamSummary]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ControlPlane_StreamLogsServer = grpc.ClientStreamingServer[LogBatch, LogStreamSummary]

// ControlPlane_ServiceDesc is the grpc.ServiceDesc for ControlPlane service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ControlPlane_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "control.v1.ControlPlane",
	HandlerType: (*ControlPlaneServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Health",
			Handler:    _ControlPlane_Health_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "OpenSession",
			Handler:       _ControlPlane_OpenSession_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
		{
			StreamName:    "StreamTelemetry",
			Handler:       _ControlPlane_StreamTelemetry_Handler,
			ClientStreams: true,
		},
		{
			StreamName:    "StreamLogs",
			Handler:       _ControlPlane_StreamLogs_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "contracts/proto/control/service.proto",
}
