// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: contracts/proto/control/service.proto

package controlpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_contracts_proto_control_service_proto protoreflect.FileDescriptor

const file_contracts_proto_control_service_proto_rawDesc = "" +
	"\n" +
	"%contracts/proto/control/service.proto\x12\n" +
	"control.v1\x1a\"contracts/proto/control/logs.proto\x1a%contracts/proto/control/session.proto\x1a'contracts/proto/control/telemetry.proto2\xbe\x02\n" +
	"\fControlPlane\x12?\n" +
	"\x06Health\x12\x19.control.v1.HealthRequest\x1a\x1a.control.v1.HealthResponse\x12T\n" +
	"\vOpenSession\x12\x1f.control.v1.AgentSessionRequest\x1a .control.v1.AgentSessionResponse(\x010\x01\x12S\n" +
	"\x0fStreamTelemetry\x12\x1a.control.v1.TelemetryEvent\x1a\".control.v1.TelemetryStreamSummary(\x01\x12B\n" +
	"\n" +
	"StreamLogs\x12\x14.control.v1.LogBatch\x1a\x1c.control.v1.LogStreamSummary(\x01B9Z7github.com/t0gun/spacescale/packages/go/pb/v1;controlpbb\x06proto3"

var file_contracts_proto_control_service_proto_goTypes = []any{
	(*HealthRequest)(nil),          // 0: control.v1.HealthRequest
	(*AgentSessionRequest)(nil),    // 1: control.v1.AgentSessionRequest
	(*TelemetryEvent)(nil),         // 2: control.v1.TelemetryEvent
	(*LogBatch)(nil),               // 3: control.v1.LogBatch
	(*HealthResponse)(nil),         // 4: control.v1.HealthResponse
	(*AgentSessionResponse)(nil),   // 5: control.v1.AgentSessionResponse
	(*TelemetryStreamSummary)(nil), // 6: control.v1.TelemetryStreamSummary
	(*LogStreamSummary)(nil),       // 7: control.v1.LogStreamSummary
}
var file_contracts_proto_control_service_proto_depIdxs = []int32{
	0, // 0: control.v1.ControlPlane.Health:input_type -> control.v1.HealthRequest
	1, // 1: control.v1.ControlPlane.OpenSession:input_type -> control.v1.AgentSessionRequest
	2, // 2: control.v1.ControlPlane.StreamTelemetry:input_type -> control.v1.TelemetryEvent
	3, // 3: control.v1.ControlPlane.StreamLogs:input_type -> control.v1.LogBatch
	4, // 4: control.v1.ControlPlane.Health:output_type -> control.v1.HealthResponse
	5, // 5: control.v1.ControlPlane.OpenSession:output_type -> control.v1.AgentSessionResponse
	6, // 6: control.v1.ControlPlane.StreamTelemetry:output_type -> control.v1.TelemetryStreamSummary
	7, // 7: control.v1.ControlPlane.StreamLogs:output_type -> control.v1.LogStreamSummary
	4, // [4:8] is the sub-list for method output_type
	0, // [0:4] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_contracts_proto_control_service_proto_init() }
func file_contracts_proto_control_service_proto_init() {
	if File_contracts_proto_control_service_proto != nil {
		return
	}
	file_contracts_proto_control_logs_proto_init()
	file_contracts_proto_control_session_proto_init()
	file_contracts_proto_control_telemetry_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_contracts_proto_control_service_proto_rawDesc), len(file_contracts_proto_control_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_contracts_proto_control_service_proto_goTypes,
		DependencyIndexes: file_contracts_proto_control_service_proto_depIdxs,
	}.Build()
	File_contracts_proto_control_service_proto = out.File
	file_contracts_proto_control_service_proto_goTypes = nil
	file_contracts_proto_control_service_proto_depIdxs = nil
}
