// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: contracts/proto/control/session.proto

package controlpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// HealthRequest is the lightweight readiness probe sent before opening the
// long-lived control stream.
type HealthRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"` // request_id is an optional correlation id for distributed tracing.
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthRequest) Reset() {
	*x = HealthRequest{}
	mi := &file_contracts_proto_control_session_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthRequest) ProtoMessage() {}

func (x *HealthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_contracts_proto_control_session_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthRequest.ProtoReflect.Descriptor instead.
func (*HealthRequest) Descriptor() ([]byte, []int) {
	return file_contracts_proto_control_session_proto_rawDescGZIP(), []int{0}
}

func (x *HealthRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

// HealthResponse reports current control-plane status.
type HealthResponse struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	Ok                  bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`                                                               // ok indicates whether the control plane is currently ready.
	Status              string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`                                                        // status is a compact readiness label (for example: "ready", "degraded").
	ControlPlaneVersion string                 `protobuf:"bytes,3,opt,name=control_plane_version,json=controlPlaneVersion,proto3" json:"control_plane_version,omitempty"` // control_plane_version identifies the serving build/version.
	StartedUnix         int64                  `protobuf:"varint,4,opt,name=started_unix,json=startedUnix,proto3" json:"started_unix,omitempty"`                          // started_unix is the control-plane process start time in unix seconds.
	Message             string                 `protobuf:"bytes,5,opt,name=message,proto3" json:"message,omitempty"`                                                      // message provides human-readable details for logs and diagnostics.
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *HealthResponse) Reset() {
	*x = HealthResponse{}
	mi := &file_contracts_proto_control_session_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthResponse) ProtoMessage() {}

func (x *HealthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_contracts_proto_control_session_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthResponse.ProtoReflect.Descriptor instead.
func (*HealthResponse) Descriptor() ([]byte, []int) {
	return file_contracts_proto_control_session_proto_rawDescGZIP(), []int{1}
}

func (x *HealthResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *HealthResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *HealthResponse) GetControlPlaneVersion() string {
	if x != nil {
		return x.ControlPlaneVersion
	}
	return ""
}

func (x *HealthResponse) GetStartedUnix() int64 {
	if x != nil {
		return x.StartedUnix
	}
	return 0
}

func (x *HealthResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// AgentSessionRequest is an envelope for agent-to-control stream events.
// Exactly one event payload should be set per message.
type AgentSessionRequest struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	RequestId string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"` // request_id is optional, may be echoed by responses, and helps stream log correlation.
	// Types that are valid to be assigned to Event:
	//
	//	*AgentSessionRequest_Register
	//	*AgentSessionRequest_Heartbeat
	//	*AgentSessionRequest_DirectiveAck
	//	*AgentSessionRequest_DirectiveProgress
	//	*AgentSessionRequest_DirectiveResult
	Event         isAgentSessionRequest_Event `protobuf_oneof:"event"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentSessionRequest) Reset() {
	*x = AgentSessionRequest{}
	mi := &file_contracts_proto_control_session_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentSessionRequest) ProtoMessage() {}

func (x *AgentSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_contracts_proto_control_session_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentSessionRequest.ProtoReflect.Descriptor instead.
func (*AgentSessionRequest) Descriptor() ([]byte, []int) {
	return file_contracts_proto_control_session_proto_rawDescGZIP(), []int{2}
}

func (x *AgentSessionRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *AgentSessionRequest) GetEvent() isAgentSessionRequest_Event {
	if x != nil {
		return x.Event
	}
	return nil
}

func (x *AgentSessionRequest) GetRegister() *RegisterRequest {
	if x != nil {
		if x, ok := x.Event.(*AgentSessionRequest_Register); ok {
			return x.Register
		}
	}
	return nil
}

func (x *AgentSessionRequest) GetHeartbeat() *HeartbeatRequest {
	if x != nil {
		if x, ok := x.Event.(*AgentSessionRequest_Heartbeat); ok {
			return x.Heartbeat
		}
	}
	return nil
}

func (x *AgentSessionRequest) GetDirectiveAck() *DirectiveAck {
	if x != nil {
		if x, ok := x.Event.(*AgentSessionRequest_DirectiveAck); ok {
			return x.DirectiveAck
		}
	}
	return nil
}

func (x *AgentSessionRequest) GetDirectiveProgress() *DirectiveProgress {
	if x != nil {
		if x, ok := x.Event.(*AgentSessionRequest_DirectiveProgress); ok {
			return x.DirectiveProgress
		}
	}
	return nil
}

func (x *AgentSessionRequest) GetDirectiveResult() *DirectiveResult {
	if x != nil {
		if x, ok := x.Event.(*AgentSessionRequest_DirectiveResult); ok {
			return x.DirectiveResult
		}
	}
	return nil
}

type isAgentSessionRequest_Event interface {
	isAgentSessionRequest_Event()
}

type AgentSessionRequest_Register struct {
	Register *RegisterRequest `protobuf:"bytes,2,opt,name=register,proto3,oneof"` // register starts a new logical control session.
}

type AgentSessionRequest_Heartbeat struct {
	Heartbeat *HeartbeatRequest `protobuf:"bytes,3,opt,name=heartbeat,proto3,oneof"` // heartbeat updates liveness and runtime load signals.
}

type AgentSessionRequest_DirectiveAck struct {
	DirectiveAck *DirectiveAck `protobuf:"bytes,4,opt,name=directive_ack,json=directiveAck,proto3,oneof"` // directive_ack reports immediate accept/reject for a directive.
}

type AgentSessionRequest_DirectiveProgress struct {
	DirectiveProgress *DirectiveProgress `protobuf:"bytes,5,opt,name=directive_progress,json=directiveProgress,proto3,oneof"` // directive_progress reports in-flight execution state.
}

type AgentSessionRequest_DirectiveResult struct {
	DirectiveResult *DirectiveResult `protobuf:"bytes,6,opt,name=directive_result,json=directiveResult,proto3,oneof"` // directive_result reports final directive completion status.
}

func (*AgentSessionRequest_Register) isAgentSessionRequest_Event() {}

func (*AgentSessionRequest_Heartbeat) isAgentSessionRequest_Event() {}

func (*AgentSessionRequest_DirectiveAck) isAgentSessionRequest_Event() {}

func (*AgentSessionRequest_DirectiveProgress) isAgentSessionRequest_Event() {}

func (*AgentSessionRequest_DirectiveResult) isAgentSessionRequest_Event() {}

// AgentSessionResponse is an envelope for control-to-agent stream events.
// Exactly one event payload should be set per message.
type AgentSessionResponse struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	RequestId string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"` // request_id echoes the originating AgentSessionRequest.request_id when present.
	// Types that are valid to be assigned to Event:
	//
	//	*AgentSessionResponse_Register
	//	*AgentSessionResponse_Heartbeat
	//	*AgentSessionResponse_NodeDirective
	//	*AgentSessionResponse_AgentDirective
	//	*AgentSessionResponse_WorkloadDirective
	Event         isAgentSessionResponse_Event `protobuf_oneof:"event"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentSessionResponse) Reset() {
	*x = AgentSessionResponse{}
	mi := &file_contracts_proto_control_session_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentSessionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentSessionResponse) ProtoMessage() {}

func (x *AgentSessionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_contracts_proto_control_session_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentSessionResponse.ProtoReflect.Descriptor instead.
func (*AgentSessionResponse) Descriptor() ([]byte, []int) {
	return file_contracts_proto_control_session_proto_rawDescGZIP(), []int{3}
}

func (x *AgentSessionResponse) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *AgentSessionResponse) GetEvent() isAgentSessionResponse_Event {
	if x != nil {
		return x.Event
	}
	return nil
}

func (x *AgentSessionResponse) GetRegister() *RegisterResponse {
	if x != nil {
		if x, ok := x.Event.(*AgentSessionResponse_Register); ok {
			return x.Register
		}
	}
	return nil
}

func (x *AgentSessionResponse) GetHeartbeat() *HeartbeatResponse {
	if x != nil {
		if x, ok := x.Event.(*AgentSessionResponse_Heartbeat); ok {
			return x.Heartbeat
		}
	}
	return nil
}

func (x *AgentSessionResponse) GetNodeDirective() *NodeDirective {
	if x != nil {
		if x, ok := x.Event.(*AgentSessionResponse_NodeDirective); ok {
			return x.NodeDirective
		}
	}
	return nil
}

func (x *AgentSessionResponse) GetAgentDirective() *AgentDirective {
	if x != nil {
		if x, ok := x.Event.(*AgentSessionResponse_AgentDirective); ok {
			return x.AgentDirective
		}
	}
	return nil
}

func (x *AgentSessionResponse) GetWorkloadDirective() *WorkloadDirective {
	if x != nil {
		if x, ok := x.Event.(*AgentSessionResponse_WorkloadDirective); ok {
			return x.WorkloadDirective
		}
	}
	return nil
}

type isAgentSessionResponse_Event interface {
	isAgentSessionResponse_Event()
}

type AgentSessionResponse_Register struct {
	Register *RegisterResponse `protobuf:"bytes,2,opt,name=register,proto3,oneof"` // register returns accepted identity and heartbeat lease settings.
}

type AgentSessionResponse_Heartbeat struct {
	Heartbeat *HeartbeatResponse `protobuf:"bytes,3,opt,name=heartbeat,proto3,oneof"` // heartbeat acknowledges liveness updates from the agent.
}

type AgentSessionResponse_NodeDirective struct {
	NodeDirective *NodeDirective `protobuf:"bytes,4,opt,name=node_directive,json=nodeDirective,proto3,oneof"` // node_directive carries host-level commands on the main control stream.
}

type AgentSessionResponse_AgentDirective struct {
	AgentDirective *AgentDirective `protobuf:"bytes,5,opt,name=agent_directive,json=agentDirective,proto3,oneof"` // agent_directive carries process-level commands on the main control stream.
}

type AgentSessionResponse_WorkloadDirective struct {
	WorkloadDirective *WorkloadDirective `protobuf:"bytes,6,opt,name=workload_directive,json=workloadDirective,proto3,oneof"` // workload_directive carries workload/VM commands on the main control stream.
}

func (*AgentSessionResponse_Register) isAgentSessionResponse_Event() {}

func (*AgentSessionResponse_Heartbeat) isAgentSessionResponse_Event() {}

func (*AgentSessionResponse_NodeDirective) isAgentSessionResponse_Event() {}

func (*AgentSessionResponse_AgentDirective) isAgentSessionResponse_Event() {}

func (*AgentSessionResponse_WorkloadDirective) isAgentSessionResponse_Event() {}

// RegisterRequest announces agent identity at session start.
//
// Security and stability notes:
// - agent_id should be the previously provisioned UUID returned by RegisterResponse.
// - leave agent_id empty on first boot so the control plane can provision one.
type RegisterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentId       string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`                // agent_id is the canonical control-plane identity for this agent; omit on first boot to request provisioning.
	AgentVersion  string                 `protobuf:"bytes,2,opt,name=agent_version,json=agentVersion,proto3" json:"agent_version,omitempty"` // agent_version identifies the running agent build/version.
	StartedUnix   int64                  `protobuf:"varint,3,opt,name=started_unix,json=startedUnix,proto3" json:"started_unix,omitempty"`   // started_unix is the agent process start time in unix seconds.
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterRequest) Reset() {
	*x = RegisterRequest{}
	mi := &file_contracts_proto_control_session_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterRequest) ProtoMessage() {}

func (x *RegisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_contracts_proto_control_session_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterRequest.ProtoReflect.Descriptor instead.
func (*RegisterRequest) Descriptor() ([]byte, []int) {
	return file_contracts_proto_control_session_proto_rawDescGZIP(), []int{4}
}

func (x *RegisterRequest) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *RegisterRequest) GetAgentVersion() string {
	if x != nil {
		return x.AgentVersion
	}
	return ""
}

func (x *RegisterRequest) GetStartedUnix() int64 {
	if x != nil {
		return x.StartedUnix
	}
	return 0
}

// RegisterResponse communicates registration acceptance and lease policy.
type RegisterResponse struct {
	state                    protoimpl.MessageState `protogen:"open.v1"`
	Accepted                 bool                   `protobuf:"varint,1,opt,name=accepted,proto3" json:"accepted,omitempty"`                                                                   // accepted indicates whether registration is admitted.
	AgentId                  string                 `protobuf:"bytes,2,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`                                                       // agent_id is the canonical control-plane identity for this agent.
	SessionId                string                 `protobuf:"bytes,3,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`                                                 // session_id identifies this stream session for heartbeat correlation.
	HeartbeatIntervalSeconds int64                  `protobuf:"varint,4,opt,name=heartbeat_interval_seconds,json=heartbeatIntervalSeconds,proto3" json:"heartbeat_interval_seconds,omitempty"` // heartbeat_interval_seconds is the expected heartbeat cadence.
	LeaseTtlSeconds          int64                  `protobuf:"varint,5,opt,name=lease_ttl_seconds,json=leaseTtlSeconds,proto3" json:"lease_ttl_seconds,omitempty"`                            // lease_ttl_seconds is the offline cutoff if heartbeats are missed.
	Message                  string                 `protobuf:"bytes,6,opt,name=message,proto3" json:"message,omitempty"`                                                                      // message provides human-readable acceptance or rejection details.
	AgentName                string                 `protobuf:"bytes,7,opt,name=agent_name,json=agentName,proto3" json:"agent_name,omitempty"`                                                 // agent_name is the control-plane assigned display name for this agent.
	unknownFields            protoimpl.UnknownFields
	sizeCache                protoimpl.SizeCache
}

func (x *RegisterResponse) Reset() {
	*x = RegisterResponse{}
	mi := &file_contracts_proto_control_session_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterResponse) ProtoMessage() {}

func (x *RegisterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_contracts_proto_control_session_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterResponse.ProtoReflect.Descriptor instead.
func (*RegisterResponse) Descriptor() ([]byte, []int) {
	return file_contracts_proto_control_session_proto_rawDescGZIP(), []int{5}
}

func (x *RegisterResponse) GetAccepted() bool {
	if x != nil {
		return x.Accepted
	}
	return false
}

func (x *RegisterResponse) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *RegisterResponse) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *RegisterResponse) GetHeartbeatIntervalSeconds() int64 {
	if x != nil {
		return x.HeartbeatIntervalSeconds
	}
	return 0
}

func (x *RegisterResponse) GetLeaseTtlSeconds() int64 {
	if x != nil {
		return x.LeaseTtlSeconds
	}
	return 0
}

func (x *RegisterResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *RegisterResponse) GetAgentName() string {
	if x != nil {
		return x.AgentName
	}
	return ""
}

// HeartbeatRequest updates liveness and runtime pressure for an active session.
type HeartbeatRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	SessionId        string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`                       // session_id must match the RegisterResponse session id.
	SentUnix         int64                  `protobuf:"varint,2,opt,name=sent_unix,json=sentUnix,proto3" json:"sent_unix,omitempty"`                         // sent_unix is when heartbeat was emitted by the agent in unix seconds.
	Status           string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`                                              // status is a compact runtime label (for example: "ready", "draining").
	RunningWorkloads uint32                 `protobuf:"varint,4,opt,name=running_workloads,json=runningWorkloads,proto3" json:"running_workloads,omitempty"` // running_workloads is the count of active workloads.
	QueuedWorkloads  uint32                 `protobuf:"varint,5,opt,name=queued_workloads,json=queuedWorkloads,proto3" json:"queued_workloads,omitempty"`    // queued_workloads is the count of pending workloads.
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *HeartbeatRequest) Reset() {
	*x = HeartbeatRequest{}
	mi := &file_contracts_proto_control_session_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatRequest) ProtoMessage() {}

func (x *HeartbeatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_contracts_proto_control_session_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatRequest.ProtoReflect.Descriptor instead.
func (*HeartbeatRequest) Descriptor() ([]byte, []int) {
	return file_contracts_proto_control_session_proto_rawDescGZIP(), []int{6}
}

func (x *HeartbeatRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *HeartbeatRequest) GetSentUnix() int64 {
	if x != nil {
		return x.SentUnix
	}
	return 0
}

func (x *HeartbeatRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *HeartbeatRequest) GetRunningWorkloads() uint32 {
	if x != nil {
		return x.RunningWorkloads
	}
	return 0
}

func (x *HeartbeatRequest) GetQueuedWorkloads() uint32 {
	if x != nil {
		return x.QueuedWorkloads
	}
	return 0
}

// HeartbeatResponse acknowledges a heartbeat and conveys server time.
type HeartbeatResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`                                   // ok indicates whether heartbeat processing was accepted.
	ServerUnix    int64                  `protobuf:"varint,2,opt,name=server_unix,json=serverUnix,proto3" json:"server_unix,omitempty"` // server_unix is control-plane unix time when heartbeat was handled.
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`                          // message provides optional diagnostics for operators.
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatResponse) Reset() {
	*x = HeartbeatResponse{}
	mi := &file_contracts_proto_control_session_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatResponse) ProtoMessage() {}

func (x *HeartbeatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_contracts_proto_control_session_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatResponse.ProtoReflect.Descriptor instead.
func (*HeartbeatResponse) Descriptor() ([]byte, []int) {
	return file_contracts_proto_control_session_proto_rawDescGZIP(), []int{7}
}

func (x *HeartbeatResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *HeartbeatResponse) GetServerUnix() int64 {
	if x != nil {
		return x.ServerUnix
	}
	return 0
}

func (x *HeartbeatResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_contracts_proto_control_session_proto protoreflect.FileDescriptor

const file_contracts_proto_control_session_proto_rawDesc = "" +
	"\n" +
	"%contracts/proto/control/session.proto\x12\n" +
	"control.v1\x1a(contracts/proto/control/directives.proto\".\n" +
	"\rHealthRequest\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\"\xa9\x01\n" +
	"\x0eHealthResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x122\n" +
	"\x15control_plane_version\x18\x03 \x01(\tR\x13controlPlaneVersion\x12!\n" +
	"\fstarted_unix\x18\x04 \x01(\x03R\vstartedUnix\x12\x18\n" +
	"\amessage\x18\x05 \x01(\tR\amessage\"\x91\x03\n" +
	"\x13AgentSessionRequest\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x129\n" +
	"\bregister\x18\x02 \x01(\v2\x1b.control.v1.RegisterRequestH\x00R\bregister\x12<\n" +
	"\theartbeat\x18\x03 \x01(\v2\x1c.control.v1.HeartbeatRequestH\x00R\theartbeat\x12?\n" +
	"\rdirective_ack\x18\x04 \x01(\v2\x18.control.v1.DirectiveAckH\x00R\fdirectiveAck\x12N\n" +
	"\x12directive_progress\x18\x05 \x01(\v2\x1d.control.v1.DirectiveProgressH\x00R\x11directiveProgress\x12H\n" +
	"\x10directive_result\x18\x06 \x01(\v2\x1b.control.v1.DirectiveResultH\x00R\x0fdirectiveResultB\a\n" +
	"\x05event\"\x94\x03\n" +
	"\x14AgentSessionResponse\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12:\n" +
	"\bregister\x18\x02 \x01(\v2\x1c.control.v1.RegisterResponseH\x00R\bregister\x12=\n" +
	"\theartbeat\x18\x03 \x01(\v2\x1d.control.v1.HeartbeatResponseH\x00R\theartbeat\x12B\n" +
	"\x0enode_directive\x18\x04 \x01(\v2\x19.control.v1.NodeDirectiveH\x00R\rnodeDirective\x12E\n" +
	"\x0fagent_directive\x18\x05 \x01(\v2\x1a.control.v1.AgentDirectiveH\x00R\x0eagentDirective\x12N\n" +
	"\x12workload_directive\x18\x06 \x01(\v2\x1d.control.v1.WorkloadDirectiveH\x00R\x11workloadDirectiveB\a\n" +
	"\x05event\"t\n" +
	"\x0fRegisterRequest\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x12#\n" +
	"\ragent_version\x18\x02 \x01(\tR\fagentVersion\x12!\n" +
	"\fstarted_unix\x18\x03 \x01(\x03R\vstartedUnix\"\x8b\x02\n" +
	"\x10RegisterResponse\x12\x1a\n" +
	"\baccepted\x18\x01 \x01(\bR\baccepted\x12\x19\n" +
	"\bagent_id\x18\x02 \x01(\tR\aagentId\x12\x1d\n" +
	"\n" +
	"session_id\x18\x03 \x01(\tR\tsessionId\x12<\n" +
	"\x1aheartbeat_interval_seconds\x18\x04 \x01(\x03R\x18heartbeatIntervalSeconds\x12*\n" +
	"\x11lease_ttl_seconds\x18\x05 \x01(\x03R\x0fleaseTtlSeconds\x12\x18\n" +
	"\amessage\x18\x06 \x01(\tR\amessage\x12\x1d\n" +
	"\n" +
	"agent_name\x18\a \x01(\tR\tagentName\"\xbe\x01\n" +
	"\x10HeartbeatRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x1b\n" +
	"\tsent_unix\x18\x02 \x01(\x03R\bsentUnix\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\x12+\n" +
	"\x11running_workloads\x18\x04 \x01(\rR\x10runningWorkloads\x12)\n" +
	"\x10queued_workloads\x18\x05 \x01(\rR\x0fqueuedWorkloads\"^\n" +
	"\x11HeartbeatResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\x12\x1f\n" +
	"\vserver_unix\x18\x02 \x01(\x03R\n" +
	"serverUnix\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessageB9Z7github.com/t0gun/spacescale/packages/go/pb/v1;controlpbb\x06proto3"

var (
	file_contracts_proto_control_session_proto_rawDescOnce sync.Once
	file_contracts_proto_control_session_proto_rawDescData []byte
)

func file_contracts_proto_control_session_proto_rawDescGZIP() []byte {
	file_contracts_proto_control_session_proto_rawDescOnce.Do(func() {
		file_contracts_proto_control_session_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_contracts_proto_control_session_proto_rawDesc), len(file_contracts_proto_control_session_proto_rawDesc)))
	})
	return file_contracts_proto_control_session_proto_rawDescData
}

var file_contracts_proto_control_session_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_contracts_proto_control_session_proto_goTypes = []any{
	(*HealthRequest)(nil),        // 0: control.v1.HealthRequest
	(*HealthResponse)(nil),       // 1: control.v1.HealthResponse
	(*AgentSessionRequest)(nil),  // 2: control.v1.AgentSessionRequest
	(*AgentSessionResponse)(nil), // 3: control.v1.AgentSessionResponse
	(*RegisterRequest)(nil),      // 4: control.v1.RegisterRequest
	(*RegisterResponse)(nil),     // 5: control.v1.RegisterResponse
	(*HeartbeatRequest)(nil),     // 6: control.v1.HeartbeatRequest
	(*HeartbeatResponse)(nil),    // 7: control.v1.HeartbeatResponse
	(*DirectiveAck)(nil),         // 8: control.v1.DirectiveAck
	(*DirectiveProgress)(nil),    // 9: control.v1.DirectiveProgress
	(*DirectiveResult)(nil),      // 10: control.v1.DirectiveResult
	(*NodeDirective)(nil),        // 11: control.v1.NodeDirective
	(*AgentDirective)(nil),       // 12: control.v1.AgentDirective
	(*WorkloadDirective)(nil),    // 13: control.v1.WorkloadDirective
}
var file_contracts_proto_control_session_proto_depIdxs = []int32{
	4,  // 0: control.v1.AgentSessionRequest.register:type_name -> control.v1.RegisterRequest
	6,  // 1: control.v1.AgentSessionRequest.heartbeat:type_name -> control.v1.HeartbeatRequest
	8,  // 2: control.v1.AgentSessionRequest.directive_ack:type_name -> control.v1.DirectiveAck
	9,  // 3: control.v1.AgentSessionRequest.directive_progress:type_name -> control.v1.DirectiveProgress
	10, // 4: control.v1.AgentSessionRequest.directive_result:type_name -> control.v1.DirectiveResult
	5,  // 5: control.v1.AgentSessionResponse.register:type_name -> control.v1.RegisterResponse
	7,  // 6: control.v1.AgentSessionResponse.heartbeat:type_name -> control.v1.HeartbeatResponse
	11, // 7: control.v1.AgentSessionResponse.node_directive:type_name -> control.v1.NodeDirective
	12, // 8: control.v1.AgentSessionResponse.agent_directive:type_name -> control.v1.AgentDirective
	13, // 9: control.v1.AgentSessionResponse.workload_directive:type_name -> control.v1.WorkloadDirective
	10, // [10:10] is the sub-list for method output_type
	10, // [10:10] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_contracts_proto_control_session_proto_init() }
func file_contracts_proto_control_session_proto_init() {
	if File_contracts_proto_control_session_proto != nil {
		return
	}
	file_contracts_proto_control_directives_proto_init()
	file_contracts_proto_control_session_proto_msgTypes[2].OneofWrappers = []any{
		(*AgentSessionRequest_Register)(nil),
		(*AgentSessionRequest_Heartbeat)(nil),
		(*AgentSessionRequest_DirectiveAck)(nil),
		(*AgentSessionRequest_DirectiveProgress)(nil),
		(*AgentSessionRequest_DirectiveResult)(nil),
	}
	file_contracts_proto_control_session_proto_msgTypes[3].OneofWrappers = []any{
		(*AgentSessionResponse_Register)(nil),
		(*AgentSessionResponse_Heartbeat)(nil),
		(*AgentSessionResponse_NodeDirective)(nil),
		(*AgentSessionResponse_AgentDirective)(nil),
		(*AgentSessionResponse_WorkloadDirective)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_contracts_proto_control_session_proto_rawDesc), len(file_contracts_proto_control_session_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_contracts_proto_control_session_proto_goTypes,
		DependencyIndexes: file_contracts_proto_control_session_proto_depIdxs,
		MessageInfos:      file_contracts_proto_control_session_proto_msgTypes,
	}.Build()
	File_contracts_proto_control_session_proto = out.File
	file_contracts_proto_control_session_proto_goTypes = nil
	file_contracts_proto_control_session_proto_depIdxs = nil
}
