// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: proto/v1/node.proto

package scalepb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// NodeBootstrapRequest is sent by the 'scaled' daemon on first boot.
// It reports the "Physical Truth" discovered by the hardware probe.
type NodeBootstrapRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	BootstrapToken string                 `protobuf:"bytes,1,opt,name=bootstrap_token,json=bootstrapToken,proto3" json:"bootstrap_token,omitempty"` // one time bootstrap secret baked onto the host
	Version        string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`                                     // daemon version
	BootId         string                 `protobuf:"bytes,3,opt,name=boot_id,json=bootId,proto3" json:"boot_id,omitempty"`                         // boot id to stores ths initial also, if system boots it changes
	TotalThreads   uint32                 `protobuf:"varint,4,opt,name=total_threads,json=totalThreads,proto3" json:"total_threads,omitempty"`      // e.g. 96 From /proc/cpuinfo
	TotalRamMb     uint64                 `protobuf:"varint,5,opt,name=total_ram_mb,json=totalRamMb,proto3" json:"total_ram_mb,omitempty"`          // e.g. 262144 From /proc/meminfo
	TotalDiskMb    uint64                 `protobuf:"varint,6,opt,name=total_disk_mb,json=totalDiskMb,proto3" json:"total_disk_mb,omitempty"`       // Total NVMe space
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *NodeBootstrapRequest) Reset() {
	*x = NodeBootstrapRequest{}
	mi := &file_proto_v1_node_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeBootstrapRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeBootstrapRequest) ProtoMessage() {}

func (x *NodeBootstrapRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_node_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeBootstrapRequest.ProtoReflect.Descriptor instead.
func (*NodeBootstrapRequest) Descriptor() ([]byte, []int) {
	return file_proto_v1_node_proto_rawDescGZIP(), []int{0}
}

func (x *NodeBootstrapRequest) GetBootstrapToken() string {
	if x != nil {
		return x.BootstrapToken
	}
	return ""
}

func (x *NodeBootstrapRequest) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *NodeBootstrapRequest) GetBootId() string {
	if x != nil {
		return x.BootId
	}
	return ""
}

func (x *NodeBootstrapRequest) GetTotalThreads() uint32 {
	if x != nil {
		return x.TotalThreads
	}
	return 0
}

func (x *NodeBootstrapRequest) GetTotalRamMb() uint64 {
	if x != nil {
		return x.TotalRamMb
	}
	return 0
}

func (x *NodeBootstrapRequest) GetTotalDiskMb() uint64 {
	if x != nil {
		return x.TotalDiskMb
	}
	return 0
}

// BootstrapResponse is returned by scalecp after bootstrap to assign identity.
type NodeBootstrapResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"` // permanent daemon identity used in heartbeats
	Region        string                 `protobuf:"bytes,2,opt,name=region,proto3" json:"region,omitempty"`               // region assigned by the control plane
	Error         string                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`                 // optional human readable failure message
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NodeBootstrapResponse) Reset() {
	*x = NodeBootstrapResponse{}
	mi := &file_proto_v1_node_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeBootstrapResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeBootstrapResponse) ProtoMessage() {}

func (x *NodeBootstrapResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_node_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeBootstrapResponse.ProtoReflect.Descriptor instead.
func (*NodeBootstrapResponse) Descriptor() ([]byte, []int) {
	return file_proto_v1_node_proto_rawDescGZIP(), []int{1}
}

func (x *NodeBootstrapResponse) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *NodeBootstrapResponse) GetRegion() string {
	if x != nil {
		return x.Region
	}
	return ""
}

func (x *NodeBootstrapResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type NodeHeartbeat struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// --- IDENTITY & SEQUENCING ---
	NodeId              string `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`                                           // Primary key; maps this pulse to the Postgres inventory.
	SeqNo               uint64 `protobuf:"varint,2,opt,name=seq_no,json=seqNo,proto3" json:"seq_no,omitempty"`                                             // Gap detection; if 10 follows 8, you lost a packet.
	BootId              string `protobuf:"bytes,3,opt,name=boot_id,json=bootId,proto3" json:"boot_id,omitempty"`                                           // if changed without purposeful restart, its probably dead
	SentAtUnixNano      int64  `protobuf:"varint,4,opt,name=sent_at_unix_nano,json=sentAtUnixNano,proto3" json:"sent_at_unix_nano,omitempty"`              // Staleness check; discards heartbeats delayed by network jitter.
	Region              string `protobuf:"bytes,5,opt,name=region,proto3" json:"region,omitempty"`                                                         // Assigned control plane region; keeps scheduling decisions in KV fast.
	SharedVcpuAvailable uint32 `protobuf:"varint,6,opt,name=shared_vcpu_available,json=sharedVcpuAvailable,proto3" json:"shared_vcpu_available,omitempty"` // Starter tier capacity; tracks over-provisioned slots.
	PinnedCpusFree      uint32 `protobuf:"varint,7,opt,name=pinned_cpus_free,json=pinnedCpusFree,proto3" json:"pinned_cpus_free,omitempty"`                // Growth/Scale capacity; ensures dedicated performance.
	AllocatableMemMb    uint64 `protobuf:"varint,8,opt,name=allocatable_mem_mb,json=allocatableMemMb,proto3" json:"allocatable_mem_mb,omitempty"`          // Policy-aware RAM; the "True North" for scheduling room.
	AllocatableDiskMb   uint64 `protobuf:"varint,9,opt,name=allocatable_disk_mb,json=allocatableDiskMb,proto3" json:"allocatable_disk_mb,omitempty"`       // Local SSD budget; prevents "Disk Full" deployment failures.
	ActiveVms           uint32 `protobuf:"varint,10,opt,name=active_vms,json=activeVms,proto3" json:"active_vms,omitempty"`                                // Zombie detection; verifies physical reality vs DB records.
	// --- HEALTH & CONTENTION  ---
	CpuPsiSome_10S    float64 `protobuf:"fixed64,11,opt,name=cpu_psi_some_10s,json=cpuPsiSome10s,proto3" json:"cpu_psi_some_10s,omitempty"`            // The "Suffering" metric; skips nodes where CPU is stalling.
	IoPsiSome_10S     float64 `protobuf:"fixed64,12,opt,name=io_psi_some_10s,json=ioPsiSome10s,proto3" json:"io_psi_some_10s,omitempty"`               // The "NVMe Watcher"; detects failing drives or I/O abuse.
	CpuTempMaxC       float32 `protobuf:"fixed32,13,opt,name=cpu_temp_max_c,json=cpuTempMaxC,proto3" json:"cpu_temp_max_c,omitempty"`                  // Thermal safety; prevents scheduling on melting hardware.
	OomKillsSinceBoot uint32  `protobuf:"varint,14,opt,name=oom_kills_since_boot,json=oomKillsSinceBoot,proto3" json:"oom_kills_since_boot,omitempty"` // Stability audit; increments mean the node is leaking or unstable.
	// --- INTENT & CONNECTIVITY ---
	Status            string `protobuf:"bytes,15,opt,name=status,proto3" json:"status,omitempty"`                                                   // one of ready, draining, offline, cordoned, overheated
	StatusReason      string `protobuf:"bytes,16,opt,name=status_reason,json=statusReason,proto3" json:"status_reason,omitempty"`                   // Only populated when status != ready
	NetworkOk         bool   `protobuf:"varint,17,opt,name=network_ok,json=networkOk,proto3" json:"network_ok,omitempty"`                           // External reachability; node is useless if it's islanded.
	NetUtilizationPct uint32 `protobuf:"varint,18,opt,name=net_utilization_pct,json=netUtilizationPct,proto3" json:"net_utilization_pct,omitempty"` // recent max TX or RX utilization percent of known link capacity
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *NodeHeartbeat) Reset() {
	*x = NodeHeartbeat{}
	mi := &file_proto_v1_node_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeHeartbeat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeHeartbeat) ProtoMessage() {}

func (x *NodeHeartbeat) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_node_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeHeartbeat.ProtoReflect.Descriptor instead.
func (*NodeHeartbeat) Descriptor() ([]byte, []int) {
	return file_proto_v1_node_proto_rawDescGZIP(), []int{2}
}

func (x *NodeHeartbeat) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *NodeHeartbeat) GetSeqNo() uint64 {
	if x != nil {
		return x.SeqNo
	}
	return 0
}

func (x *NodeHeartbeat) GetBootId() string {
	if x != nil {
		return x.BootId
	}
	return ""
}

func (x *NodeHeartbeat) GetSentAtUnixNano() int64 {
	if x != nil {
		return x.SentAtUnixNano
	}
	return 0
}

func (x *NodeHeartbeat) GetRegion() string {
	if x != nil {
		return x.Region
	}
	return ""
}

func (x *NodeHeartbeat) GetSharedVcpuAvailable() uint32 {
	if x != nil {
		return x.SharedVcpuAvailable
	}
	return 0
}

func (x *NodeHeartbeat) GetPinnedCpusFree() uint32 {
	if x != nil {
		return x.PinnedCpusFree
	}
	return 0
}

func (x *NodeHeartbeat) GetAllocatableMemMb() uint64 {
	if x != nil {
		return x.AllocatableMemMb
	}
	return 0
}

func (x *NodeHeartbeat) GetAllocatableDiskMb() uint64 {
	if x != nil {
		return x.AllocatableDiskMb
	}
	return 0
}

func (x *NodeHeartbeat) GetActiveVms() uint32 {
	if x != nil {
		return x.ActiveVms
	}
	return 0
}

func (x *NodeHeartbeat) GetCpuPsiSome_10S() float64 {
	if x != nil {
		return x.CpuPsiSome_10S
	}
	return 0
}

func (x *NodeHeartbeat) GetIoPsiSome_10S() float64 {
	if x != nil {
		return x.IoPsiSome_10S
	}
	return 0
}

func (x *NodeHeartbeat) GetCpuTempMaxC() float32 {
	if x != nil {
		return x.CpuTempMaxC
	}
	return 0
}

func (x *NodeHeartbeat) GetOomKillsSinceBoot() uint32 {
	if x != nil {
		return x.OomKillsSinceBoot
	}
	return 0
}

func (x *NodeHeartbeat) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *NodeHeartbeat) GetStatusReason() string {
	if x != nil {
		return x.StatusReason
	}
	return ""
}

func (x *NodeHeartbeat) GetNetworkOk() bool {
	if x != nil {
		return x.NetworkOk
	}
	return false
}

func (x *NodeHeartbeat) GetNetUtilizationPct() uint32 {
	if x != nil {
		return x.NetUtilizationPct
	}
	return 0
}

var File_proto_v1_node_proto protoreflect.FileDescriptor

const file_proto_v1_node_proto_rawDesc = "" +
	"\n" +
	"\x13proto/v1/node.proto\x12\rspacescale.v1\"\xdd\x01\n" +
	"\x14NodeBootstrapRequest\x12'\n" +
	"\x0fbootstrap_token\x18\x01 \x01(\tR\x0ebootstrapToken\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\x12\x17\n" +
	"\aboot_id\x18\x03 \x01(\tR\x06bootId\x12#\n" +
	"\rtotal_threads\x18\x04 \x01(\rR\ftotalThreads\x12 \n" +
	"\ftotal_ram_mb\x18\x05 \x01(\x04R\n" +
	"totalRamMb\x12\"\n" +
	"\rtotal_disk_mb\x18\x06 \x01(\x04R\vtotalDiskMb\"^\n" +
	"\x15NodeBootstrapResponse\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12\x16\n" +
	"\x06region\x18\x02 \x01(\tR\x06region\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error\"\xa8\x05\n" +
	"\rNodeHeartbeat\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12\x15\n" +
	"\x06seq_no\x18\x02 \x01(\x04R\x05seqNo\x12\x17\n" +
	"\aboot_id\x18\x03 \x01(\tR\x06bootId\x12)\n" +
	"\x11sent_at_unix_nano\x18\x04 \x01(\x03R\x0esentAtUnixNano\x12\x16\n" +
	"\x06region\x18\x05 \x01(\tR\x06region\x122\n" +
	"\x15shared_vcpu_available\x18\x06 \x01(\rR\x13sharedVcpuAvailable\x12(\n" +
	"\x10pinned_cpus_free\x18\a \x01(\rR\x0epinnedCpusFree\x12,\n" +
	"\x12allocatable_mem_mb\x18\b \x01(\x04R\x10allocatableMemMb\x12.\n" +
	"\x13allocatable_disk_mb\x18\t \x01(\x04R\x11allocatableDiskMb\x12\x1d\n" +
	"\n" +
	"active_vms\x18\n" +
	" \x01(\rR\tactiveVms\x12'\n" +
	"\x10cpu_psi_some_10s\x18\v \x01(\x01R\rcpuPsiSome10s\x12%\n" +
	"\x0fio_psi_some_10s\x18\f \x01(\x01R\fioPsiSome10s\x12#\n" +
	"\x0ecpu_temp_max_c\x18\r \x01(\x02R\vcpuTempMaxC\x12/\n" +
	"\x14oom_kills_since_boot\x18\x0e \x01(\rR\x11oomKillsSinceBoot\x12\x16\n" +
	"\x06status\x18\x0f \x01(\tR\x06status\x12#\n" +
	"\rstatus_reason\x18\x10 \x01(\tR\fstatusReason\x12\x1d\n" +
	"\n" +
	"network_ok\x18\x11 \x01(\bR\tnetworkOk\x12.\n" +
	"\x13net_utilization_pct\x18\x12 \x01(\rR\x11netUtilizationPctB:Z8github.com/spacescale/core/internal/shared/pb/v1;scalepbb\x06proto3"

var (
	file_proto_v1_node_proto_rawDescOnce sync.Once
	file_proto_v1_node_proto_rawDescData []byte
)

func file_proto_v1_node_proto_rawDescGZIP() []byte {
	file_proto_v1_node_proto_rawDescOnce.Do(func() {
		file_proto_v1_node_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_v1_node_proto_rawDesc), len(file_proto_v1_node_proto_rawDesc)))
	})
	return file_proto_v1_node_proto_rawDescData
}

var file_proto_v1_node_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_proto_v1_node_proto_goTypes = []any{
	(*NodeBootstrapRequest)(nil),  // 0: spacescale.v1.NodeBootstrapRequest
	(*NodeBootstrapResponse)(nil), // 1: spacescale.v1.NodeBootstrapResponse
	(*NodeHeartbeat)(nil),         // 2: spacescale.v1.NodeHeartbeat
}
var file_proto_v1_node_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_v1_node_proto_init() }
func file_proto_v1_node_proto_init() {
	if File_proto_v1_node_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_v1_node_proto_rawDesc), len(file_proto_v1_node_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_v1_node_proto_goTypes,
		DependencyIndexes: file_proto_v1_node_proto_depIdxs,
		MessageInfos:      file_proto_v1_node_proto_msgTypes,
	}.Build()
	File_proto_v1_node_proto = out.File
	file_proto_v1_node_proto_goTypes = nil
	file_proto_v1_node_proto_depIdxs = nil
}
