// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: proto/v1/workload.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// The abstract service tiers
type Tier int32

const (
	Tier_TIER_UNSPECIFIED Tier = 0
	Tier_TIER_STARTER     Tier = 1 // 2 vCPU / 4 GB (Shared)
	Tier_TIER_GROWTH      Tier = 2 // 4 vCPU / 8 GB (Dedicated/Pinned)
	Tier_TIER_SCALE       Tier = 3 // 8 vCPU / 16 GB (Dedicated/Pinned)
)

// Enum value maps for Tier.
var (
	Tier_name = map[int32]string{
		0: "TIER_UNSPECIFIED",
		1: "TIER_STARTER",
		2: "TIER_GROWTH",
		3: "TIER_SCALE",
	}
	Tier_value = map[string]int32{
		"TIER_UNSPECIFIED": 0,
		"TIER_STARTER":     1,
		"TIER_GROWTH":      2,
		"TIER_SCALE":       3,
	}
)

func (x Tier) Enum() *Tier {
	p := new(Tier)
	*p = x
	return p
}

func (x Tier) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Tier) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_v1_workload_proto_enumTypes[0].Descriptor()
}

func (Tier) Type() protoreflect.EnumType {
	return &file_proto_v1_workload_proto_enumTypes[0]
}

func (x Tier) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Tier.Descriptor instead.
func (Tier) EnumDescriptor() ([]byte, []int) {
	return file_proto_v1_workload_proto_rawDescGZIP(), []int{0}
}

// Broadcast by the CP to all nodes in a region.
// Subject: node.auction.<region>.machine
type AuctionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MachineId     string                 `protobuf:"bytes,1,opt,name=machine_id,json=machineId,proto3" json:"machine_id,omitempty"`
	Tier          Tier                   `protobuf:"varint,2,opt,name=tier,proto3,enum=spacescale.v1.Tier" json:"tier,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuctionRequest) Reset() {
	*x = AuctionRequest{}
	mi := &file_proto_v1_workload_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuctionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuctionRequest) ProtoMessage() {}

func (x *AuctionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_workload_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuctionRequest.ProtoReflect.Descriptor instead.
func (*AuctionRequest) Descriptor() ([]byte, []int) {
	return file_proto_v1_workload_proto_rawDescGZIP(), []int{0}
}

func (x *AuctionRequest) GetMachineId() string {
	if x != nil {
		return x.MachineId
	}
	return ""
}

func (x *AuctionRequest) GetTier() Tier {
	if x != nil {
		return x.Tier
	}
	return Tier_TIER_UNSPECIFIED
}

// Fired back by eligible scaled daemons if they have physical capacity.
// NATS Request-Reply handles the routing back to the CP.
type AuctionReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MachineId     string                 `protobuf:"bytes,1,opt,name=machine_id,json=machineId,proto3" json:"machine_id,omitempty"`    // Correlates the bid to the exact request
	NodeId        string                 `protobuf:"bytes,2,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`             // Permanent daemon identity
	BootId        string                 `protobuf:"bytes,3,opt,name=boot_id,json=bootId,proto3" json:"boot_id,omitempty"`             // Target ID for the subsequent launch command
	FreeRamMb     uint64                 `protobuf:"varint,4,opt,name=free_ram_mb,json=freeRamMb,proto3" json:"free_ram_mb,omitempty"` // The Tie-Breaker: CP picks the emptiest node
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuctionReply) Reset() {
	*x = AuctionReply{}
	mi := &file_proto_v1_workload_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuctionReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuctionReply) ProtoMessage() {}

func (x *AuctionReply) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_workload_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuctionReply.ProtoReflect.Descriptor instead.
func (*AuctionReply) Descriptor() ([]byte, []int) {
	return file_proto_v1_workload_proto_rawDescGZIP(), []int{1}
}

func (x *AuctionReply) GetMachineId() string {
	if x != nil {
		return x.MachineId
	}
	return ""
}

func (x *AuctionReply) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *AuctionReply) GetBootId() string {
	if x != nil {
		return x.BootId
	}
	return ""
}

func (x *AuctionReply) GetFreeRamMb() uint64 {
	if x != nil {
		return x.FreeRamMb
	}
	return 0
}

// Sent directly to the winning node's personal inbox.
// Subject: node.cmd.<boot_id>.machine.launch
type MachineLaunchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MachineId     string                 `protobuf:"bytes,1,opt,name=machine_id,json=machineId,proto3" json:"machine_id,omitempty"`
	Tier          Tier                   `protobuf:"varint,2,opt,name=tier,proto3,enum=spacescale.v1.Tier" json:"tier,omitempty"`
	ImageRef      string                 `protobuf:"bytes,3,opt,name=image_ref,json=imageRef,proto3" json:"image_ref,omitempty"`
	Env           map[string]string      `protobuf:"bytes,4,rep,name=env,proto3" json:"env,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MachineLaunchRequest) Reset() {
	*x = MachineLaunchRequest{}
	mi := &file_proto_v1_workload_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MachineLaunchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MachineLaunchRequest) ProtoMessage() {}

func (x *MachineLaunchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_workload_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MachineLaunchRequest.ProtoReflect.Descriptor instead.
func (*MachineLaunchRequest) Descriptor() ([]byte, []int) {
	return file_proto_v1_workload_proto_rawDescGZIP(), []int{2}
}

func (x *MachineLaunchRequest) GetMachineId() string {
	if x != nil {
		return x.MachineId
	}
	return ""
}

func (x *MachineLaunchRequest) GetTier() Tier {
	if x != nil {
		return x.Tier
	}
	return Tier_TIER_UNSPECIFIED
}

func (x *MachineLaunchRequest) GetImageRef() string {
	if x != nil {
		return x.ImageRef
	}
	return ""
}

func (x *MachineLaunchRequest) GetEnv() map[string]string {
	if x != nil {
		return x.Env
	}
	return nil
}

// Returned by the scaled daemon to acknowledge the launch intent.
type MachineLaunchResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MachineId     string                 `protobuf:"bytes,1,opt,name=machine_id,json=machineId,proto3" json:"machine_id,omitempty"`
	Accepted      bool                   `protobuf:"varint,2,opt,name=accepted,proto3" json:"accepted,omitempty"` // True if the Ghost Reservation was successful
	Status        string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`      // e.g., "starting", "failed"
	ErrorMessage  string                 `protobuf:"bytes,4,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MachineLaunchResponse) Reset() {
	*x = MachineLaunchResponse{}
	mi := &file_proto_v1_workload_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MachineLaunchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MachineLaunchResponse) ProtoMessage() {}

func (x *MachineLaunchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_workload_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MachineLaunchResponse.ProtoReflect.Descriptor instead.
func (*MachineLaunchResponse) Descriptor() ([]byte, []int) {
	return file_proto_v1_workload_proto_rawDescGZIP(), []int{3}
}

func (x *MachineLaunchResponse) GetMachineId() string {
	if x != nil {
		return x.MachineId
	}
	return ""
}

func (x *MachineLaunchResponse) GetAccepted() bool {
	if x != nil {
		return x.Accepted
	}
	return false
}

func (x *MachineLaunchResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *MachineLaunchResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

var File_proto_v1_workload_proto protoreflect.FileDescriptor

const file_proto_v1_workload_proto_rawDesc = "" +
	"\n" +
	"\x17proto/v1/workload.proto\x12\rspacescale.v1\"X\n" +
	"\x0eAuctionRequest\x12\x1d\n" +
	"\n" +
	"machine_id\x18\x01 \x01(\tR\tmachineId\x12'\n" +
	"\x04tier\x18\x02 \x01(\x0e2\x13.spacescale.v1.TierR\x04tier\"\x7f\n" +
	"\fAuctionReply\x12\x1d\n" +
	"\n" +
	"machine_id\x18\x01 \x01(\tR\tmachineId\x12\x17\n" +
	"\anode_id\x18\x02 \x01(\tR\x06nodeId\x12\x17\n" +
	"\aboot_id\x18\x03 \x01(\tR\x06bootId\x12\x1e\n" +
	"\vfree_ram_mb\x18\x04 \x01(\x04R\tfreeRamMb\"\xf3\x01\n" +
	"\x14MachineLaunchRequest\x12\x1d\n" +
	"\n" +
	"machine_id\x18\x01 \x01(\tR\tmachineId\x12'\n" +
	"\x04tier\x18\x02 \x01(\x0e2\x13.spacescale.v1.TierR\x04tier\x12\x1b\n" +
	"\timage_ref\x18\x03 \x01(\tR\bimageRef\x12>\n" +
	"\x03env\x18\x04 \x03(\v2,.spacescale.v1.MachineLaunchRequest.EnvEntryR\x03env\x1a6\n" +
	"\bEnvEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x8f\x01\n" +
	"\x15MachineLaunchResponse\x12\x1d\n" +
	"\n" +
	"machine_id\x18\x01 \x01(\tR\tmachineId\x12\x1a\n" +
	"\baccepted\x18\x02 \x01(\bR\baccepted\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\x12#\n" +
	"\rerror_message\x18\x04 \x01(\tR\ferrorMessage*O\n" +
	"\x04Tier\x12\x14\n" +
	"\x10TIER_UNSPECIFIED\x10\x00\x12\x10\n" +
	"\fTIER_STARTER\x10\x01\x12\x0f\n" +
	"\vTIER_GROWTH\x10\x02\x12\x0e\n" +
	"\n" +
	"TIER_SCALE\x10\x03B5Z3github.com/spacescale/core/internal/shared/pb/v1;pbb\x06proto3"

var (
	file_proto_v1_workload_proto_rawDescOnce sync.Once
	file_proto_v1_workload_proto_rawDescData []byte
)

func file_proto_v1_workload_proto_rawDescGZIP() []byte {
	file_proto_v1_workload_proto_rawDescOnce.Do(func() {
		file_proto_v1_workload_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_v1_workload_proto_rawDesc), len(file_proto_v1_workload_proto_rawDesc)))
	})
	return file_proto_v1_workload_proto_rawDescData
}

var file_proto_v1_workload_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_v1_workload_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_proto_v1_workload_proto_goTypes = []any{
	(Tier)(0),                     // 0: spacescale.v1.Tier
	(*AuctionRequest)(nil),        // 1: spacescale.v1.AuctionRequest
	(*AuctionReply)(nil),          // 2: spacescale.v1.AuctionReply
	(*MachineLaunchRequest)(nil),  // 3: spacescale.v1.MachineLaunchRequest
	(*MachineLaunchResponse)(nil), // 4: spacescale.v1.MachineLaunchResponse
	nil,                           // 5: spacescale.v1.MachineLaunchRequest.EnvEntry
}
var file_proto_v1_workload_proto_depIdxs = []int32{
	0, // 0: spacescale.v1.AuctionRequest.tier:type_name -> spacescale.v1.Tier
	0, // 1: spacescale.v1.MachineLaunchRequest.tier:type_name -> spacescale.v1.Tier
	5, // 2: spacescale.v1.MachineLaunchRequest.env:type_name -> spacescale.v1.MachineLaunchRequest.EnvEntry
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_proto_v1_workload_proto_init() }
func file_proto_v1_workload_proto_init() {
	if File_proto_v1_workload_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_v1_workload_proto_rawDesc), len(file_proto_v1_workload_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_v1_workload_proto_goTypes,
		DependencyIndexes: file_proto_v1_workload_proto_depIdxs,
		EnumInfos:         file_proto_v1_workload_proto_enumTypes,
		MessageInfos:      file_proto_v1_workload_proto_msgTypes,
	}.Build()
	File_proto_v1_workload_proto = out.File
	file_proto_v1_workload_proto_goTypes = nil
	file_proto_v1_workload_proto_depIdxs = nil
}
