// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: proto/v1/workload.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// CpuMode describes how guest CPUs map onto the host.
type CpuMode int32

const (
	CpuMode_CPU_MODE_UNSPECIFIED CpuMode = 0
	CpuMode_CPU_MODE_SHARED      CpuMode = 1
	CpuMode_CPU_MODE_PINNED      CpuMode = 2
)

// Enum value maps for CpuMode.
var (
	CpuMode_name = map[int32]string{
		0: "CPU_MODE_UNSPECIFIED",
		1: "CPU_MODE_SHARED",
		2: "CPU_MODE_PINNED",
	}
	CpuMode_value = map[string]int32{
		"CPU_MODE_UNSPECIFIED": 0,
		"CPU_MODE_SHARED":      1,
		"CPU_MODE_PINNED":      2,
	}
)

func (x CpuMode) Enum() *CpuMode {
	p := new(CpuMode)
	*p = x
	return p
}

func (x CpuMode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CpuMode) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_v1_workload_proto_enumTypes[0].Descriptor()
}

func (CpuMode) Type() protoreflect.EnumType {
	return &file_proto_v1_workload_proto_enumTypes[0]
}

func (x CpuMode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CpuMode.Descriptor instead.
func (CpuMode) EnumDescriptor() ([]byte, []int) {
	return file_proto_v1_workload_proto_rawDescGZIP(), []int{0}
}

// MicroVMShape is the resolved runtime shape sent to the edge.
type MicroVMShape struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Vcpu          uint32                 `protobuf:"varint,1,opt,name=vcpu,proto3" json:"vcpu,omitempty"`
	RamMb         uint64                 `protobuf:"varint,2,opt,name=ram_mb,json=ramMb,proto3" json:"ram_mb,omitempty"`
	CpuMode       CpuMode                `protobuf:"varint,3,opt,name=cpu_mode,json=cpuMode,proto3,enum=spacescale.v1.CpuMode" json:"cpu_mode,omitempty"`
	RootDiskMb    uint64                 `protobuf:"varint,4,opt,name=root_disk_mb,json=rootDiskMb,proto3" json:"root_disk_mb,omitempty"`
	VolumeMb      uint64                 `protobuf:"varint,5,opt,name=volume_mb,json=volumeMb,proto3" json:"volume_mb,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MicroVMShape) Reset() {
	*x = MicroVMShape{}
	mi := &file_proto_v1_workload_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MicroVMShape) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MicroVMShape) ProtoMessage() {}

func (x *MicroVMShape) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_workload_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MicroVMShape.ProtoReflect.Descriptor instead.
func (*MicroVMShape) Descriptor() ([]byte, []int) {
	return file_proto_v1_workload_proto_rawDescGZIP(), []int{0}
}

func (x *MicroVMShape) GetVcpu() uint32 {
	if x != nil {
		return x.Vcpu
	}
	return 0
}

func (x *MicroVMShape) GetRamMb() uint64 {
	if x != nil {
		return x.RamMb
	}
	return 0
}

func (x *MicroVMShape) GetCpuMode() CpuMode {
	if x != nil {
		return x.CpuMode
	}
	return CpuMode_CPU_MODE_UNSPECIFIED
}

func (x *MicroVMShape) GetRootDiskMb() uint64 {
	if x != nil {
		return x.RootDiskMb
	}
	return 0
}

func (x *MicroVMShape) GetVolumeMb() uint64 {
	if x != nil {
		return x.VolumeMb
	}
	return 0
}

// Broadcast by the CP to all nodes in a region.
// Subject: node.auction.<region>.microvm
type AuctionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MicrovmId     string                 `protobuf:"bytes,1,opt,name=microvm_id,json=microvmId,proto3" json:"microvm_id,omitempty"`
	Shape         *MicroVMShape          `protobuf:"bytes,2,opt,name=shape,proto3" json:"shape,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuctionRequest) Reset() {
	*x = AuctionRequest{}
	mi := &file_proto_v1_workload_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuctionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuctionRequest) ProtoMessage() {}

func (x *AuctionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_workload_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuctionRequest.ProtoReflect.Descriptor instead.
func (*AuctionRequest) Descriptor() ([]byte, []int) {
	return file_proto_v1_workload_proto_rawDescGZIP(), []int{1}
}

func (x *AuctionRequest) GetMicrovmId() string {
	if x != nil {
		return x.MicrovmId
	}
	return ""
}

func (x *AuctionRequest) GetShape() *MicroVMShape {
	if x != nil {
		return x.Shape
	}
	return nil
}

// Fired back by eligible scaled daemons if they have physical capacity.
// NATS Request-Reply handles the routing back to the CP.
type AuctionReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MicrovmId     string                 `protobuf:"bytes,1,opt,name=microvm_id,json=microvmId,proto3" json:"microvm_id,omitempty"`    // Correlates the bid to the exact request
	NodeId        string                 `protobuf:"bytes,2,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`             // Permanent daemon identity
	BootId        string                 `protobuf:"bytes,3,opt,name=boot_id,json=bootId,proto3" json:"boot_id,omitempty"`             // Target ID for the subsequent launch command
	FreeRamMb     uint64                 `protobuf:"varint,4,opt,name=free_ram_mb,json=freeRamMb,proto3" json:"free_ram_mb,omitempty"` // The Tie-Breaker: CP picks the emptiest node
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuctionReply) Reset() {
	*x = AuctionReply{}
	mi := &file_proto_v1_workload_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuctionReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuctionReply) ProtoMessage() {}

func (x *AuctionReply) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_workload_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuctionReply.ProtoReflect.Descriptor instead.
func (*AuctionReply) Descriptor() ([]byte, []int) {
	return file_proto_v1_workload_proto_rawDescGZIP(), []int{2}
}

func (x *AuctionReply) GetMicrovmId() string {
	if x != nil {
		return x.MicrovmId
	}
	return ""
}

func (x *AuctionReply) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *AuctionReply) GetBootId() string {
	if x != nil {
		return x.BootId
	}
	return ""
}

func (x *AuctionReply) GetFreeRamMb() uint64 {
	if x != nil {
		return x.FreeRamMb
	}
	return 0
}

// Sent directly to the winning node's personal inbox.
// Subject: node.cmd.<boot_id>.microvm.launch
type MicroVMLaunchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MicrovmId     string                 `protobuf:"bytes,1,opt,name=microvm_id,json=microvmId,proto3" json:"microvm_id,omitempty"`
	Shape         *MicroVMShape          `protobuf:"bytes,2,opt,name=shape,proto3" json:"shape,omitempty"`
	ImageRef      string                 `protobuf:"bytes,3,opt,name=image_ref,json=imageRef,proto3" json:"image_ref,omitempty"`
	Env           map[string]string      `protobuf:"bytes,4,rep,name=env,proto3" json:"env,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	RuntimePort   uint32                 `protobuf:"varint,5,opt,name=runtime_port,json=runtimePort,proto3" json:"runtime_port,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MicroVMLaunchRequest) Reset() {
	*x = MicroVMLaunchRequest{}
	mi := &file_proto_v1_workload_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MicroVMLaunchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MicroVMLaunchRequest) ProtoMessage() {}

func (x *MicroVMLaunchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_workload_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MicroVMLaunchRequest.ProtoReflect.Descriptor instead.
func (*MicroVMLaunchRequest) Descriptor() ([]byte, []int) {
	return file_proto_v1_workload_proto_rawDescGZIP(), []int{3}
}

func (x *MicroVMLaunchRequest) GetMicrovmId() string {
	if x != nil {
		return x.MicrovmId
	}
	return ""
}

func (x *MicroVMLaunchRequest) GetShape() *MicroVMShape {
	if x != nil {
		return x.Shape
	}
	return nil
}

func (x *MicroVMLaunchRequest) GetImageRef() string {
	if x != nil {
		return x.ImageRef
	}
	return ""
}

func (x *MicroVMLaunchRequest) GetEnv() map[string]string {
	if x != nil {
		return x.Env
	}
	return nil
}

func (x *MicroVMLaunchRequest) GetRuntimePort() uint32 {
	if x != nil {
		return x.RuntimePort
	}
	return 0
}

// Returned by the scaled daemon to acknowledge the launch intent.
type MicroVMLaunchResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MicrovmId     string                 `protobuf:"bytes,1,opt,name=microvm_id,json=microvmId,proto3" json:"microvm_id,omitempty"`
	Accepted      bool                   `protobuf:"varint,2,opt,name=accepted,proto3" json:"accepted,omitempty"` // True if the Ghost Reservation was successful
	Status        string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`      // e.g., "starting", "failed"
	ErrorMessage  string                 `protobuf:"bytes,4,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MicroVMLaunchResponse) Reset() {
	*x = MicroVMLaunchResponse{}
	mi := &file_proto_v1_workload_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MicroVMLaunchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MicroVMLaunchResponse) ProtoMessage() {}

func (x *MicroVMLaunchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_workload_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MicroVMLaunchResponse.ProtoReflect.Descriptor instead.
func (*MicroVMLaunchResponse) Descriptor() ([]byte, []int) {
	return file_proto_v1_workload_proto_rawDescGZIP(), []int{4}
}

func (x *MicroVMLaunchResponse) GetMicrovmId() string {
	if x != nil {
		return x.MicrovmId
	}
	return ""
}

func (x *MicroVMLaunchResponse) GetAccepted() bool {
	if x != nil {
		return x.Accepted
	}
	return false
}

func (x *MicroVMLaunchResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *MicroVMLaunchResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

var File_proto_v1_workload_proto protoreflect.FileDescriptor

const file_proto_v1_workload_proto_rawDesc = "" +
	"\n" +
	"\x17proto/v1/workload.proto\x12\rspacescale.v1\"\xab\x01\n" +
	"\fMicroVMShape\x12\x12\n" +
	"\x04vcpu\x18\x01 \x01(\rR\x04vcpu\x12\x15\n" +
	"\x06ram_mb\x18\x02 \x01(\x04R\x05ramMb\x121\n" +
	"\bcpu_mode\x18\x03 \x01(\x0e2\x16.spacescale.v1.CpuModeR\acpuMode\x12 \n" +
	"\froot_disk_mb\x18\x04 \x01(\x04R\n" +
	"rootDiskMb\x12\x1b\n" +
	"\tvolume_mb\x18\x05 \x01(\x04R\bvolumeMb\"b\n" +
	"\x0eAuctionRequest\x12\x1d\n" +
	"\n" +
	"microvm_id\x18\x01 \x01(\tR\tmicrovmId\x121\n" +
	"\x05shape\x18\x02 \x01(\v2\x1b.spacescale.v1.MicroVMShapeR\x05shape\"\x7f\n" +
	"\fAuctionReply\x12\x1d\n" +
	"\n" +
	"microvm_id\x18\x01 \x01(\tR\tmicrovmId\x12\x17\n" +
	"\anode_id\x18\x02 \x01(\tR\x06nodeId\x12\x17\n" +
	"\aboot_id\x18\x03 \x01(\tR\x06bootId\x12\x1e\n" +
	"\vfree_ram_mb\x18\x04 \x01(\x04R\tfreeRamMb\"\xa0\x02\n" +
	"\x14MicroVMLaunchRequest\x12\x1d\n" +
	"\n" +
	"microvm_id\x18\x01 \x01(\tR\tmicrovmId\x121\n" +
	"\x05shape\x18\x02 \x01(\v2\x1b.spacescale.v1.MicroVMShapeR\x05shape\x12\x1b\n" +
	"\timage_ref\x18\x03 \x01(\tR\bimageRef\x12>\n" +
	"\x03env\x18\x04 \x03(\v2,.spacescale.v1.MicroVMLaunchRequest.EnvEntryR\x03env\x12!\n" +
	"\fruntime_port\x18\x05 \x01(\rR\vruntimePort\x1a6\n" +
	"\bEnvEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x8f\x01\n" +
	"\x15MicroVMLaunchResponse\x12\x1d\n" +
	"\n" +
	"microvm_id\x18\x01 \x01(\tR\tmicrovmId\x12\x1a\n" +
	"\baccepted\x18\x02 \x01(\bR\baccepted\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\x12#\n" +
	"\rerror_message\x18\x04 \x01(\tR\ferrorMessage*M\n" +
	"\aCpuMode\x12\x18\n" +
	"\x14CPU_MODE_UNSPECIFIED\x10\x00\x12\x13\n" +
	"\x0fCPU_MODE_SHARED\x10\x01\x12\x13\n" +
	"\x0fCPU_MODE_PINNED\x10\x02B5Z3github.com/spacescale/core/internal/shared/pb/v1;pbb\x06proto3"

var (
	file_proto_v1_workload_proto_rawDescOnce sync.Once
	file_proto_v1_workload_proto_rawDescData []byte
)

func file_proto_v1_workload_proto_rawDescGZIP() []byte {
	file_proto_v1_workload_proto_rawDescOnce.Do(func() {
		file_proto_v1_workload_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_v1_workload_proto_rawDesc), len(file_proto_v1_workload_proto_rawDesc)))
	})
	return file_proto_v1_workload_proto_rawDescData
}

var file_proto_v1_workload_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_v1_workload_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_proto_v1_workload_proto_goTypes = []any{
	(CpuMode)(0),                  // 0: spacescale.v1.CpuMode
	(*MicroVMShape)(nil),          // 1: spacescale.v1.MicroVMShape
	(*AuctionRequest)(nil),        // 2: spacescale.v1.AuctionRequest
	(*AuctionReply)(nil),          // 3: spacescale.v1.AuctionReply
	(*MicroVMLaunchRequest)(nil),  // 4: spacescale.v1.MicroVMLaunchRequest
	(*MicroVMLaunchResponse)(nil), // 5: spacescale.v1.MicroVMLaunchResponse
	nil,                           // 6: spacescale.v1.MicroVMLaunchRequest.EnvEntry
}
var file_proto_v1_workload_proto_depIdxs = []int32{
	0, // 0: spacescale.v1.MicroVMShape.cpu_mode:type_name -> spacescale.v1.CpuMode
	1, // 1: spacescale.v1.AuctionRequest.shape:type_name -> spacescale.v1.MicroVMShape
	1, // 2: spacescale.v1.MicroVMLaunchRequest.shape:type_name -> spacescale.v1.MicroVMShape
	6, // 3: spacescale.v1.MicroVMLaunchRequest.env:type_name -> spacescale.v1.MicroVMLaunchRequest.EnvEntry
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_proto_v1_workload_proto_init() }
func file_proto_v1_workload_proto_init() {
	if File_proto_v1_workload_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_v1_workload_proto_rawDesc), len(file_proto_v1_workload_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_v1_workload_proto_goTypes,
		DependencyIndexes: file_proto_v1_workload_proto_depIdxs,
		EnumInfos:         file_proto_v1_workload_proto_enumTypes,
		MessageInfos:      file_proto_v1_workload_proto_msgTypes,
	}.Build()
	File_proto_v1_workload_proto = out.File
	file_proto_v1_workload_proto_goTypes = nil
	file_proto_v1_workload_proto_depIdxs = nil
}
