import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: ["class"],
  content: [
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "../../packages/ui/src/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        background: "hsl(var(--background))",
        foreground: "hsl(var(--foreground))",
        primary: {
          DEFAULT: "hsl(var(--primary))",
          foreground: "hsl(var(--primary-foreground))",
        },
        secondary: {
          DEFAULT: "hsl(var(--secondary))",
          foreground: "hsl(var(--secondary-foreground))",
        },
        muted: {
          DEFAULT: "hsl(var(--muted))",
          foreground: "hsl(var(--muted-foreground))",
        },
        accent: {
          DEFAULT: "hsl(var(--accent))",
          foreground: "hsl(var(--accent-foreground))",
        },
        destructive: {
          DEFAULT: "hsl(var(--destructive))",
          foreground: "hsl(var(--destructive-foreground))",
        },
        success: {
          DEFAULT: "hsl(var(--success))",
          foreground: "hsl(var(--success-foreground))",
        },
        warning: {
          DEFAULT: "hsl(var(--warning))",
          foreground: "hsl(var(--warning-foreground))",
        },
        "railway-bg": "#0f111a",
        "railway-card": "#181b26",
        "railway-border": "#232836",
        "railway-text": "#cacedb",
        "railway-muted": "#6b7280",
        "digital-blue": "#6366f1",
        "digital-blue-glow": "rgba(99, 102, 241, 0.5)",
        "glow-blue": "#818cf8",
        "off-white": "#e2e4e9",
      },
      borderRadius: {
        lg: "var(--radius)",
        md: "calc(var(--radius) - 2px)",
        sm: "calc(var(--radius) - 4px)",
      },
      fontFamily: {
        display: ["var(--font-display)", "sans-serif"],
        mono: ["var(--font-mono)", "ui-monospace", "monospace"],
      },
      backgroundImage: {
        "square-grid":
          "linear-gradient(to right, rgba(255, 255, 255, 0.03) 1px, transparent 1px), linear-gradient(to bottom, rgba(255, 255, 255, 0.03) 1px, transparent 1px)",
      },
      boxShadow: {
        "glow-blue": "0 0 40px -10px rgba(99, 102, 241, 0.3)",
        glass: "0 8px 32px 0 rgba(0, 0, 0, 0.37)",
      },
      animation: {
        "cursor-main": "cursorMain 32s infinite",
        "view-1": "view1 32s infinite",
        "view-2": "view2 32s infinite",
        "view-2-content": "view2Content 32s infinite",
        "view-2-scan": "view2Scan 32s infinite",
        "view-2-result": "view2Result 32s infinite",
        "view-3": "view3 32s infinite",
        "dash-build": "dashBuild 32s infinite",
        "dash-metrics": "dashMetrics 32s infinite",
        "dash-logs": "dashLogs 32s infinite",
        "dash-settings": "dashSettings 32s infinite",
        "view-4": "view4 32s infinite",
        "progress-fill": "progressFill 32s infinite",
        "term-scroll": "termScroll 32s infinite",
        "tab-highlight": "tabHighlight 32s steps(1, end) infinite",
        "radar-pulse": "radarPulse 3s ease-in-out infinite",
        "wave-flow": "waveFlow 4s linear infinite",
        shimmer: "shimmer 3s linear infinite",
        "infinite-scroll": "infinite-scroll 60s linear infinite",
      },
      keyframes: {
        "infinite-scroll": {
          from: { transform: "translateX(0)" },
          to: { transform: "translateX(-100%)" },
        },
        view1: {
          "0%": { opacity: "0", pointerEvents: "auto", transform: "scale(1)" },
          "1%": { opacity: "1" },
          "9%": { opacity: "1", transform: "scale(1)" },
          "11%": {
            opacity: "0",
            pointerEvents: "none",
            transform: "scale(0.98)",
          },
          "100%": { opacity: "0" },
        },
        view2: {
          "0%, 9%": { opacity: "0", pointerEvents: "none" },
          "11%": { opacity: "1", pointerEvents: "auto" },
          "24%": { opacity: "1" },
          "26%": { opacity: "0", pointerEvents: "none" },
          "100%": { opacity: "0" },
        },
        view2Content: {
          "0%, 13%": { opacity: "1", display: "block" },
          "14%": { opacity: "0", display: "none" },
          "100%": { opacity: "0", display: "none" },
        },
        view2Scan: {
          "0%, 14%": { opacity: "0", display: "none" },
          "14.1%": { opacity: "1", display: "flex" },
          "17%": { opacity: "1" },
          "18.5%": { opacity: "0", display: "none" },
          "100%": { opacity: "0" },
        },
        view2Result: {
          "0%, 17%": {
            opacity: "0",
            display: "none",
            transform: "translateY(10px)",
          },
          "18%": {
            opacity: "1",
            display: "flex",
            transform: "translateY(0)",
          },
          "100%": { opacity: "1", display: "flex" },
        },
        view3: {
          "0%, 24%": { opacity: "0", pointerEvents: "none" },
          "26%": { opacity: "1", pointerEvents: "auto" },
          "86%": { opacity: "1" },
          "88%": { opacity: "0", pointerEvents: "none" },
          "100%": { opacity: "0" },
        },
        dashBuild: {
          "0%, 26%": { opacity: "0", zIndex: "0" },
          "27%, 44%": { opacity: "1", zIndex: "10" },
          "46%": { opacity: "0", zIndex: "0" },
          "100%": { opacity: "0" },
        },
        dashMetrics: {
          "0%, 44%": { opacity: "0", zIndex: "0" },
          "46%, 60%": { opacity: "1", zIndex: "10" },
          "62%": { opacity: "0", zIndex: "0" },
          "100%": { opacity: "0" },
        },
        dashLogs: {
          "0%, 60%": { opacity: "0", zIndex: "0" },
          "62%, 76%": { opacity: "1", zIndex: "10" },
          "78%": { opacity: "0", zIndex: "0" },
          "100%": { opacity: "0" },
        },
        dashSettings: {
          "0%, 76%": { opacity: "0", zIndex: "0" },
          "78%, 86%": { opacity: "1", zIndex: "10" },
          "88%": { opacity: "0", zIndex: "0" },
          "100%": { opacity: "0" },
        },
        view4: {
          "0%, 87%": { opacity: "0", pointerEvents: "none" },
          "89%, 97%": { opacity: "1", pointerEvents: "auto" },
          "99%": { opacity: "0", pointerEvents: "none" },
          "100%": { opacity: "0", pointerEvents: "none" },
        },
        cursorMain: {
          "0%": { opacity: "0", top: "50%", left: "50%" },
          "4%": { opacity: "1" },
          "8%": { top: "12%", left: "88%", transform: "scale(1)" },
          "9%": { transform: "scale(0.9)" },
          "10%": { transform: "scale(1)" },
          "13%": { top: "45%", left: "30%" },
          "14%": { transform: "scale(0.9)" },
          "15%": { transform: "scale(1)" },
          "22%": { top: "55%", left: "65%" },
          "23%": { transform: "scale(0.9)" },
          "24%": { transform: "scale(1)" },
          "38%": { top: "13%", left: "14.5%", transform: "scale(1)" },
          "42%": { transform: "scale(0.9)" },
          "43%": { transform: "scale(1)" },
          "54%": { top: "13%", left: "22.5%", transform: "scale(1)" },
          "58%": { transform: "scale(0.9)" },
          "59%": { transform: "scale(1)" },
          "70%": { top: "13%", left: "30.5%", transform: "scale(1)" },
          "74%": { transform: "scale(0.9)" },
          "75%": { transform: "scale(1)" },
          "86%": { top: "12%", left: "12%" },
          "87%": { transform: "scale(0.9)" },
          "88%": { transform: "scale(1)" },
          "95%": { opacity: "1" },
          "100%": { opacity: "0" },
        },
        progressFill: {
          "0%, 27%": { width: "0%" },
          "30%": { width: "20%" },
          "35%": { width: "60%" },
          "39%, 100%": { width: "100%" },
        },
        termScroll: {
          "0%, 30%": { transform: "translateY(0)" },
          "38%, 100%": { transform: "translateY(-140px)" },
        },
        tabHighlight: {
          "0%, 44%": { left: "16px", width: "66px" },
          "45%, 60%": { left: "98px", width: "58px" },
          "61%, 76%": { left: "172px", width: "45px" },
          "77%, 100%": { left: "233px", width: "65px" },
        },
        radarPulse: {
          "0%, 100%": { opacity: "0.1" },
          "50%": { opacity: "0.3" },
        },
        waveFlow: {
          "0%": { transform: "translateX(0)" },
          "100%": { transform: "translateX(-50%)" },
        },
        shimmer: {
          from: { backgroundPosition: "0 0" },
          to: { backgroundPosition: "-200% 0" },
        },
      },
    },
  },
  plugins: [require("tailwindcss-animate")],
};

export default config;
