// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: contracts/proto/control/logs.proto

package controlpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// LogStream identifies the logical source of a log entry.
type LogStream int32

const (
	LogStream_LOG_STREAM_UNSPECIFIED LogStream = 0
	LogStream_LOG_STREAM_STDOUT      LogStream = 1
	LogStream_LOG_STREAM_STDERR      LogStream = 2
	LogStream_LOG_STREAM_SYSTEM      LogStream = 3
)

// Enum value maps for LogStream.
var (
	LogStream_name = map[int32]string{
		0: "LOG_STREAM_UNSPECIFIED",
		1: "LOG_STREAM_STDOUT",
		2: "LOG_STREAM_STDERR",
		3: "LOG_STREAM_SYSTEM",
	}
	LogStream_value = map[string]int32{
		"LOG_STREAM_UNSPECIFIED": 0,
		"LOG_STREAM_STDOUT":      1,
		"LOG_STREAM_STDERR":      2,
		"LOG_STREAM_SYSTEM":      3,
	}
)

func (x LogStream) Enum() *LogStream {
	p := new(LogStream)
	*p = x
	return p
}

func (x LogStream) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (LogStream) Descriptor() protoreflect.EnumDescriptor {
	return file_contracts_proto_control_logs_proto_enumTypes[0].Descriptor()
}

func (LogStream) Type() protoreflect.EnumType {
	return &file_contracts_proto_control_logs_proto_enumTypes[0]
}

func (x LogStream) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use LogStream.Descriptor instead.
func (LogStream) EnumDescriptor() ([]byte, []int) {
	return file_contracts_proto_control_logs_proto_rawDescGZIP(), []int{0}
}

// LogBatch carries a batch of log lines on the dedicated log-ingest RPC.
type LogBatch struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"` // request_id is optional and helps correlate ingest warnings.
	SessionId     string                 `protobuf:"bytes,2,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"` // session_id identifies the active control session that produced these logs.
	SentUnix      int64                  `protobuf:"varint,3,opt,name=sent_unix,json=sentUnix,proto3" json:"sent_unix,omitempty"`   // sent_unix is when this batch was emitted by the agent.
	Sequence      uint64                 `protobuf:"varint,4,opt,name=sequence,proto3" json:"sequence,omitempty"`                   // sequence is monotonic per session and helps detect dropped batches.
	Entries       []*LogEntry            `protobuf:"bytes,5,rep,name=entries,proto3" json:"entries,omitempty"`                      // entries are the log lines carried in this batch.
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogBatch) Reset() {
	*x = LogBatch{}
	mi := &file_contracts_proto_control_logs_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogBatch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogBatch) ProtoMessage() {}

func (x *LogBatch) ProtoReflect() protoreflect.Message {
	mi := &file_contracts_proto_control_logs_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogBatch.ProtoReflect.Descriptor instead.
func (*LogBatch) Descriptor() ([]byte, []int) {
	return file_contracts_proto_control_logs_proto_rawDescGZIP(), []int{0}
}

func (x *LogBatch) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *LogBatch) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *LogBatch) GetSentUnix() int64 {
	if x != nil {
		return x.SentUnix
	}
	return 0
}

func (x *LogBatch) GetSequence() uint64 {
	if x != nil {
		return x.Sequence
	}
	return 0
}

func (x *LogBatch) GetEntries() []*LogEntry {
	if x != nil {
		return x.Entries
	}
	return nil
}

// LogEntry is one emitted log line or structured message from a node or workload.
type LogEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkloadId    string                 `protobuf:"bytes,1,opt,name=workload_id,json=workloadId,proto3" json:"workload_id,omitempty"`     // workload_id identifies the owning workload when available.
	VmId          string                 `protobuf:"bytes,2,opt,name=vm_id,json=vmId,proto3" json:"vm_id,omitempty"`                       // vm_id identifies the firecracker microVM instance when available.
	Stream        LogStream              `protobuf:"varint,3,opt,name=stream,proto3,enum=control.v1.LogStream" json:"stream,omitempty"`    // stream identifies the logical source such as stdout or stderr.
	Message       string                 `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`                             // message is the emitted log line or structured payload.
	EmittedUnix   int64                  `protobuf:"varint,5,opt,name=emitted_unix,json=emittedUnix,proto3" json:"emitted_unix,omitempty"` // emitted_unix is when this log entry was produced.
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogEntry) Reset() {
	*x = LogEntry{}
	mi := &file_contracts_proto_control_logs_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogEntry) ProtoMessage() {}

func (x *LogEntry) ProtoReflect() protoreflect.Message {
	mi := &file_contracts_proto_control_logs_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogEntry.ProtoReflect.Descriptor instead.
func (*LogEntry) Descriptor() ([]byte, []int) {
	return file_contracts_proto_control_logs_proto_rawDescGZIP(), []int{1}
}

func (x *LogEntry) GetWorkloadId() string {
	if x != nil {
		return x.WorkloadId
	}
	return ""
}

func (x *LogEntry) GetVmId() string {
	if x != nil {
		return x.VmId
	}
	return ""
}

func (x *LogEntry) GetStream() LogStream {
	if x != nil {
		return x.Stream
	}
	return LogStream_LOG_STREAM_UNSPECIFIED
}

func (x *LogEntry) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *LogEntry) GetEmittedUnix() int64 {
	if x != nil {
		return x.EmittedUnix
	}
	return 0
}

// LogStreamSummary reports how many log batches and entries were accepted before
// the stream closed.
type LogStreamSummary struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	AcceptedBatches uint64                 `protobuf:"varint,1,opt,name=accepted_batches,json=acceptedBatches,proto3" json:"accepted_batches,omitempty"` // accepted_batches counts successfully read log batches.
	AcceptedEntries uint64                 `protobuf:"varint,2,opt,name=accepted_entries,json=acceptedEntries,proto3" json:"accepted_entries,omitempty"` // accepted_entries counts successfully read log entries.
	Message         string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`                                         // message provides optional operator-readable ingest details.
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *LogStreamSummary) Reset() {
	*x = LogStreamSummary{}
	mi := &file_contracts_proto_control_logs_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogStreamSummary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogStreamSummary) ProtoMessage() {}

func (x *LogStreamSummary) ProtoReflect() protoreflect.Message {
	mi := &file_contracts_proto_control_logs_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogStreamSummary.ProtoReflect.Descriptor instead.
func (*LogStreamSummary) Descriptor() ([]byte, []int) {
	return file_contracts_proto_control_logs_proto_rawDescGZIP(), []int{2}
}

func (x *LogStreamSummary) GetAcceptedBatches() uint64 {
	if x != nil {
		return x.AcceptedBatches
	}
	return 0
}

func (x *LogStreamSummary) GetAcceptedEntries() uint64 {
	if x != nil {
		return x.AcceptedEntries
	}
	return 0
}

func (x *LogStreamSummary) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_contracts_proto_control_logs_proto protoreflect.FileDescriptor

const file_contracts_proto_control_logs_proto_rawDesc = "" +
	"\n" +
	"\"contracts/proto/control/logs.proto\x12\n" +
	"control.v1\"\xb1\x01\n" +
	"\bLogBatch\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12\x1d\n" +
	"\n" +
	"session_id\x18\x02 \x01(\tR\tsessionId\x12\x1b\n" +
	"\tsent_unix\x18\x03 \x01(\x03R\bsentUnix\x12\x1a\n" +
	"\bsequence\x18\x04 \x01(\x04R\bsequence\x12.\n" +
	"\aentries\x18\x05 \x03(\v2\x14.control.v1.LogEntryR\aentries\"\xac\x01\n" +
	"\bLogEntry\x12\x1f\n" +
	"\vworkload_id\x18\x01 \x01(\tR\n" +
	"workloadId\x12\x13\n" +
	"\x05vm_id\x18\x02 \x01(\tR\x04vmId\x12-\n" +
	"\x06stream\x18\x03 \x01(\x0e2\x15.control.v1.LogStreamR\x06stream\x12\x18\n" +
	"\amessage\x18\x04 \x01(\tR\amessage\x12!\n" +
	"\femitted_unix\x18\x05 \x01(\x03R\vemittedUnix\"\x82\x01\n" +
	"\x10LogStreamSummary\x12)\n" +
	"\x10accepted_batches\x18\x01 \x01(\x04R\x0facceptedBatches\x12)\n" +
	"\x10accepted_entries\x18\x02 \x01(\x04R\x0facceptedEntries\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage*l\n" +
	"\tLogStream\x12\x1a\n" +
	"\x16LOG_STREAM_UNSPECIFIED\x10\x00\x12\x15\n" +
	"\x11LOG_STREAM_STDOUT\x10\x01\x12\x15\n" +
	"\x11LOG_STREAM_STDERR\x10\x02\x12\x15\n" +
	"\x11LOG_STREAM_SYSTEM\x10\x03B9Z7github.com/t0gun/spacescale/packages/go/pb/v1;controlpbb\x06proto3"

var (
	file_contracts_proto_control_logs_proto_rawDescOnce sync.Once
	file_contracts_proto_control_logs_proto_rawDescData []byte
)

func file_contracts_proto_control_logs_proto_rawDescGZIP() []byte {
	file_contracts_proto_control_logs_proto_rawDescOnce.Do(func() {
		file_contracts_proto_control_logs_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_contracts_proto_control_logs_proto_rawDesc), len(file_contracts_proto_control_logs_proto_rawDesc)))
	})
	return file_contracts_proto_control_logs_proto_rawDescData
}

var file_contracts_proto_control_logs_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_contracts_proto_control_logs_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_contracts_proto_control_logs_proto_goTypes = []any{
	(LogStream)(0),           // 0: control.v1.LogStream
	(*LogBatch)(nil),         // 1: control.v1.LogBatch
	(*LogEntry)(nil),         // 2: control.v1.LogEntry
	(*LogStreamSummary)(nil), // 3: control.v1.LogStreamSummary
}
var file_contracts_proto_control_logs_proto_depIdxs = []int32{
	2, // 0: control.v1.LogBatch.entries:type_name -> control.v1.LogEntry
	0, // 1: control.v1.LogEntry.stream:type_name -> control.v1.LogStream
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_contracts_proto_control_logs_proto_init() }
func file_contracts_proto_control_logs_proto_init() {
	if File_contracts_proto_control_logs_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_contracts_proto_control_logs_proto_rawDesc), len(file_contracts_proto_control_logs_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_contracts_proto_control_logs_proto_goTypes,
		DependencyIndexes: file_contracts_proto_control_logs_proto_depIdxs,
		EnumInfos:         file_contracts_proto_control_logs_proto_enumTypes,
		MessageInfos:      file_contracts_proto_control_logs_proto_msgTypes,
	}.Build()
	File_contracts_proto_control_logs_proto = out.File
	file_contracts_proto_control_logs_proto_goTypes = nil
	file_contracts_proto_control_logs_proto_depIdxs = nil
}
