// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.0
// source: proto/v1/models.proto

package spacescalepb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Sent every 5-10 seconds to keep the "Map" updated.
type NodeHeartbeat struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	NodeId          string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	Status          string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`                                           // "ready", "draining", "offline"
	MemoryAvailable uint64                 `protobuf:"varint,3,opt,name=memory_available,json=memoryAvailable,proto3" json:"memory_available,omitempty"` // In Bytes
	CpuUsage        float64                `protobuf:"fixed64,4,opt,name=cpu_usage,json=cpuUsage,proto3" json:"cpu_usage,omitempty"`                     // 0.0 to 1.0
	RunningVms      uint32                 `protobuf:"varint,5,opt,name=running_vms,json=runningVms,proto3" json:"running_vms,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *NodeHeartbeat) Reset() {
	*x = NodeHeartbeat{}
	mi := &file_proto_v1_models_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeHeartbeat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeHeartbeat) ProtoMessage() {}

func (x *NodeHeartbeat) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_models_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeHeartbeat.ProtoReflect.Descriptor instead.
func (*NodeHeartbeat) Descriptor() ([]byte, []int) {
	return file_proto_v1_models_proto_rawDescGZIP(), []int{0}
}

func (x *NodeHeartbeat) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *NodeHeartbeat) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *NodeHeartbeat) GetMemoryAvailable() uint64 {
	if x != nil {
		return x.MemoryAvailable
	}
	return 0
}

func (x *NodeHeartbeat) GetCpuUsage() float64 {
	if x != nil {
		return x.CpuUsage
	}
	return 0
}

func (x *NodeHeartbeat) GetRunningVms() uint32 {
	if x != nil {
		return x.RunningVms
	}
	return 0
}

// Deploy Command is sent to deploy a new application
type DeployCommand struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LeaseId       string                 `protobuf:"bytes,1,opt,name=lease_id,json=leaseId,proto3" json:"lease_id,omitempty"`
	VmId          string                 `protobuf:"bytes,2,opt,name=vm_id,json=vmId,proto3" json:"vm_id,omitempty"`
	ImageUrl      string                 `protobuf:"bytes,3,opt,name=image_url,json=imageUrl,proto3" json:"image_url,omitempty"`
	CpuCores      uint32                 `protobuf:"varint,4,opt,name=cpu_cores,json=cpuCores,proto3" json:"cpu_cores,omitempty"`
	MemoryMb      uint32                 `protobuf:"varint,5,opt,name=memory_mb,json=memoryMb,proto3" json:"memory_mb,omitempty"`
	Env           map[string]string      `protobuf:"bytes,6,rep,name=env,proto3" json:"env,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeployCommand) Reset() {
	*x = DeployCommand{}
	mi := &file_proto_v1_models_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeployCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeployCommand) ProtoMessage() {}

func (x *DeployCommand) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_models_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeployCommand.ProtoReflect.Descriptor instead.
func (*DeployCommand) Descriptor() ([]byte, []int) {
	return file_proto_v1_models_proto_rawDescGZIP(), []int{1}
}

func (x *DeployCommand) GetLeaseId() string {
	if x != nil {
		return x.LeaseId
	}
	return ""
}

func (x *DeployCommand) GetVmId() string {
	if x != nil {
		return x.VmId
	}
	return ""
}

func (x *DeployCommand) GetImageUrl() string {
	if x != nil {
		return x.ImageUrl
	}
	return ""
}

func (x *DeployCommand) GetCpuCores() uint32 {
	if x != nil {
		return x.CpuCores
	}
	return 0
}

func (x *DeployCommand) GetMemoryMb() uint32 {
	if x != nil {
		return x.MemoryMb
	}
	return 0
}

func (x *DeployCommand) GetEnv() map[string]string {
	if x != nil {
		return x.Env
	}
	return nil
}

var File_proto_v1_models_proto protoreflect.FileDescriptor

const file_proto_v1_models_proto_rawDesc = "" +
	"\n" +
	"\x15proto/v1/models.proto\x12\rspacescale.v1\"\xa9\x01\n" +
	"\rNodeHeartbeat\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12)\n" +
	"\x10memory_available\x18\x03 \x01(\x04R\x0fmemoryAvailable\x12\x1b\n" +
	"\tcpu_usage\x18\x04 \x01(\x01R\bcpuUsage\x12\x1f\n" +
	"\vrunning_vms\x18\x05 \x01(\rR\n" +
	"runningVms\"\x87\x02\n" +
	"\rDeployCommand\x12\x19\n" +
	"\blease_id\x18\x01 \x01(\tR\aleaseId\x12\x13\n" +
	"\x05vm_id\x18\x02 \x01(\tR\x04vmId\x12\x1b\n" +
	"\timage_url\x18\x03 \x01(\tR\bimageUrl\x12\x1b\n" +
	"\tcpu_cores\x18\x04 \x01(\rR\bcpuCores\x12\x1b\n" +
	"\tmemory_mb\x18\x05 \x01(\rR\bmemoryMb\x127\n" +
	"\x03env\x18\x06 \x03(\v2%.spacescale.v1.DeployCommand.EnvEntryR\x03env\x1a6\n" +
	"\bEnvEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01B3Z1github.com/spacescale/core/pkg/pb/v1;spacescalepbb\x06proto3"

var (
	file_proto_v1_models_proto_rawDescOnce sync.Once
	file_proto_v1_models_proto_rawDescData []byte
)

func file_proto_v1_models_proto_rawDescGZIP() []byte {
	file_proto_v1_models_proto_rawDescOnce.Do(func() {
		file_proto_v1_models_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_v1_models_proto_rawDesc), len(file_proto_v1_models_proto_rawDesc)))
	})
	return file_proto_v1_models_proto_rawDescData
}

var file_proto_v1_models_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_proto_v1_models_proto_goTypes = []any{
	(*NodeHeartbeat)(nil), // 0: spacescale.v1.NodeHeartbeat
	(*DeployCommand)(nil), // 1: spacescale.v1.DeployCommand
	nil,                   // 2: spacescale.v1.DeployCommand.EnvEntry
}
var file_proto_v1_models_proto_depIdxs = []int32{
	2, // 0: spacescale.v1.DeployCommand.env:type_name -> spacescale.v1.DeployCommand.EnvEntry
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_v1_models_proto_init() }
func file_proto_v1_models_proto_init() {
	if File_proto_v1_models_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_v1_models_proto_rawDesc), len(file_proto_v1_models_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_v1_models_proto_goTypes,
		DependencyIndexes: file_proto_v1_models_proto_depIdxs,
		MessageInfos:      file_proto_v1_models_proto_msgTypes,
	}.Build()
	File_proto_v1_models_proto = out.File
	file_proto_v1_models_proto_goTypes = nil
	file_proto_v1_models_proto_depIdxs = nil
}
