// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: contracts/proto/control/telemetry.proto

package controlpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// WorkloadRuntimeState enumerates per-workload lifecycle states reported by the agent.
type WorkloadRuntimeState int32

const (
	WorkloadRuntimeState_WORKLOAD_RUNTIME_STATE_UNSPECIFIED WorkloadRuntimeState = 0
	WorkloadRuntimeState_WORKLOAD_RUNTIME_STATE_PENDING     WorkloadRuntimeState = 1 // WORKLOAD_RUNTIME_STATE_PENDING means workload resources are not ready yet.
	WorkloadRuntimeState_WORKLOAD_RUNTIME_STATE_STARTING    WorkloadRuntimeState = 2 // WORKLOAD_RUNTIME_STATE_STARTING means workload startup is in progress.
	WorkloadRuntimeState_WORKLOAD_RUNTIME_STATE_RUNNING     WorkloadRuntimeState = 3 // WORKLOAD_RUNTIME_STATE_RUNNING means workload is healthy and serving.
	WorkloadRuntimeState_WORKLOAD_RUNTIME_STATE_DRAINING    WorkloadRuntimeState = 4 // WORKLOAD_RUNTIME_STATE_DRAINING means workload is finishing in-flight work.
	WorkloadRuntimeState_WORKLOAD_RUNTIME_STATE_STOPPED     WorkloadRuntimeState = 5 // WORKLOAD_RUNTIME_STATE_STOPPED means workload is intentionally not running.
	WorkloadRuntimeState_WORKLOAD_RUNTIME_STATE_FAILED      WorkloadRuntimeState = 6 // WORKLOAD_RUNTIME_STATE_FAILED means workload reached terminal failure.
)

// Enum value maps for WorkloadRuntimeState.
var (
	WorkloadRuntimeState_name = map[int32]string{
		0: "WORKLOAD_RUNTIME_STATE_UNSPECIFIED",
		1: "WORKLOAD_RUNTIME_STATE_PENDING",
		2: "WORKLOAD_RUNTIME_STATE_STARTING",
		3: "WORKLOAD_RUNTIME_STATE_RUNNING",
		4: "WORKLOAD_RUNTIME_STATE_DRAINING",
		5: "WORKLOAD_RUNTIME_STATE_STOPPED",
		6: "WORKLOAD_RUNTIME_STATE_FAILED",
	}
	WorkloadRuntimeState_value = map[string]int32{
		"WORKLOAD_RUNTIME_STATE_UNSPECIFIED": 0,
		"WORKLOAD_RUNTIME_STATE_PENDING":     1,
		"WORKLOAD_RUNTIME_STATE_STARTING":    2,
		"WORKLOAD_RUNTIME_STATE_RUNNING":     3,
		"WORKLOAD_RUNTIME_STATE_DRAINING":    4,
		"WORKLOAD_RUNTIME_STATE_STOPPED":     5,
		"WORKLOAD_RUNTIME_STATE_FAILED":      6,
	}
)

func (x WorkloadRuntimeState) Enum() *WorkloadRuntimeState {
	p := new(WorkloadRuntimeState)
	*p = x
	return p
}

func (x WorkloadRuntimeState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (WorkloadRuntimeState) Descriptor() protoreflect.EnumDescriptor {
	return file_contracts_proto_control_telemetry_proto_enumTypes[0].Descriptor()
}

func (WorkloadRuntimeState) Type() protoreflect.EnumType {
	return &file_contracts_proto_control_telemetry_proto_enumTypes[0]
}

func (x WorkloadRuntimeState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use WorkloadRuntimeState.Descriptor instead.
func (WorkloadRuntimeState) EnumDescriptor() ([]byte, []int) {
	return file_contracts_proto_control_telemetry_proto_rawDescGZIP(), []int{0}
}

// TelemetryEvent is the envelope for bulk node/workload telemetry sent on the
// dedicated telemetry RPC.
type TelemetryEvent struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	RequestId string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"` // request_id is optional and helps correlate ingest warnings.
	// Types that are valid to be assigned to Event:
	//
	//	*TelemetryEvent_NodeHealth
	//	*TelemetryEvent_WorkloadsReport
	Event         isTelemetryEvent_Event `protobuf_oneof:"event"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TelemetryEvent) Reset() {
	*x = TelemetryEvent{}
	mi := &file_contracts_proto_control_telemetry_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TelemetryEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TelemetryEvent) ProtoMessage() {}

func (x *TelemetryEvent) ProtoReflect() protoreflect.Message {
	mi := &file_contracts_proto_control_telemetry_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TelemetryEvent.ProtoReflect.Descriptor instead.
func (*TelemetryEvent) Descriptor() ([]byte, []int) {
	return file_contracts_proto_control_telemetry_proto_rawDescGZIP(), []int{0}
}

func (x *TelemetryEvent) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *TelemetryEvent) GetEvent() isTelemetryEvent_Event {
	if x != nil {
		return x.Event
	}
	return nil
}

func (x *TelemetryEvent) GetNodeHealth() *NodeHealthReport {
	if x != nil {
		if x, ok := x.Event.(*TelemetryEvent_NodeHealth); ok {
			return x.NodeHealth
		}
	}
	return nil
}

func (x *TelemetryEvent) GetWorkloadsReport() *WorkloadsReport {
	if x != nil {
		if x, ok := x.Event.(*TelemetryEvent_WorkloadsReport); ok {
			return x.WorkloadsReport
		}
	}
	return nil
}

type isTelemetryEvent_Event interface {
	isTelemetryEvent_Event()
}

type TelemetryEvent_NodeHealth struct {
	NodeHealth *NodeHealthReport `protobuf:"bytes,2,opt,name=node_health,json=nodeHealth,proto3,oneof"` // node_health reports machine-level resource and health telemetry.
}

type TelemetryEvent_WorkloadsReport struct {
	WorkloadsReport *WorkloadsReport `protobuf:"bytes,3,opt,name=workloads_report,json=workloadsReport,proto3,oneof"` // workloads_report reports per-workload runtime telemetry for scheduling and operations.
}

func (*TelemetryEvent_NodeHealth) isTelemetryEvent_Event() {}

func (*TelemetryEvent_WorkloadsReport) isTelemetryEvent_Event() {}

// TelemetryStreamSummary reports how many telemetry events were accepted before
// the stream closed.
type TelemetryStreamSummary struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	AcceptedEvents uint64                 `protobuf:"varint,1,opt,name=accepted_events,json=acceptedEvents,proto3" json:"accepted_events,omitempty"` // accepted_events counts successfully read telemetry frames.
	Message        string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`                                      // message provides optional operator-readable ingest details.
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *TelemetryStreamSummary) Reset() {
	*x = TelemetryStreamSummary{}
	mi := &file_contracts_proto_control_telemetry_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TelemetryStreamSummary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TelemetryStreamSummary) ProtoMessage() {}

func (x *TelemetryStreamSummary) ProtoReflect() protoreflect.Message {
	mi := &file_contracts_proto_control_telemetry_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TelemetryStreamSummary.ProtoReflect.Descriptor instead.
func (*TelemetryStreamSummary) Descriptor() ([]byte, []int) {
	return file_contracts_proto_control_telemetry_proto_rawDescGZIP(), []int{1}
}

func (x *TelemetryStreamSummary) GetAcceptedEvents() uint64 {
	if x != nil {
		return x.AcceptedEvents
	}
	return 0
}

func (x *TelemetryStreamSummary) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// WorkloadsReport carries per-workload runtime telemetry for one sample window.
type WorkloadsReport struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"` // session_id identifies the active control session emitting this report.
	SentUnix      int64                  `protobuf:"varint,2,opt,name=sent_unix,json=sentUnix,proto3" json:"sent_unix,omitempty"`   // sent_unix is when this report snapshot was sampled by the agent.
	Sequence      uint64                 `protobuf:"varint,3,opt,name=sequence,proto3" json:"sequence,omitempty"`                   // sequence is monotonic per session and helps detect dropped report frames.
	Workloads     []*WorkloadRuntime     `protobuf:"bytes,4,rep,name=workloads,proto3" json:"workloads,omitempty"`                  // workloads is the current set of workload runtime records observed on the node.
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WorkloadsReport) Reset() {
	*x = WorkloadsReport{}
	mi := &file_contracts_proto_control_telemetry_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkloadsReport) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkloadsReport) ProtoMessage() {}

func (x *WorkloadsReport) ProtoReflect() protoreflect.Message {
	mi := &file_contracts_proto_control_telemetry_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkloadsReport.ProtoReflect.Descriptor instead.
func (*WorkloadsReport) Descriptor() ([]byte, []int) {
	return file_contracts_proto_control_telemetry_proto_rawDescGZIP(), []int{2}
}

func (x *WorkloadsReport) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *WorkloadsReport) GetSentUnix() int64 {
	if x != nil {
		return x.SentUnix
	}
	return 0
}

func (x *WorkloadsReport) GetSequence() uint64 {
	if x != nil {
		return x.Sequence
	}
	return 0
}

func (x *WorkloadsReport) GetWorkloads() []*WorkloadRuntime {
	if x != nil {
		return x.Workloads
	}
	return nil
}

// WorkloadRuntime captures runtime state and resource usage for one workload instance.
type WorkloadRuntime struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ProjectId       string                 `protobuf:"bytes,1,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`                       // project_id scopes the workload to its owning project.
	WorkloadId      string                 `protobuf:"bytes,2,opt,name=workload_id,json=workloadId,proto3" json:"workload_id,omitempty"`                    // workload_id is the stable control-plane workload identity.
	VmId            string                 `protobuf:"bytes,3,opt,name=vm_id,json=vmId,proto3" json:"vm_id,omitempty"`                                      // vm_id identifies the firecracker microVM instance running this workload.
	State           WorkloadRuntimeState   `protobuf:"varint,4,opt,name=state,proto3,enum=control.v1.WorkloadRuntimeState" json:"state,omitempty"`          // state is the current lifecycle state for this workload instance.
	CpuUsagePercent float64                `protobuf:"fixed64,5,opt,name=cpu_usage_percent,json=cpuUsagePercent,proto3" json:"cpu_usage_percent,omitempty"` // cpu_usage_percent is current workload CPU usage percentage.
	MemoryUsedBytes uint64                 `protobuf:"varint,6,opt,name=memory_used_bytes,json=memoryUsedBytes,proto3" json:"memory_used_bytes,omitempty"`  // memory_used_bytes is current workload memory usage.
	DiskUsedBytes   uint64                 `protobuf:"varint,7,opt,name=disk_used_bytes,json=diskUsedBytes,proto3" json:"disk_used_bytes,omitempty"`        // disk_used_bytes is current writable disk usage for this workload.
	NetworkRxBytes  uint64                 `protobuf:"varint,8,opt,name=network_rx_bytes,json=networkRxBytes,proto3" json:"network_rx_bytes,omitempty"`     // network_rx_bytes is cumulative inbound network traffic for this workload.
	NetworkTxBytes  uint64                 `protobuf:"varint,9,opt,name=network_tx_bytes,json=networkTxBytes,proto3" json:"network_tx_bytes,omitempty"`     // network_tx_bytes is cumulative outbound network traffic for this workload.
	RestartCount    uint32                 `protobuf:"varint,10,opt,name=restart_count,json=restartCount,proto3" json:"restart_count,omitempty"`            // restart_count is the number of restarts observed for this workload instance.
	StartedUnix     int64                  `protobuf:"varint,11,opt,name=started_unix,json=startedUnix,proto3" json:"started_unix,omitempty"`               // started_unix is the workload instance start time in unix seconds.
	Message         string                 `protobuf:"bytes,12,opt,name=message,proto3" json:"message,omitempty"`                                           // message provides optional operator-readable runtime context.
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *WorkloadRuntime) Reset() {
	*x = WorkloadRuntime{}
	mi := &file_contracts_proto_control_telemetry_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkloadRuntime) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkloadRuntime) ProtoMessage() {}

func (x *WorkloadRuntime) ProtoReflect() protoreflect.Message {
	mi := &file_contracts_proto_control_telemetry_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkloadRuntime.ProtoReflect.Descriptor instead.
func (*WorkloadRuntime) Descriptor() ([]byte, []int) {
	return file_contracts_proto_control_telemetry_proto_rawDescGZIP(), []int{3}
}

func (x *WorkloadRuntime) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

func (x *WorkloadRuntime) GetWorkloadId() string {
	if x != nil {
		return x.WorkloadId
	}
	return ""
}

func (x *WorkloadRuntime) GetVmId() string {
	if x != nil {
		return x.VmId
	}
	return ""
}

func (x *WorkloadRuntime) GetState() WorkloadRuntimeState {
	if x != nil {
		return x.State
	}
	return WorkloadRuntimeState_WORKLOAD_RUNTIME_STATE_UNSPECIFIED
}

func (x *WorkloadRuntime) GetCpuUsagePercent() float64 {
	if x != nil {
		return x.CpuUsagePercent
	}
	return 0
}

func (x *WorkloadRuntime) GetMemoryUsedBytes() uint64 {
	if x != nil {
		return x.MemoryUsedBytes
	}
	return 0
}

func (x *WorkloadRuntime) GetDiskUsedBytes() uint64 {
	if x != nil {
		return x.DiskUsedBytes
	}
	return 0
}

func (x *WorkloadRuntime) GetNetworkRxBytes() uint64 {
	if x != nil {
		return x.NetworkRxBytes
	}
	return 0
}

func (x *WorkloadRuntime) GetNetworkTxBytes() uint64 {
	if x != nil {
		return x.NetworkTxBytes
	}
	return 0
}

func (x *WorkloadRuntime) GetRestartCount() uint32 {
	if x != nil {
		return x.RestartCount
	}
	return 0
}

func (x *WorkloadRuntime) GetStartedUnix() int64 {
	if x != nil {
		return x.StartedUnix
	}
	return 0
}

func (x *WorkloadRuntime) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// NodeHealthReport carries machine-level telemetry for scheduling and operations.
type NodeHealthReport struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	SessionId            string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`                                     // session_id identifies the active control session emitting telemetry.
	SentUnix             int64                  `protobuf:"varint,2,opt,name=sent_unix,json=sentUnix,proto3" json:"sent_unix,omitempty"`                                       // sent_unix is when this telemetry snapshot was sampled by the agent.
	NodeStatus           string                 `protobuf:"bytes,3,opt,name=node_status,json=nodeStatus,proto3" json:"node_status,omitempty"`                                  // node_status is a compact label (for example: "ready", "draining", "degraded").
	CpuUsagePercent      float64                `protobuf:"fixed64,4,opt,name=cpu_usage_percent,json=cpuUsagePercent,proto3" json:"cpu_usage_percent,omitempty"`               // cpu_usage_percent is total CPU usage percentage across all cores.
	CpuCores             uint32                 `protobuf:"varint,5,opt,name=cpu_cores,json=cpuCores,proto3" json:"cpu_cores,omitempty"`                                       // cpu_cores is the number of logical CPU cores visible to the agent.
	MemoryTotalBytes     uint64                 `protobuf:"varint,6,opt,name=memory_total_bytes,json=memoryTotalBytes,proto3" json:"memory_total_bytes,omitempty"`             // memory_total_bytes is total node memory capacity.
	MemoryAvailableBytes uint64                 `protobuf:"varint,7,opt,name=memory_available_bytes,json=memoryAvailableBytes,proto3" json:"memory_available_bytes,omitempty"` // memory_available_bytes is currently available memory.
	DiskTotalBytes       uint64                 `protobuf:"varint,8,opt,name=disk_total_bytes,json=diskTotalBytes,proto3" json:"disk_total_bytes,omitempty"`                   // disk_total_bytes is total disk capacity for the primary data volume.
	DiskAvailableBytes   uint64                 `protobuf:"varint,9,opt,name=disk_available_bytes,json=diskAvailableBytes,proto3" json:"disk_available_bytes,omitempty"`       // disk_available_bytes is currently available space on the primary data volume.
	RunningWorkloads     uint32                 `protobuf:"varint,10,opt,name=running_workloads,json=runningWorkloads,proto3" json:"running_workloads,omitempty"`              // running_workloads is the number of active workloads currently running.
	QueuedWorkloads      uint32                 `protobuf:"varint,11,opt,name=queued_workloads,json=queuedWorkloads,proto3" json:"queued_workloads,omitempty"`                 // queued_workloads is the number of pending workloads waiting to start.
	UptimeSeconds        uint64                 `protobuf:"varint,12,opt,name=uptime_seconds,json=uptimeSeconds,proto3" json:"uptime_seconds,omitempty"`                       // uptime_seconds is host uptime since the last reboot.
	BootIdHash           string                 `protobuf:"bytes,13,opt,name=boot_id_hash,json=bootIdHash,proto3" json:"boot_id_hash,omitempty"`                               // boot_id_hash is a privacy-safe hash used to detect host reboot cycles.
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *NodeHealthReport) Reset() {
	*x = NodeHealthReport{}
	mi := &file_contracts_proto_control_telemetry_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeHealthReport) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeHealthReport) ProtoMessage() {}

func (x *NodeHealthReport) ProtoReflect() protoreflect.Message {
	mi := &file_contracts_proto_control_telemetry_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeHealthReport.ProtoReflect.Descriptor instead.
func (*NodeHealthReport) Descriptor() ([]byte, []int) {
	return file_contracts_proto_control_telemetry_proto_rawDescGZIP(), []int{4}
}

func (x *NodeHealthReport) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *NodeHealthReport) GetSentUnix() int64 {
	if x != nil {
		return x.SentUnix
	}
	return 0
}

func (x *NodeHealthReport) GetNodeStatus() string {
	if x != nil {
		return x.NodeStatus
	}
	return ""
}

func (x *NodeHealthReport) GetCpuUsagePercent() float64 {
	if x != nil {
		return x.CpuUsagePercent
	}
	return 0
}

func (x *NodeHealthReport) GetCpuCores() uint32 {
	if x != nil {
		return x.CpuCores
	}
	return 0
}

func (x *NodeHealthReport) GetMemoryTotalBytes() uint64 {
	if x != nil {
		return x.MemoryTotalBytes
	}
	return 0
}

func (x *NodeHealthReport) GetMemoryAvailableBytes() uint64 {
	if x != nil {
		return x.MemoryAvailableBytes
	}
	return 0
}

func (x *NodeHealthReport) GetDiskTotalBytes() uint64 {
	if x != nil {
		return x.DiskTotalBytes
	}
	return 0
}

func (x *NodeHealthReport) GetDiskAvailableBytes() uint64 {
	if x != nil {
		return x.DiskAvailableBytes
	}
	return 0
}

func (x *NodeHealthReport) GetRunningWorkloads() uint32 {
	if x != nil {
		return x.RunningWorkloads
	}
	return 0
}

func (x *NodeHealthReport) GetQueuedWorkloads() uint32 {
	if x != nil {
		return x.QueuedWorkloads
	}
	return 0
}

func (x *NodeHealthReport) GetUptimeSeconds() uint64 {
	if x != nil {
		return x.UptimeSeconds
	}
	return 0
}

func (x *NodeHealthReport) GetBootIdHash() string {
	if x != nil {
		return x.BootIdHash
	}
	return ""
}

var File_contracts_proto_control_telemetry_proto protoreflect.FileDescriptor

const file_contracts_proto_control_telemetry_proto_rawDesc = "" +
	"\n" +
	"'contracts/proto/control/telemetry.proto\x12\n" +
	"control.v1\"\xc3\x01\n" +
	"\x0eTelemetryEvent\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12?\n" +
	"\vnode_health\x18\x02 \x01(\v2\x1c.control.v1.NodeHealthReportH\x00R\n" +
	"nodeHealth\x12H\n" +
	"\x10workloads_report\x18\x03 \x01(\v2\x1b.control.v1.WorkloadsReportH\x00R\x0fworkloadsReportB\a\n" +
	"\x05event\"[\n" +
	"\x16TelemetryStreamSummary\x12'\n" +
	"\x0faccepted_events\x18\x01 \x01(\x04R\x0eacceptedEvents\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\xa4\x01\n" +
	"\x0fWorkloadsReport\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x1b\n" +
	"\tsent_unix\x18\x02 \x01(\x03R\bsentUnix\x12\x1a\n" +
	"\bsequence\x18\x03 \x01(\x04R\bsequence\x129\n" +
	"\tworkloads\x18\x04 \x03(\v2\x1b.control.v1.WorkloadRuntimeR\tworkloads\"\xd4\x03\n" +
	"\x0fWorkloadRuntime\x12\x1d\n" +
	"\n" +
	"project_id\x18\x01 \x01(\tR\tprojectId\x12\x1f\n" +
	"\vworkload_id\x18\x02 \x01(\tR\n" +
	"workloadId\x12\x13\n" +
	"\x05vm_id\x18\x03 \x01(\tR\x04vmId\x126\n" +
	"\x05state\x18\x04 \x01(\x0e2 .control.v1.WorkloadRuntimeStateR\x05state\x12*\n" +
	"\x11cpu_usage_percent\x18\x05 \x01(\x01R\x0fcpuUsagePercent\x12*\n" +
	"\x11memory_used_bytes\x18\x06 \x01(\x04R\x0fmemoryUsedBytes\x12&\n" +
	"\x0fdisk_used_bytes\x18\a \x01(\x04R\rdiskUsedBytes\x12(\n" +
	"\x10network_rx_bytes\x18\b \x01(\x04R\x0enetworkRxBytes\x12(\n" +
	"\x10network_tx_bytes\x18\t \x01(\x04R\x0enetworkTxBytes\x12#\n" +
	"\rrestart_count\x18\n" +
	" \x01(\rR\frestartCount\x12!\n" +
	"\fstarted_unix\x18\v \x01(\x03R\vstartedUnix\x12\x18\n" +
	"\amessage\x18\f \x01(\tR\amessage\"\x99\x04\n" +
	"\x10NodeHealthReport\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x1b\n" +
	"\tsent_unix\x18\x02 \x01(\x03R\bsentUnix\x12\x1f\n" +
	"\vnode_status\x18\x03 \x01(\tR\n" +
	"nodeStatus\x12*\n" +
	"\x11cpu_usage_percent\x18\x04 \x01(\x01R\x0fcpuUsagePercent\x12\x1b\n" +
	"\tcpu_cores\x18\x05 \x01(\rR\bcpuCores\x12,\n" +
	"\x12memory_total_bytes\x18\x06 \x01(\x04R\x10memoryTotalBytes\x124\n" +
	"\x16memory_available_bytes\x18\a \x01(\x04R\x14memoryAvailableBytes\x12(\n" +
	"\x10disk_total_bytes\x18\b \x01(\x04R\x0ediskTotalBytes\x120\n" +
	"\x14disk_available_bytes\x18\t \x01(\x04R\x12diskAvailableBytes\x12+\n" +
	"\x11running_workloads\x18\n" +
	" \x01(\rR\x10runningWorkloads\x12)\n" +
	"\x10queued_workloads\x18\v \x01(\rR\x0fqueuedWorkloads\x12%\n" +
	"\x0euptime_seconds\x18\f \x01(\x04R\ruptimeSeconds\x12 \n" +
	"\fboot_id_hash\x18\r \x01(\tR\n" +
	"bootIdHash*\x97\x02\n" +
	"\x14WorkloadRuntimeState\x12&\n" +
	"\"WORKLOAD_RUNTIME_STATE_UNSPECIFIED\x10\x00\x12\"\n" +
	"\x1eWORKLOAD_RUNTIME_STATE_PENDING\x10\x01\x12#\n" +
	"\x1fWORKLOAD_RUNTIME_STATE_STARTING\x10\x02\x12\"\n" +
	"\x1eWORKLOAD_RUNTIME_STATE_RUNNING\x10\x03\x12#\n" +
	"\x1fWORKLOAD_RUNTIME_STATE_DRAINING\x10\x04\x12\"\n" +
	"\x1eWORKLOAD_RUNTIME_STATE_STOPPED\x10\x05\x12!\n" +
	"\x1dWORKLOAD_RUNTIME_STATE_FAILED\x10\x06B9Z7github.com/t0gun/spacescale/packages/go/pb/v1;controlpbb\x06proto3"

var (
	file_contracts_proto_control_telemetry_proto_rawDescOnce sync.Once
	file_contracts_proto_control_telemetry_proto_rawDescData []byte
)

func file_contracts_proto_control_telemetry_proto_rawDescGZIP() []byte {
	file_contracts_proto_control_telemetry_proto_rawDescOnce.Do(func() {
		file_contracts_proto_control_telemetry_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_contracts_proto_control_telemetry_proto_rawDesc), len(file_contracts_proto_control_telemetry_proto_rawDesc)))
	})
	return file_contracts_proto_control_telemetry_proto_rawDescData
}

var file_contracts_proto_control_telemetry_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_contracts_proto_control_telemetry_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_contracts_proto_control_telemetry_proto_goTypes = []any{
	(WorkloadRuntimeState)(0),      // 0: control.v1.WorkloadRuntimeState
	(*TelemetryEvent)(nil),         // 1: control.v1.TelemetryEvent
	(*TelemetryStreamSummary)(nil), // 2: control.v1.TelemetryStreamSummary
	(*WorkloadsReport)(nil),        // 3: control.v1.WorkloadsReport
	(*WorkloadRuntime)(nil),        // 4: control.v1.WorkloadRuntime
	(*NodeHealthReport)(nil),       // 5: control.v1.NodeHealthReport
}
var file_contracts_proto_control_telemetry_proto_depIdxs = []int32{
	5, // 0: control.v1.TelemetryEvent.node_health:type_name -> control.v1.NodeHealthReport
	3, // 1: control.v1.TelemetryEvent.workloads_report:type_name -> control.v1.WorkloadsReport
	4, // 2: control.v1.WorkloadsReport.workloads:type_name -> control.v1.WorkloadRuntime
	0, // 3: control.v1.WorkloadRuntime.state:type_name -> control.v1.WorkloadRuntimeState
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_contracts_proto_control_telemetry_proto_init() }
func file_contracts_proto_control_telemetry_proto_init() {
	if File_contracts_proto_control_telemetry_proto != nil {
		return
	}
	file_contracts_proto_control_telemetry_proto_msgTypes[0].OneofWrappers = []any{
		(*TelemetryEvent_NodeHealth)(nil),
		(*TelemetryEvent_WorkloadsReport)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_contracts_proto_control_telemetry_proto_rawDesc), len(file_contracts_proto_control_telemetry_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_contracts_proto_control_telemetry_proto_goTypes,
		DependencyIndexes: file_contracts_proto_control_telemetry_proto_depIdxs,
		EnumInfos:         file_contracts_proto_control_telemetry_proto_enumTypes,
		MessageInfos:      file_contracts_proto_control_telemetry_proto_msgTypes,
	}.Build()
	File_contracts_proto_control_telemetry_proto = out.File
	file_contracts_proto_control_telemetry_proto_goTypes = nil
	file_contracts_proto_control_telemetry_proto_depIdxs = nil
}
