// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.0
// source: proto/v1/node.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type NodeHeartbeat struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	NodeId         string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`                              // Who am I?
	SeqNo          uint64                 `protobuf:"varint,2,opt,name=seq_no,json=seqNo,proto3" json:"seq_no,omitempty"`                                // Am I dropping packets?
	BootId         string                 `protobuf:"bytes,3,opt,name=boot_id,json=bootId,proto3" json:"boot_id,omitempty"`                              // Did I suddenly reboot?
	SentAtUnixNano int64                  `protobuf:"varint,4,opt,name=sent_at_unix_nano,json=sentAtUnixNano,proto3" json:"sent_at_unix_nano,omitempty"` // Is there network lag?
	Region         string                 `protobuf:"bytes,5,opt,name=region,proto3" json:"region,omitempty"`                                            // Provisioned placement region for this node.
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *NodeHeartbeat) Reset() {
	*x = NodeHeartbeat{}
	mi := &file_proto_v1_node_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeHeartbeat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeHeartbeat) ProtoMessage() {}

func (x *NodeHeartbeat) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_node_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeHeartbeat.ProtoReflect.Descriptor instead.
func (*NodeHeartbeat) Descriptor() ([]byte, []int) {
	return file_proto_v1_node_proto_rawDescGZIP(), []int{0}
}

func (x *NodeHeartbeat) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *NodeHeartbeat) GetSeqNo() uint64 {
	if x != nil {
		return x.SeqNo
	}
	return 0
}

func (x *NodeHeartbeat) GetBootId() string {
	if x != nil {
		return x.BootId
	}
	return ""
}

func (x *NodeHeartbeat) GetSentAtUnixNano() int64 {
	if x != nil {
		return x.SentAtUnixNano
	}
	return 0
}

func (x *NodeHeartbeat) GetRegion() string {
	if x != nil {
		return x.Region
	}
	return ""
}

var File_proto_v1_node_proto protoreflect.FileDescriptor

const file_proto_v1_node_proto_rawDesc = "" +
	"\n" +
	"\x13proto/v1/node.proto\x12\rspacescale.v1\"\x9b\x01\n" +
	"\rNodeHeartbeat\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12\x15\n" +
	"\x06seq_no\x18\x02 \x01(\x04R\x05seqNo\x12\x17\n" +
	"\aboot_id\x18\x03 \x01(\tR\x06bootId\x12)\n" +
	"\x11sent_at_unix_nano\x18\x04 \x01(\x03R\x0esentAtUnixNano\x12\x16\n" +
	"\x06region\x18\x05 \x01(\tR\x06regionB,Z*github.com/spacescale/core/shared/pb/v1;pbb\x06proto3"

var (
	file_proto_v1_node_proto_rawDescOnce sync.Once
	file_proto_v1_node_proto_rawDescData []byte
)

func file_proto_v1_node_proto_rawDescGZIP() []byte {
	file_proto_v1_node_proto_rawDescOnce.Do(func() {
		file_proto_v1_node_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_v1_node_proto_rawDesc), len(file_proto_v1_node_proto_rawDesc)))
	})
	return file_proto_v1_node_proto_rawDescData
}

var file_proto_v1_node_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_proto_v1_node_proto_goTypes = []any{
	(*NodeHeartbeat)(nil), // 0: spacescale.v1.NodeHeartbeat
}
var file_proto_v1_node_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_v1_node_proto_init() }
func file_proto_v1_node_proto_init() {
	if File_proto_v1_node_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_v1_node_proto_rawDesc), len(file_proto_v1_node_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_v1_node_proto_goTypes,
		DependencyIndexes: file_proto_v1_node_proto_depIdxs,
		MessageInfos:      file_proto_v1_node_proto_msgTypes,
	}.Build()
	File_proto_v1_node_proto = out.File
	file_proto_v1_node_proto_goTypes = nil
	file_proto_v1_node_proto_depIdxs = nil
}
